# seqr development environment

# shell
export PS1="\h:\w]$ "

export SHELL=/bin/bash

export LS_OPTIONS='--color=auto'
alias ll="ls -al"
alias less='less -m -g -i--underline-special --SILENT'
alias more='less'

export TERM=xterm


# databases

export PGHOST=${POSTGRES_SVC_SERVICE_HOST}
export PGUSER=postgres

resize
