apiVersion: batch/v1
kind: Job
metadata:
  name: configure-es-snapshot-repo
  labels:
    name: configure-es-snapshot-repo
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: addrepo
        image: curlimages/curl:7.75.0
        env:
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secrets
              key: elasticsearch.password
        - name: ELASTICSEARCH_SERVICE_HOSTNAME
          value: "{{ ELASTICSEARCH_SERVICE_HOSTNAME }}"
        - name: ES_SNAPSHOTS_BUCKET
          value: "{{ ES_SNAPSHOTS_BUCKET }}"
        args:
        - /bin/sh
        - -c
        - |
            curl -u "kibana:$ES_PASSWORD" -X PUT "${ELASTICSEARCH_SERVICE_HOSTNAME}:9200/_snapshot/snapshot_storage?pretty" -H 'Content-Type: application/json' --data @- <<EOF
            {
              "type": "gcs",
              "settings": {
                "bucket": "${ES_SNAPSHOTS_BUCKET}",
                "client": "default",
                "compress": true
              }
            }
            EOF
      restartPolicy: Never
