# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0036_auto_20180415_2250'),
        ('gene_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelist',
            name='seqr_locus_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.LocusList'),
        ),
    ]
