# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20191126_2052'),
        ('gene_lists', '0002_genelist_seqr_locus_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='genelist',
            name='seqr_locus_list',
        ),
        migrations.RemoveField(
            model_name='genelistitem',
            name='gene_list',
        ),
        migrations.DeleteModel(
            name='GeneList',
        ),
        migrations.DeleteModel(
            name='GeneListItem',
        ),
    ]
