# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakpoint_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreakpointFile',
        ),
        migrations.RemoveField(
            model_name='breakpointgene',
            name='breakpoint',
        ),
        migrations.RemoveField(
            model_name='breakpointmetadata',
            name='breakpoint',
        ),
        migrations.DeleteModel(
            name='Breakpoint',
        ),
        migrations.DeleteModel(
            name='BreakpointGene',
        ),
        migrations.DeleteModel(
            name='BreakpointMetaData',
        ),
    ]
