# based on http://stackoverflow.com/questions/40136891/gcloud-ingress-loadbalancer-static-ip

apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-svc
  annotations:
    service.beta.kubernetes.io/external-traffic: 'OnlyLocal'
spec:
  type: LoadBalancer
  loadBalancerIP: {{ CLUSTER_EXTERNAL_IP }}  # static IP pre-allocated.
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: nginx-ingress