# In order for the Ingress resource to work, the cluster must have an Ingress controller running.
# You need to choose the ingress controller implementation that is the best fit for your cluster.
# More docs can be found here:
#  https://kubernetes.io/docs/concepts/services-networking/ingress

#  The Google k8s nginx controller is being refactored (https://github.com/kubernetes/ingress/tree/master/controllers/nginx), so using
#  the NGINX-provided controller:
#
#     https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml
#
#  which is more complete.
#
#  Customizations:
#      https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/README.md



# NGINX config based on: https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/README.md

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  hsts: "true"

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx-ingress-rc
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.8.0
        imagePullPolicy: Always
        name: nginx-pod
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
