kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  #host: {{ HOSTNAME }}
  tls:
    - secretName: nginx-secrets
  backend:
    serviceName: seqr-svc
    servicePort: 8000
