# Generated by Django 3.1.13 on 2021-09-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('seqr', '0001_squashed_0067_remove_project_custom_reference_populations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaLocusList',
            fields=[
                ('seqr_locus_list',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='seqr.locuslist')),
                ('panel_app_id', models.IntegerField(unique=True)),
                ('disease_group', models.TextField(blank=True, null=True)),
                ('disease_sub_group', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('version_created', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(max_length=2000)),
                ('raw_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PaLocusListGene',
            fields=[
                ('seqr_locus_list_gene',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='seqr.locuslistgene')),
                ('confidence_level',
                 models.CharField(choices=[('1', 'RED'), ('2', 'AMBER'), ('3', 'GREEN'), ('4', 'GREEN')],
                                  max_length=1)),
                ('biotype', models.TextField(blank=True, null=True)),
                ('penetrance', models.TextField(blank=True, null=True)),
                ('mode_of_pathogenicity', models.TextField(blank=True, null=True)),
                ('mode_of_inheritance', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
        ),
    ]
