# Generated by Django 3.1.13 on 2021-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palocuslist',
            name='panel_app_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='palocuslist',
            name='url',
            field=models.TextField(max_length=2000, unique=True),
        ),
    ]
