# Generated by Django 4.2.24 on 2025-12-09 20:55

from django.db import migrations, models


def set_source(apps, schema_editor):
    PaLocusList = apps.get_model('panelapp', 'PaLocusList')
    db_alias = schema_editor.connection.alias
    PaLocusList.objects.using(db_alias).filter(url__startswith='https://panelapp-aus.org').update(source='AU')
    PaLocusList.objects.using(db_alias).filter(url__startswith='https://panelapp.genomicsengland.co.uk').update(source='UK')


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0003_panelapp_aus_domain_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='palocuslist',
            name='source',
            field=models.CharField(choices=[('AU', 'AU'), ('UK', 'UK')], max_length=2, null=True),
        ),
        migrations.RunPython(set_source),
        migrations.AlterField(
            model_name='palocuslist',
            name='source',
            field=models.CharField(choices=[('AU', 'AU'), ('UK', 'UK')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='palocuslist',
            unique_together={('source', 'panel_app_id')},
        ),
        migrations.RemoveField(
            model_name='palocuslist',
            name='url',
        ),
    ]
