
//possible values
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_NEW = 'SHOW_NEW'

export const SORT_BY_FAMILY_NAME = 'SORT_BY_FAMILY_NAME'
export const SORT_BY_DATE_CREATED = 'SORT_BY_DATE_CREATED'
//export const SORT_BY_DATE_ACCESSED = 'SORT_BY_DATE_ACCESSED'


// modal
export const EDIT_NAME_MODAL = 'EDIT_NAME'
export const EDIT_DESCRIPTION_MODAL = 'EDIT_DESCRIPTION'

export const MODAL_SAVING = 'MODAL_SAVING'
export const MODAL_SAVE_SUCCEEDED = 'MODAL_SAVE_SUCCEEDED'
export const MODAL_SAVE_ERROR = 'MODAL_SAVE_ERROR'
