#!/usr/bin/env python

import os
import sys

print(os.name)
def r(command):
    print("Running: %s" % command)
    result = os.system(command)
    if result != 0:
        sys.exit('%s returned %s' % (command, result))

is_mac = False
is_linux = False
if os.name == "mac":
    is_mac = True
elif os.name == "posix":
    is_linux = True
else:
    raise ValueError("Unexpected os: " + os.name)

if is_linux:
    r("sudo yum install -y wget python.x86_64 git")

r("cd /local/software/")

# seqr repo
r("git clone https://github.com/macarthur-lab/seqr")
  
# postgres - download binaries from https://www.enterprisedb.com/download-postgresql-binaries
r("mkdir -p postgres")
r("cd postgres")
if is_mac:
    r("wget -O postgresql-9.5.5-1-osx-binaries.tar.gz 'https://www.enterprisedb.com/postgresql-960-binaries-osx?ls=Crossover&type=Crossover'")
elif is_linux:
    r("wget -O postgresql-9.6.1-1-linux-x64-binaries.tar.gz 'https://www.enterprisedb.com/postgresql-948-binaries-linux64?ls=Crossover&type=Crossover'")
r("tar xzf *.tar.gz")





"""
Commands to format and mount new disk:

sudo mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-seqr-disk
sudo mkdir -p /mnt/disks/google-seqr-disk
sudo mount -o discard,defaults /dev/disk/by-id/google-seqr-disk /mnt/disks/google-seqr-disk
sudo chmod a+w /mnt/disks/google-seqr-disk

# add to /etc/fstab for auto-startup
echo UUID=`sudo blkid -s UUID -o value /dev/disk/by-id/google-seqr-disk` /mnt/disks/google-seqr-disk ext4 discard,defaults,nofail 0 2 | sudo tee -a /etc/fstab
"""

# python 2.7
# supervisord
# phenotips
# gunicorn
# nginx
# github
