# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakerresult',
            name='originating_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_results', to='matchmaker.MatchmakerSubmission'),
        ),
    ]
