# Generated by Django 3.2.14 on 2022-09-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_alter_matchmakersubmission_individual'),
        ('seqr', '0047_auto_20220908_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='genomic_features',
        ),
    ]
