# Generated by Django 3.2.14 on 2022-09-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_alter_matchmakersubmission_individual'),
        ('seqr', '0047_savedvariant_matchmaker_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='genomic_features',
        ),
    ]
