# Generated by Django 4.2.24 on 2025-12-19 16:44

import django.contrib.postgres.fields
from django.db import migrations, models
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_auto_20220921_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakersubmission',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=matchmaker.models.get_mme_contact_default, size=None),
        ),
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='contact_href',
        ),
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='contact_name',
        ),
    ]
