# Generated by Django 4.2.24 on 2025-12-19 16:44

import django.contrib.postgres.fields
from django.db import migrations, models
import matchmaker.models


def set_contacts(apps, schema_editor):
    MatchmakerSubmission = apps.get_model("matchmaker", "MatchmakerSubmission")
    db_alias = schema_editor.connection.alias
    submissions = list(MatchmakerSubmission.objects.using(db_alias).all())
    for submission in submissions:
        emails = submission.contact_href.replace('mailto:', '').split(',')
        names = submission.contact_name.split(',')
        submission.contacts = [
            {'email': email.strip(), 'name': names[i].strip() if i < len(names) else ''}
            for i, email in enumerate(emails)
        ]
    MatchmakerSubmission.objects.using(db_alias).bulk_update(submissions, ['contacts'])


def set_legacy_contacts(apps, schema_editor):
    MatchmakerSubmission = apps.get_model("matchmaker", "MatchmakerSubmission")
    db_alias = schema_editor.connection.alias
    submissions = list(MatchmakerSubmission.objects.using(db_alias).all())
    for submission in submissions:
        submission.contact_name = ','.join([contact['name'] for contact in submission.contacts])
        submission.contact_href = f"mailto:{','.join([contact['email'] for contact in submission.contacts])}"
    MatchmakerSubmission.objects.using(db_alias).bulk_update(submissions, ['contact_name', 'contact_href'])


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_auto_20220921_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakersubmission',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=matchmaker.models.get_mme_contact_default, size=None),
        ),
        migrations.RunPython(set_contacts, reverse_code=set_legacy_contacts),
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='contact_href',
        ),
        migrations.RemoveField(
            model_name='matchmakersubmission',
            name='contact_name',
        ),
    ]
