/* eslint-disable no-multi-spaces */

//possible values
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_NEW = 'SHOW_NEW'

export const SORT_BY_PROJECT_NAME = 'SORT_BY_PROJECT_NAME'
export const SORT_BY_PROJECT_SAMPLES = 'SORT_BY_PROJECT_SAMPLES'
export const SORT_BY_NUM_FAMILIES = 'SORT_BY_NUM_FAMILIES'
export const SORT_BY_NUM_INDIVIDUALS = 'SORT_BY_NUM_INDIVIDUALS'
export const SORT_BY_DATE_CREATED = 'SORT_BY_DATE_CREATED'
export const SORT_BY_DATE_LAST_ACCESSED = 'SORT_BY_DATE_LAST_ACCESSED'
export const SORT_BY_TAGS = 'SORT_BY_TAGS'
export const SORT_BY_ANALYSIS = 'SORT_BY_ANALYSIS'

//export const SORT_BY_DATE_ACCESSED = 'SORT_BY_DATE_ACCESSED'

// modal
export const EDIT_NAME_MODAL = 'EDIT_NAME'
export const EDIT_DESCRIPTION_MODAL = 'EDIT_DESCRIPTION'
export const EDIT_CATEGORY_MODAL = 'EDIT_CATEGORY'
export const ADD_PROJECT_MODAL = 'ADD_PROJECT'
export const DELETE_PROJECT_MODAL = 'DELETE_PROJECT'

