SEX_MALE = 'M'
SEX_FEMALE = 'F'
SEX_UNKNOWN = 'U'
FEMALE_ANEUPLOIDIES = ['XXX', 'X0']
MALE_ANEUPLOIDIES = ['XXY', 'XYY']
FEMALE_SEXES = [SEX_FEMALE, *FEMALE_ANEUPLOIDIES]
MALE_SEXES = [SEX_MALE, *MALE_ANEUPLOIDIES]

AFFECTED_STATUS_AFFECTED = 'A'
AFFECTED_STATUS_UNAFFECTED = 'N'
AFFECTED_STATUS_UNKNOWN = 'U'

SAMPLE_TYPE_WES = 'WES'
SAMPLE_TYPE_WGS = 'WGS'
DATASET_TYPE_VARIANT_CALLS = 'SNV_INDEL'
DATASET_TYPE_SV_CALLS = 'SV'
DATASET_TYPE_MITO_CALLS = 'MITO'

GENOME_VERSION_GRCh37 = '37'
GENOME_VERSION_GRCh38 = '38'
