/* eslint-disable no-multi-spaces */

export const CASE_REVIEW_STATUS_NOT_IN_REVIEW = 'N'
export const CASE_REVIEW_STATUS_IN_REVIEW = 'I'
export const CASE_REVIEW_STATUS_UNCERTAIN = 'U'
export const CASE_REVIEW_STATUS_ACCEPTED = 'A'
export const CASE_REVIEW_STATUS_NOT_ACCEPTED = 'R'
export const CASE_REVIEW_STATUS_MORE_INFO_NEEDED = 'Q'

export const CASE_REVIEW_STATUS_ACCEPTED_FOR_STORE_DNA = 'S'
export const CASE_REVIEW_STATUS_ACCEPTED_FOR_ARRAY = 'A'
export const CASE_REVIEW_STATUS_ACCEPTED_FOR_EXOME = 'E'
export const CASE_REVIEW_STATUS_ACCEPTED_FOR_GENOME = 'G'
export const CASE_REVIEW_STATUS_ACCEPTED_FOR_RNASEQ = 'R'
export const CASE_REVIEW_STATUS_ACCEPTED_FOR_REPROCESSING = 'P'

