GENOME_VERSION_GRCh38_DISPLAY = 'GRCh38'

AFFECTED = 'A'
UNAFFECTED = 'N'
AFFECTED_ID = 0
UNAFFECTED_ID = 1

VARIANT_DATASET = 'VARIANTS'

VARIANT_KEY_FIELD = 'variantId'
GNOMAD_GENOMES_FIELD = 'gnomad_genomes'

XPOS = 'xpos'
