FROM ubuntu:18.04 as build

# NB: This code is a copy of GRCh38 except for the loftee branch.

RUN apt-get update && apt-get -y install wget libncurses5-dev libncursesw5-dev libbz2-dev liblzma-dev build-essential libz-dev git
RUN wget https://github.com/samtools/samtools/releases/download/1.7/samtools-1.7.tar.bz2 && tar xjvf samtools-1.7.tar.bz2 && cd samtools-1.7 && make && make install
RUN git clone https://github.com/konradjk/loftee.git

FROM ensemblorg/ensembl-vep:release_110.1 as runtime
RUN cpanm DBD::SQLite
COPY --from=build /usr/local/bin/samtools /usr/local/bin/samtools
COPY --from=build /loftee/ /plugins
