# Generated by Django 4.2.20 on 2025-04-16 20:35

import clickhouse_backend.models
import clickhouse_search.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntriesGrch38SnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField()),
                ('family_guid', clickhouse_backend.models.StringField()),
                ('sample_ids', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('xpos', clickhouse_backend.models.UInt64Field()),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('is_gnomad_gt_5_percent', clickhouse_backend.models.BoolField()),
                ('gt', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'REF'), (1, 'HET'), (2, 'HOM')], null=True), db_column='GT')),
                ('gq', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Int32Field(blank=True, null=True), db_column='GQ')),
                ('ab', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float32Field(blank=True, null=True), db_column='AB')),
                ('dp', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Int32Field(blank=True, null=True), db_column='DP')),
                ('sign', clickhouse_backend.models.Int8Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/entries',
                'ordering': ['project_guid', 'family_guid', 'is_gnomad_gt_5_percent', 'key'],
                'engine': clickhouse_search.models.CollapsingMergeTree('sign', deduplicate_merge_projection_mode='rebuild', index_granularity=8192, order_by=('project_guid', 'family_guid', 'is_gnomad_gt_5_percent', 'key')),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
