# Generated by Django 4.2.20 on 2025-04-25 20:26

import clickhouse_backend.models
import clickhouse_search.backend.fields
import clickhouse_search.backend.engines
import clickhouse_search.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from settings import CLICKHOUSE_IN_MEMORY_DIR, CLICKHOUSE_DATA_DIR

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
