# Generated by Django 4.2.21 on 2025-06-12 21:14

import clickhouse_backend.models
import clickhouse_search.backend.engines
import clickhouse_search.backend.fields
import clickhouse_search.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0001_initial'),
    ]

    operations = [
    ]
