# Generated by Django 4.2.21 on 2025-06-13 00:44

import clickhouse_backend.models
import clickhouse_search.backend.engines
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0002_annotationsdiskgrch37snvindel_and_more'),
    ]

    operations = [
    ]
