# Generated by Django 4.2.21 on 2025-06-13 02:50

import clickhouse_backend.models
import clickhouse_search.backend.engines
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0004_annotationsdisksv_annotationssv_entriessv'),
    ]

    operations = [
    ]
