# Generated by Django 4.2.21 on 2025-06-23 14:57

import clickhouse_backend.models
import clickhouse_search.backend.engines
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0005_annotationsdiskgcnv_annotationsgcnv_entriesgcnv_and_more'),
    ]

    operations = [
    ]
