# Generated by Django 4.2.21 on 2025-06-23 17:58

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0006_keylookupgcnv_keylookupgrch37snvindel_keylookupmito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGtStatsGRCh37SnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('ref_samples', clickhouse_backend.models.UInt32Field()),
                ('het_samples', clickhouse_backend.models.UInt32Field()),
                ('hom_samples', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/project_gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by=('project_guid', 'key', 'sample_type'), partition_by='project_guid'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGtStatsMito',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('ref_samples', clickhouse_backend.models.UInt32Field()),
                ('het_samples', clickhouse_backend.models.UInt32Field()),
                ('hom_samples', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/project_gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by=('project_guid', 'key', 'sample_type'), partition_by='project_guid'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGtStatsSnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('ref_samples', clickhouse_backend.models.UInt32Field()),
                ('het_samples', clickhouse_backend.models.UInt32Field()),
                ('hom_samples', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/project_gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by=('project_guid', 'key', 'sample_type'), partition_by='project_guid'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGtStatsSv',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssv')),
                ('ref_samples', clickhouse_backend.models.UInt32Field()),
                ('het_samples', clickhouse_backend.models.UInt32Field()),
                ('hom_samples', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SV/project_gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by=('project_guid', 'key'), partition_by='project_guid'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
