# Generated by Django 4.2.21 on 2025-06-23 17:58

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0006_keylookupgcnv_keylookupgrch37snvindel_keylookupmito_and_more'),
    ]

    operations = [
    ]
