# Generated by Django 4.2.21 on 2025-06-23 20:06

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0007_projectgtstatsgrch37snvindel_projectgtstatsmito_and_more'),
    ]

    operations = [
    ]
