# Generated by Django 4.2.21 on 2025-06-23 20:06

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0007_projectgtstatsgrch37snvindel_projectgtstatsmito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtStatsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsMito',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('ac_het_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_het_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wgs', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsSv',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssv')),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SV/gt_stats',
                'abstract': False,
                'engine': clickhouse_backend.models.SummingMergeTree(index_granularity=8192, order_by='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
