# Generated by Django 4.2.21 on 2025-07-15 16:39

import clickhouse_backend.models
import clickhouse_search.backend.fields
import clickhouse_search.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0009_materializedviews_and_dictionaries'),
    ]

    operations = [
    ]
