# Generated by Django 4.2.21 on 2025-08-06 00:31

import clickhouse_backend.models
import clickhouse_search.backend.fields
import clickhouse_search.backend.engines
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0011_clinvar_materialized_view'),
    ]

    operations = [
    ]
