# Generated by Django 4.2.21 on 2025-08-13 19:35 and editted manually by the seqr team

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0013_annotationsdiskgcnv_annotationsdiskmito_and_more'),
    ]

    operations = [
    ]
