# Generated by Django 4.2.21 on 2025-08-13 19:35 and editted manually by the seqr team

import os
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

GNOMAD_GENOMES_DICT = Template(Template("""
CREATE DICTIONARY `$reference_genome/$dataset_type/gnomad_genomes_dict`
(
    key UInt32,
    filter_af Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(USER $clickhouse_writer_user PASSWORD $clickhouse_writer_password TABLE `$reference_genome/$dataset_type/gnomad_genomes`))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE $size))
""").safe_substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
))


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0013_annotationsdiskgcnv_annotationsdiskmito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadGenomesGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/gnomad_genomes',
                'engine': clickhouse_backend.models.ReplacingMergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadGenomesSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/gnomad_genomes',
                'engine': clickhouse_backend.models.ReplacingMergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            GNOMAD_GENOMES_DICT.substitute(
                reference_genome='GRCh37',
                dataset_type='SNV_INDEL',
                size=int(1e8),
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            GNOMAD_GENOMES_DICT.substitute(
                reference_genome='GRCh38',
                dataset_type='SNV_INDEL',
                size=int(5e8),
            ),
            hints={'clickhouse': True},
        ),
    ]
