# Generated by Django 4.2.22 on 2025-08-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0014_gnomadgenomesgrch37snvindel_gnomadgenomessnvindel'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh37/SNV_INDEL/gnomad_genomes_dict`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh38/SNV_INDEL/gnomad_genomes_dict`',
            hints={'clickhouse': True},
        ),
        migrations.DeleteModel(
            name='GnomadGenomesGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='GnomadGenomesSnvIndel',
        ),
    ]
