# Generated by Django 4.2.21 on 2025-10-01 20:29
# Modified by the seqr team.

import clickhouse_backend.models

from django.db import migrations
import os
from string import Template

from settings import DATABASES

CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

GT_STATS_DICT = Template(Template("""
CREATE DICTIONARY `$reference_genome/$dataset_type/gt_stats_dict`
(
    key UInt32,
    $columns
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(USER '$clickhouse_writer_user' PASSWORD '$clickhouse_writer_password' TABLE `$reference_genome/$dataset_type/gt_stats`))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE $size))
""").safe_substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
))

SEQRDB_AFFECTED_STATUS_DICT = Template("""
CREATE DICTIONARY `seqrdb_affected_status_dict`
(
    `family_guid` String,
    `sampleId` String,
    `affected` String
)
PRIMARY KEY family_guid, sampleId
SOURCE(POSTGRESQL(
    NAME 'seqr_postgres_named_collection' 
    DATABASE $database
    QUERY 'select f.guid as family_guid, i.individual_id as sample_id, i.affected FROM seqr_individual i INNER JOIN seqr_family f ON i.family_id = f.id'
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(COMPLEX_KEY_HASHED());
""").substitute(
    database=DATABASES['default']['NAME'],
)

CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS  = os.environ.get(
    'CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS',
    ''
).split(',')
ENTRIES_TO_PROJECT_GT_STATS = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/$dataset_type/entries_to_project_gt_stats_mv`
TO `$reference_genome/$dataset_type/project_gt_stats`
AS SELECT
    project_guid,
    key,
    dictGetOrDefault('seqrdb_affected_status_dict', 'affected', (family_guid, calls.sampleId), 'U') affected,
    $columns
FROM `$reference_genome/$dataset_type/entries`
ARRAY JOIN calls
GROUP BY $groupby_columns
""")

PROJECT_GT_STATS_TO_GT_STATS = Template(Template("""
CREATE MATERIALIZED VIEW `$reference_genome/$dataset_type/project_gt_stats_to_gt_stats_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/$dataset_type/gt_stats`
AS SELECT
    key,
    $columns
FROM `$reference_genome/$dataset_type/project_gt_stats`
WHERE project_guid NOT IN $clickhouse_ac_excluded_project_guids
GROUP BY key
""").safe_substitute(
    clickhouse_ac_excluded_project_guids=CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS
))


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0015_remove_gnomadgenomessnvindel_key_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsgrch37snvindel',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsgrch37snvindel',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssnvindel',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssnvindel',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/gt_stats` ADD COLUMN `ac_het_affected` UInt32 DEFAULT 0 AFTER `ac_het_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsmito',
                    name='ac_het_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/gt_stats` ADD COLUMN `ac_hom_affected` UInt32 DEFAULT 0 AFTER `ac_hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsmito',
                    name='ac_hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssv',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssv',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatsgrch37snvindel',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatssnvindel',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatsmito',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `key`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatssv',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            SEQRDB_AFFECTED_STATUS_DICT,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh37/SNV_INDEL/gt_stats_dict`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh37/SNV_INDEL/entries_to_project_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh37/SNV_INDEL/project_gt_stats_to_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            ENTRIES_TO_PROJECT_GT_STATS.substitute(
                reference_genome='GRCh37',
                dataset_type='SNV_INDEL',
                columns=",\n    ".join([
                    'sample_type',
                    "sumIf(sign, calls.gt = 'REF') ref_samples",
                    "sumIf(sign, calls.gt = 'HET') het_samples",
                    "sumIf(sign, calls.gt = 'HOM') hom_samples",
                ]),
                groupby_columns='project_guid, key, sample_type, affected',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PROJECT_GT_STATS_TO_GT_STATS.substitute(
                reference_genome='GRCh37',
                dataset_type='SNV_INDEL',
                columns=",\n    ".join([
                    "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WES') ac_wes",
                    "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WGS') ac_wgs",
                    "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A') ac_affected",
                    "sumIf(hom_samples, sample_type = 'WES') hom_wes",
                    "sumIf(hom_samples, sample_type = 'WGS') hom_wgs",
                    "sumIf(hom_samples, affected = 'A') hom_affected",
                ])
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            GT_STATS_DICT.substitute(
                reference_genome='GRCh37',
                dataset_type='SNV_INDEL',
                columns= ",\n    ".join([
                    'ac_wes UInt32',
                    'ac_wgs UInt32',
                    'ac_affected UInt32',
                    'hom_wes UInt32',
                    'hom_wgs UInt32',
                    'hom_affected UInt32',
                ]),
                size=int(2e8),
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh38/SNV_INDEL/gt_stats_dict`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/SNV_INDEL/entries_to_project_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/SNV_INDEL/project_gt_stats_to_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            ENTRIES_TO_PROJECT_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='SNV_INDEL',
                columns=",\n    ".join([
                    'sample_type',
                    "sumIf(sign, calls.gt = 'REF') ref_samples",
                    "sumIf(sign, calls.gt = 'HET') het_samples",
                    "sumIf(sign, calls.gt = 'HOM') hom_samples",
                ]),
                groupby_columns='project_guid, key, sample_type, affected',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PROJECT_GT_STATS_TO_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='SNV_INDEL',
                columns=",\n    ".join([
                    "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WES') ac_wes",
                    "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WGS') ac_wgs",
                    "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A') ac_affected",
                    "sumIf(hom_samples, sample_type = 'WES') hom_wes",
                    "sumIf(hom_samples, sample_type = 'WGS') hom_wgs",
                    "sumIf(hom_samples, affected = 'A') hom_affected",
                ])
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            GT_STATS_DICT.substitute(
                reference_genome='GRCh38',
                dataset_type='SNV_INDEL',
                columns= ",\n    ".join([
                    'ac_wes UInt32',
                    'ac_wgs UInt32',
                    'ac_affected UInt32',
                    'hom_wes  UInt32',
                    'hom_wgs  UInt32',
                    'hom_affected UInt32',
                ]),
                size=int(1e9),
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh38/MITO/gt_stats_dict`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/MITO/entries_to_project_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/MITO/project_gt_stats_to_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            ENTRIES_TO_PROJECT_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='MITO',
                columns=",\n    ".join([
                    'sample_type',
                    "sumIf(sign, calls.hl == '0') ref_samples",
                    "sumIf(sign, calls.hl > '0' AND calls.hl < '0.95') het_samples",
                    "sumIf(sign, calls.hl >= '0.95') hom_samples",
                ]),
                groupby_columns='project_guid, key, sample_type, affected',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PROJECT_GT_STATS_TO_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='MITO',
                columns=",\n    ".join([
                    "sumIf(het_samples, sample_type = 'WES') ac_het_wes",
                    "sumIf(het_samples, sample_type = 'WGS') ac_het_wgs",
                    "sumIf(het_samples, affected = 'A') ac_het_affected",
                    "sumIf(hom_samples, sample_type = 'WES') ac_hom_wes",
                    "sumIf(hom_samples, sample_type = 'WGS') ac_hom_wgs",
                    "sumIf(hom_samples, affected = 'A') ac_hom_affected",
                ])
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            GT_STATS_DICT.substitute(
                reference_genome='GRCh38',
                dataset_type='MITO',
                columns= ",\n    ".join([
                    'ac_het_wes UInt32',
                    'ac_het_wgs UInt32',
                    'ac_het_affected UInt32',
                    'ac_hom_wes UInt32',
                    'ac_hom_wgs UInt32',
                    'ac_hom_affected UInt32',
                ]),
                size=int(1e6),
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP DICTIONARY `GRCh38/SV/gt_stats_dict`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/SV/entries_to_project_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'DROP TABLE `GRCh38/SV/project_gt_stats_to_gt_stats_mv`',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            ENTRIES_TO_PROJECT_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='SV',
                columns=",\n    ".join([
                    "sumIf(sign, calls.gt = 'REF') ref_samples",
                    "sumIf(sign, calls.gt = 'HET') het_samples",
                    "sumIf(sign, calls.gt = 'HOM') hom_samples",
                ]),
                groupby_columns='project_guid, key, affected',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PROJECT_GT_STATS_TO_GT_STATS.substitute(
                reference_genome='GRCh38',
                dataset_type='SV',
                columns=",\n    ".join([
                    'sum((het_samples * 1) + (hom_samples * 2)) ac_wgs',
                    "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A') ac_affected",
                    'sum(hom_samples) hom_wgs',
                    "sumIf(hom_samples, affected = 'A') hom_affected",
                ])
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            GT_STATS_DICT.substitute(
                reference_genome='GRCh38',
                dataset_type='SV',
                columns= ",\n    ".join([
                    'ac_wgs UInt32',
                    'ac_affected UInt32',
                    'hom_wgs UInt32',
                    'hom_affected UInt32',
                ]),
                size=int(5e6),
            ),
            hints={'clickhouse': True},
        ),

    ]
