# Generated by Django 4.2.21 on 2025-10-01 20:29
# Modified by the seqr team.

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations
import django.db.models.manager
import os

CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS  = os.environ.get(
    'CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS',
    ''
).split(',')


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0015_remove_gnomadgenomessnvindel_key_and_more'),
        ('seqr', '0001_squashed_0067_remove_project_custom_reference_populations'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsgrch37snvindel',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsgrch37snvindel',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssnvindel',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssnvindel',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/gt_stats` ADD COLUMN `ac_het_affected` UInt32 DEFAULT 0 AFTER `ac_het_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsmito',
                    name='ac_het_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/gt_stats` ADD COLUMN `ac_hom_affected` UInt32 DEFAULT 0 AFTER `ac_hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatsmito',
                    name='ac_hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/gt_stats` ADD COLUMN `ac_affected` UInt32 DEFAULT 0 AFTER `ac_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssv',
                    name='ac_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/gt_stats` ADD COLUMN `hom_affected` UInt32 DEFAULT 0 AFTER `hom_wgs`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='gtstatssv',
                    name='hom_affected',
                    field=clickhouse_backend.models.UInt32Field(),
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatsgrch37snvindel',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatssnvindel',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/MITO/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `sample_type`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatsmito',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SV/project_gt_stats` ADD COLUMN `affected` Enum8('A'=1, 'N'=2, 'U'=3) DEFAULT 'U' AFTER `key`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='projectgtstatssv',
                    name='affected',
                    field=clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')]),
                ),
            ]
        ),
        migrations.CreateModel(
            name='AffectedDict',
            fields=[
                ('family_guid', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('sampleId', clickhouse_backend.models.StringField()),
                ('affected', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'seqrdb_affected_status_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key=('family_guid', 'sampleId')),
                'layout': 'COMPLEX_KEY_HASHED()',
                'postgres_query': 'select f.guid as family_guid, i.individual_id as sample_id, i.affected FROM seqr_individual i INNER JOIN seqr_family f ON i.family_id = f.id',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='GtStatsDictGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='ProjectsToGtStatsGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='EntriesToProjectGtStatsGRCh37SnvIndel',
        ),
        migrations.CreateModel(
            name='EntriesToProjectGtStatsGRCh37SnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('affected', clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')])),
                ('ref_samples', clickhouse_backend.models.Int64Field()),
                ('het_samples', clickhouse_backend.models.Int64Field()),
                ('hom_samples', clickhouse_backend.models.Int64Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/entries_to_project_gt_stats_mv',
                'to_table': 'ProjectGtStatsGRCh37SnvIndel',
                'source_table': 'EntriesGRCh37SnvIndel',
                'source_sql': 'ARRAY JOIN calls GROUP BY project_guid, key, sample_type, affected',
                'column_selects': {
                    'affected': "dictGetOrDefault('seqrdb_affected_status_dict', 'affected', (family_guid, calls.sampleId), 'U')",
                    'het_samples': "sumIf(sign, calls.gt = 'HET')",
                    'hom_samples': "sumIf(sign, calls.gt = 'HOM')",
                    'ref_samples': "sumIf(sign, calls.gt = 'REF')",
                },
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsToGtStatsGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/project_gt_stats_to_gt_stats_mv',
                'to_table': 'GtStatsGRCh37SnvIndel',
                'source_table': 'ProjectGtStatsGRCh37SnvIndel',
                'source_sql': f'WHERE project_guid NOT IN {CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS} GROUP BY key',
                'column_selects': {'ac_affected': "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A')",
                                   'ac_wes': "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WES')",
                                   'ac_wgs': "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WGS')",
                                   'hom_affected': "sumIf(hom_samples, affected = 'A')",
                                   'hom_wes': "sumIf(hom_samples, sample_type = 'WES')",
                                   'hom_wgs': "sumIf(hom_samples, sample_type = 'WGS')"},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsDictGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/gt_stats_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GtStatsGRCh37SnvIndel',
                'layout': 'FLAT(MAX_ARRAY_SIZE 200000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='GtStatsDictSnvIndel',
        ),
        migrations.DeleteModel(
            name='ProjectsToGtStatsSnvIndel',
        ),
        migrations.DeleteModel(
            name='EntriesToProjectGtStatsSnvIndel',
        ),
        migrations.CreateModel(
            name='EntriesToProjectGtStatsSnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('affected', clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')])),
                ('ref_samples', clickhouse_backend.models.Int64Field()),
                ('het_samples', clickhouse_backend.models.Int64Field()),
                ('hom_samples', clickhouse_backend.models.Int64Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/entries_to_project_gt_stats_mv',
                'to_table': 'ProjectGtStatsSnvIndel',
                'source_table': 'EntriesSnvIndel',
                'source_sql': 'ARRAY JOIN calls GROUP BY project_guid, key, sample_type, affected',
                'column_selects': {
                    'affected': "dictGetOrDefault('seqrdb_affected_status_dict', 'affected', (family_guid, calls.sampleId), 'U')",
                    'het_samples': "sumIf(sign, calls.gt = 'HET')",
                    'hom_samples': "sumIf(sign, calls.gt = 'HOM')",
                    'ref_samples': "sumIf(sign, calls.gt = 'REF')",
                },
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsToGtStatsSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/project_gt_stats_to_gt_stats_mv',
                'to_table': 'GtStatsSnvIndel',
                'source_table': 'ProjectGtStatsSnvIndel',
                'source_sql': f'WHERE project_guid NOT IN {CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS} GROUP BY key',
                'column_selects': {'ac_affected': "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A')",
                                   'ac_wes': "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WES')",
                                   'ac_wgs': "sumIf((het_samples * 1) + (hom_samples * 2), sample_type = 'WGS')",
                                   'hom_affected': "sumIf(hom_samples, affected = 'A')",
                                   'hom_wes': "sumIf(hom_samples, sample_type = 'WES')",
                                   'hom_wgs': "sumIf(hom_samples, sample_type = 'WGS')"},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsDictSnvIndel',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wes', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/gt_stats_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GtStatsSnvIndel',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1000000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='GtStatsDictMito',
        ),
        migrations.DeleteModel(
            name='ProjectsToGtStatsMito',
        ),
        migrations.DeleteModel(
            name='EntriesToProjectGtStatsMito',
        ),
        migrations.CreateModel(
            name='EntriesToProjectGtStatsMito',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('sample_type', clickhouse_backend.models.Enum8Field(choices=[(1, 'WES'), (2, 'WGS')])),
                ('affected', clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')])),
                ('ref_samples', clickhouse_backend.models.Int64Field()),
                ('het_samples', clickhouse_backend.models.Int64Field()),
                ('hom_samples', clickhouse_backend.models.Int64Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/entries_to_project_gt_stats_mv',
                'to_table': 'ProjectGtStatsMito',
                'source_table': 'EntriesMito',
                'source_sql': 'ARRAY JOIN calls GROUP BY project_guid, key, sample_type, affected',
                'column_selects': {
                    'affected': "dictGetOrDefault('seqrdb_affected_status_dict', 'affected', (family_guid, calls.sampleId), 'U')",
                    'het_samples': "sumIf(sign, calls.hl > '0' AND calls.hl < '0.95')",
                    'hom_samples': "sumIf(sign, calls.hl >= '0.95')",
                    'ref_samples': "sumIf(sign, calls.hl == '0')",
                },
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsToGtStatsMito',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac_het_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_het_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_het_affected', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/project_gt_stats_to_gt_stats_mv',
                'to_table': 'GtStatsMito',
                'source_table': 'ProjectGtStatsMito',
                'source_sql': f'WHERE project_guid NOT IN {CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS} GROUP BY key',
                'column_selects': {'ac_het_affected': "sumIf(het_samples, affected = 'A')",
                                   'ac_het_wes': "sumIf(het_samples, sample_type = 'WES')",
                                   'ac_het_wgs': "sumIf(het_samples, sample_type = 'WGS')",
                                   'ac_hom_affected': "sumIf(hom_samples, affected = 'A')",
                                   'ac_hom_wes': "sumIf(hom_samples, sample_type = 'WES')",
                                   'ac_hom_wgs': "sumIf(hom_samples, sample_type = 'WGS')"},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsDictMito',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac_het_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_het_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_het_affected', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wes', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/gt_stats_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GtStatsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='GtStatsDictSv',
        ),
        migrations.DeleteModel(
            name='ProjectsToGtStatsSv',
        ),
        migrations.DeleteModel(
            name='EntriesToProjectGtStatsSv',
        ),
        migrations.CreateModel(
            name='EntriesToProjectGtStatsSv',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(low_cardinality=True)),
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('affected', clickhouse_backend.models.Enum8Field(choices=[(1, 'A'), (2, 'N'), (3, 'U')])),
                ('ref_samples', clickhouse_backend.models.Int64Field()),
                ('het_samples', clickhouse_backend.models.Int64Field()),
                ('hom_samples', clickhouse_backend.models.Int64Field()),
            ],
            options={
                'db_table': 'GRCh38/SV/entries_to_project_gt_stats_mv',
                'to_table': 'ProjectGtStatsSv',
                'source_table': 'EntriesSv',
                'source_sql': 'ARRAY JOIN calls GROUP BY project_guid, key, affected',
                'column_selects': {
                    'affected': "dictGetOrDefault('seqrdb_affected_status_dict', 'affected', (family_guid, calls.sampleId), 'U')",
                    'het_samples': "sumIf(sign, calls.gt = 'HET')",
                    'hom_samples': "sumIf(sign, calls.gt = 'HOM')",
                    'ref_samples': "sumIf(sign, calls.gt = 'REF')",
                },
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsToGtStatsSv',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SV/project_gt_stats_to_gt_stats_mv',
                'to_table': 'GtStatsSv',
                'source_table': 'ProjectGtStatsSv',
                'source_sql': f'WHERE project_guid NOT IN {CLICKHOUSE_AC_EXCLUDED_PROJECT_GUIDS} GROUP BY key',
                'column_selects': {'ac_affected': "sumIf((het_samples * 1) + (hom_samples * 2), affected = 'A')",
                                   'ac_wgs': 'sum((het_samples * 1) + (hom_samples * 2))',
                                   'hom_affected': "sumIf(hom_samples, affected = 'A')", 'hom_wgs': 'sum(hom_samples)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GtStatsDictSv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac_wgs', clickhouse_backend.models.UInt32Field()),
                ('ac_affected', clickhouse_backend.models.UInt32Field()),
                ('hom_wgs', clickhouse_backend.models.UInt32Field()),
                ('hom_affected', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SV/gt_stats_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GtStatsSv',
                'layout': 'FLAT(MAX_ARRAY_SIZE 5000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
