# Generated by Django 4.2.21 on 2025-10-16 19:48

import clickhouse_backend.models
import clickhouse_search.backend.engines
from django.db import migrations, models, connections
import django.db.models.deletion
import django.db.models.manager

def conditionally_recreate_repartitioned_snv_indel_entries(apps, schema_editor):
    with connections['clickhouse_write'].cursor() as cursor:
        cursor.execute(
            '''
            SELECT create_table_query
            FROM system.tables
            WHERE database = currentDatabase() AND name = %(table_name)s;
            ''',
            {'table_name': 'GRCh38/SNV_INDEL/entries'},
        )
        row = cursor.fetchone()
        if not row:
            return
        create_table_query = row[0]
        if 'project_partitions' in create_table_query:
            return
        cursor.execute('SELECT COUNT(*) FROM `GRCh38/SNV_INDEL/entries`;')
        if cursor.fetchone()[0] > 0:
            return
        new_partition_by = "(project_guid, farmHash64(family_guid) % coalesce(joinGet(concat(currentDatabase(), '.project_partitions'), 'n_partitions', project_guid), 1))"
        create_table_query = create_table_query.replace(
            'PARTITION BY project_guid',
            f'PARTITION BY {new_partition_by}',
        )
        #cursor.execute('DROP TABLE `GRCh38/SNV_INDEL/entries`')
        #cursor.execute(create_table_query)


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0016_add_affected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartitionsSnvIndel',
            fields=[
                ('project_guid', models.ForeignKey(db_column='project_guid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.entriessnvindel')),
                ('n_partitions', clickhouse_backend.models.UInt8Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/project_partitions',
                'engine': clickhouse_search.backend.engines.Join('ALL', 'LEFT', 'project_guid', flatten_nested=0, join_use_nulls=1),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(conditionally_recreate_repartitioned_snv_indel_entries, reverse_code=migrations.RunPython.noop),
    ]
