# Generated by Django 4.2.21 on 2025-10-16 19:48
import os
from string import Template

import clickhouse_backend.models
import clickhouse_search.backend.engines
from django.db import migrations, connections
import django.db.models.deletion
import django.db.models.manager


CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

PROJECT_PARTITIONS_DICT = Template("""
CREATE DICTIONARY `GRCh38/SNV_INDEL/project_partitions_dict`
(
    project_guid String,
    n_partitions UInt8
)
PRIMARY KEY project_guid
SOURCE(CLICKHOUSE(USER '$clickhouse_writer_user' PASSWORD '$clickhouse_writer_password' TABLE `GRCh38/SNV_INDEL/project_partitions`))
LIFETIME(MIN 0 MAX 300)  -- refresh every 5 minutes
LAYOUT(HASHED()) -- hashed layout supports string keys
""").substitute(
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

def conditionally_recreate_repartitioned_snv_indel_entries(apps, schema_editor):
    with connections['clickhouse_write'].cursor() as cursor:
        cursor.execute(
            '''
            SELECT create_table_query
            FROM system.tables
            WHERE database = currentDatabase() AND name = %(table_name)s;
            ''',
            {'table_name': 'GRCh38/SNV_INDEL/entries'},
        )
        row = cursor.fetchone()
        if not row:
            return
        create_table_query = row[0]
        if 'farmHash64(family_guid)' in create_table_query:
            return
        cursor.execute('SELECT COUNT(*) FROM `GRCh38/SNV_INDEL/entries`;')
        if cursor.fetchone()[0] > 0:
            return
        create_table_query = create_table_query.replace(
            'PARTITION BY project_guid',
            'PARTITION BY (project_guid, partition_id)',
        )
        cursor.execute('DROP TABLE `GRCh38/SNV_INDEL/entries`')
        cursor.execute(create_table_query)


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0018_queue_rebuild_gt_stats_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartitionsSnvIndel',
            fields=[
                ('project_guid', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('n_partitions', clickhouse_backend.models.UInt8Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/project_partitions',
                'engine': clickhouse_backend.models.MergeTree(
                    primary_key='project_guid',
                    order_by='project_guid',
                ),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            PROJECT_PARTITIONS_DICT,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/entries` ADD COLUMN `n_partitions` UInt8 MATERIALIZED dictGetOrDefault('GRCh38/SNV_INDEL/project_partitions_dict', 'n_partitions', project_guid, 1) AFTER `sign`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='entriessnvindel',
                    name='n_partitions',
                    field=clickhouse_search.backend.fields.MaterializedUInt8Field(expression="dictGetOrDefault('GRCh38/SNV_INDEL/project_partitions_dict', 'n_partitions', project_guid, 1)"),
                )
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/entries` ADD COLUMN `partition_id` UInt8 MATERIALIZED farmHash64(family_guid) % n_partitions AFTER `n_partitions`;",
            hints={'clickhouse': True},
            state_operations=[
                migrations.AddField(
                    model_name='entriessnvindel',
                    name='partition_id',
                    field=clickhouse_search.backend.fields.MaterializedUInt8Field(expression='farmHash64(family_guid) %% n_partitions'),
                ),
            ],
        ),
        migrations.RunPython(conditionally_recreate_repartitioned_snv_indel_entries, reverse_code=migrations.RunPython.noop),
    ]
