# Generated by Django 4.2.21 on 2025-10-20 21:46

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.manager


def refresh_materialized_views(apps, schema_editor):
    for view_cls_name in [
        'ClinvarMvGRCh37SnvIndel', 'ClinvarSearchMvGRCh37SnvIndel',
        'ClinvarMvSnvIndel', 'ClinvarSearchMvSnvIndel',
        'ClinvarMvMito', 'ClinvarSearchMvMito',
    ]:
        view_model = apps.get_model('clickhouse_search', view_cls_name)
        view_model.refresh()


class Migration(migrations.Migration):
    dependencies = [
        ("clickhouse_search", "0019_projectpartitions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinvarSeqrVariantsGRCh37SnvIndel",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsgrch37snvindel",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh37/SNV_INDEL/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClinvarSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClinvarSeqrVariantsSnvIndel",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationssnvindel",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/SNV_INDEL/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name="clinvargrch37snvindel",
            table="GRCh37/SNV_INDEL/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarmito",
            table="GRCh38/MITO/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarsnvindel",
            table="GRCh38/SNV_INDEL/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantsgrch37snvindel",
            table="GRCh37/SNV_INDEL/reference_data/clinvar/all_variants",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantsmito",
            table="GRCh38/MITO/reference_data/clinvar/all_variants",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantssnvindel",
            table="GRCh38/SNV_INDEL/reference_data/clinvar/all_variants",
        ),
        migrations.DeleteModel(
            name='ClinvarMvGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='ClinvarMvSnvIndel',
        ),
        migrations.DeleteModel(
            name='ClinvarMvMito',
        ),
        migrations.CreateModel(
            name='ClinvarMvGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/clinvar/all_variants_to_seqr_variants_mv',
                'to_table': 'ClinvarSeqrVariantsGRCh37SnvIndel',
                'source_table': 'ClinvarGRCh37AllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarMvSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/clinvar/all_variants_to_seqr_variants_mv',
                'to_table': 'ClinvarSeqrVariantsSnvIndel',
                'source_table': 'ClinvarAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarMvMito',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/clinvar/all_variants_to_seqr_variants_mv',
                'to_table': 'ClinvarSeqrVariantsMito',
                'source_table': 'ClinvarAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarSearchMvGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/clinvar/seqr_variants_to_search_mv',
                'to_table': 'ClinvarGRCh37SnvIndel',
                'source_table': 'ClinvarGRCh37SeqrVariantsSnvIndel',
                'source_sql': '',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarSearchMvSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/clinvar/seqr_variants_to_search_mv',
                'to_table': 'ClinvarSnvIndel',
                'source_table': 'ClinvarSeqrVariantsSnvIndel',
                'source_sql': '',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarSearchMvMito',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('allele_id', clickhouse_backend.models.UInt32Field(blank=True, db_column='alleleId', null=True)),
                ('conflicting_pathogenicities', clickhouse_search.backend.fields.NestedField(base_fields=[(
                                                                                                          'pathogenicity',
                                                                                                          clickhouse_backend.models.Enum8Field(
                                                                                                              choices=[(
                                                                                                                       0,
                                                                                                                       'Pathogenic'),
                                                                                                                       (
                                                                                                                       1,
                                                                                                                       'Pathogenic/Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       2,
                                                                                                                       'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                                                                                                                       (
                                                                                                                       3,
                                                                                                                       'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       4,
                                                                                                                       'Pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       5,
                                                                                                                       'Likely_pathogenic'),
                                                                                                                       (
                                                                                                                       6,
                                                                                                                       'Likely_pathogenic/Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       7,
                                                                                                                       'Established_risk_allele'),
                                                                                                                       (
                                                                                                                       8,
                                                                                                                       'Likely_risk_allele'),
                                                                                                                       (
                                                                                                                       9,
                                                                                                                       'Conflicting_classifications_of_pathogenicity'),
                                                                                                                       (
                                                                                                                       10,
                                                                                                                       'Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       11,
                                                                                                                       'Uncertain_significance/Uncertain_risk_allele'),
                                                                                                                       (
                                                                                                                       12,
                                                                                                                       'Uncertain_significance'),
                                                                                                                       (
                                                                                                                       13,
                                                                                                                       'No_pathogenic_assertion'),
                                                                                                                       (
                                                                                                                       14,
                                                                                                                       'Likely_benign'),
                                                                                                                       (
                                                                                                                       15,
                                                                                                                       'Benign/Likely_benign'),
                                                                                                                       (
                                                                                                                       16,
                                                                                                                       'Benign')])),
                                                                                                          ('count',
                                                                                                           clickhouse_backend.models.UInt16Field())],
                                                                                             db_column='conflictingPathogenicities')),
                ('gold_stars', clickhouse_backend.models.UInt8Field(blank=True, db_column='goldStars', null=True)),
                (
                'submitters', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                (
                'conditions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('assertions', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Affects'), (1, 'association'), (2, 'association_not_found'),
                             (3, 'confers_sensitivity'), (4, 'drug_response'), (5, 'low_penetrance'),
                             (6, 'not_provided'), (7, 'other'), (8, 'protective'), (9, 'risk_factor'),
                             (10, 'no_classification_for_the_single_variant'),
                             (11, 'no_classifications_from_unflagged_records')]))),
                ('pathogenicity', clickhouse_backend.models.Enum8Field(
                    choices=[(0, 'Pathogenic'), (1, 'Pathogenic/Likely_pathogenic'),
                             (2, 'Pathogenic/Likely_pathogenic/Established_risk_allele'),
                             (3, 'Pathogenic/Likely_pathogenic/Likely_risk_allele'),
                             (4, 'Pathogenic/Likely_risk_allele'), (5, 'Likely_pathogenic'),
                             (6, 'Likely_pathogenic/Likely_risk_allele'), (7, 'Established_risk_allele'),
                             (8, 'Likely_risk_allele'), (9, 'Conflicting_classifications_of_pathogenicity'),
                             (10, 'Uncertain_risk_allele'), (11, 'Uncertain_significance/Uncertain_risk_allele'),
                             (12, 'Uncertain_significance'), (13, 'No_pathogenic_assertion'), (14, 'Likely_benign'),
                             (15, 'Benign/Likely_benign'), (16, 'Benign')])),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/clinvar/seqr_variants_to_search_mv',
                'to_table': 'ClinvarMito',
                'source_table': 'ClinvarSeqrVariantsMito',
                'source_sql': '',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(refresh_materialized_views),
    ]
