# Generated by Django 4.2.21 on 2025-10-20 21:46

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models, connections
import django.db.models.manager
from string import Template

CLINVAR_ALL_TO_SEQR_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/$dataset_type/reference_data/clinvar/all_variants_to_seqr_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/$dataset_type/reference_data/clinvar/seqr_variants`
AS 
SELECT
    DISTINCT ON (key)
    key,
    COLUMNS('.*') EXCEPT(version, variantId, key)
FROM `$reference_genome/$dataset_type/reference_data/clinvar/all_variants` src
INNER JOIN `$reference_genome/$dataset_type/key_lookup` dst
ON assumeNotNull(src.variantId) = dst.variantId
""")

CLINVAR_SEQR_TO_SEARCH_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/$dataset_type/reference_data/clinvar/seqr_variants_to_search_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/$dataset_type/reference_data/clinvar`
AS 
SELECT 
DISTINCT ON (key) *
FROM `$reference_genome/$dataset_type/reference_data/clinvar/seqr_variants`
""")

def build_materialized_view(reference_genome: str, dataset_type: str, materialized_view: str):
    def inner(apps, schema_editor):
        with connections['clickhouse_write'].cursor() as cursor:
            cursor.execute(
                f'SYSTEM REFRESH VIEW `{reference_genome}/{dataset_type}/reference_data/clinvar/{materialized_view}`;'
            )
            cursor.execute(
                f'SYSTEM WAIT VIEW `{reference_genome}/{dataset_type}/reference_data/clinvar/{materialized_view}`;'
            )
    return inner


class Migration(migrations.Migration):
    dependencies = [
        ("clickhouse_search", "0019_projectpartitions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinvarSeqrVariantsGRCh37SnvIndel",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsgrch37snvindel",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh37/SNV_INDEL/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClinvarSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClinvarSeqrVariantsSnvIndel",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationssnvindel",
                    ),
                ),
                (
                    "allele_id",
                    clickhouse_backend.models.UInt32Field(
                        blank=True, db_column="alleleId", null=True
                    ),
                ),
                (
                    "conflicting_pathogenicities",
                    clickhouse_search.backend.fields.NestedField(
                        base_fields=[
                            (
                                "pathogenicity",
                                clickhouse_backend.models.Enum8Field(
                                    choices=[
                                        (0, "Pathogenic"),
                                        (1, "Pathogenic/Likely_pathogenic"),
                                        (
                                            2,
                                            "Pathogenic/Likely_pathogenic/Established_risk_allele",
                                        ),
                                        (
                                            3,
                                            "Pathogenic/Likely_pathogenic/Likely_risk_allele",
                                        ),
                                        (4, "Pathogenic/Likely_risk_allele"),
                                        (5, "Likely_pathogenic"),
                                        (6, "Likely_pathogenic/Likely_risk_allele"),
                                        (7, "Established_risk_allele"),
                                        (8, "Likely_risk_allele"),
                                        (
                                            9,
                                            "Conflicting_classifications_of_pathogenicity",
                                        ),
                                        (10, "Uncertain_risk_allele"),
                                        (
                                            11,
                                            "Uncertain_significance/Uncertain_risk_allele",
                                        ),
                                        (12, "Uncertain_significance"),
                                        (13, "No_pathogenic_assertion"),
                                        (14, "Likely_benign"),
                                        (15, "Benign/Likely_benign"),
                                        (16, "Benign"),
                                    ]
                                ),
                            ),
                            ("count", clickhouse_backend.models.UInt16Field()),
                        ],
                        db_column="conflictingPathogenicities",
                    ),
                ),
                (
                    "gold_stars",
                    clickhouse_backend.models.UInt8Field(
                        blank=True, db_column="goldStars", null=True
                    ),
                ),
                (
                    "submitters",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "conditions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.StringField()
                    ),
                ),
                (
                    "assertions",
                    clickhouse_backend.models.ArrayField(
                        base_field=clickhouse_backend.models.Enum8Field(
                            choices=[
                                (0, "Affects"),
                                (1, "association"),
                                (2, "association_not_found"),
                                (3, "confers_sensitivity"),
                                (4, "drug_response"),
                                (5, "low_penetrance"),
                                (6, "not_provided"),
                                (7, "other"),
                                (8, "protective"),
                                (9, "risk_factor"),
                                (10, "no_classification_for_the_single_variant"),
                                (11, "no_classifications_from_unflagged_records"),
                            ]
                        )
                    ),
                ),
                (
                    "pathogenicity",
                    clickhouse_backend.models.Enum8Field(
                        choices=[
                            (0, "Pathogenic"),
                            (1, "Pathogenic/Likely_pathogenic"),
                            (2, "Pathogenic/Likely_pathogenic/Established_risk_allele"),
                            (3, "Pathogenic/Likely_pathogenic/Likely_risk_allele"),
                            (4, "Pathogenic/Likely_risk_allele"),
                            (5, "Likely_pathogenic"),
                            (6, "Likely_pathogenic/Likely_risk_allele"),
                            (7, "Established_risk_allele"),
                            (8, "Likely_risk_allele"),
                            (9, "Conflicting_classifications_of_pathogenicity"),
                            (10, "Uncertain_risk_allele"),
                            (11, "Uncertain_significance/Uncertain_risk_allele"),
                            (12, "Uncertain_significance"),
                            (13, "No_pathogenic_assertion"),
                            (14, "Likely_benign"),
                            (15, "Benign/Likely_benign"),
                            (16, "Benign"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/SNV_INDEL/reference_data/clinvar/seqr_variants",
                "abstract": False,
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key",
                    primary_key="key",
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name="clinvargrch37snvindel",
            table="GRCh37/SNV_INDEL/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarmito",
            table="GRCh38/MITO/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarsnvindel",
            table="GRCh38/SNV_INDEL/reference_data/clinvar",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantsgrch37snvindel",
            table="GRCh37/SNV_INDEL/reference_data/clinvar/all_variants",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantsmito",
            table="GRCh38/MITO/reference_data/clinvar/all_variants",
        ),
        migrations.AlterModelTable(
            name="clinvarallvariantssnvindel",
            table="GRCh38/SNV_INDEL/reference_data/clinvar/all_variants",
        ),
        migrations.RunSQL(
            "DROP TABLE `GRCh37/SNV_INDEL/clinvar_all_variants_to_clinvar_mv`",
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            "DROP TABLE `GRCh38/SNV_INDEL/clinvar_all_variants_to_clinvar_mv`",
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            "DROP TABLE `GRCh38/MITO/clinvar_all_variants_to_clinvar_mv`",
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            CLINVAR_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                materialized_view="all_variants_to_seqr_variants_mv"
            ),
        ),
        migrations.RunSQL(
            CLINVAR_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                materialized_view="all_variants_to_seqr_variants_mv"
            ),
        ),
        migrations.RunSQL(
            CLINVAR_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh38",
                dataset_type="MITO",
                materialized_view="all_variants_to_seqr_variants_mv"
            ),
        ),
        migrations.RunSQL(
            CLINVAR_SEQR_TO_SEARCH_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                materialized_view="seqr_variants_to_search_mv"
            ),
        ),
        migrations.RunSQL(
            CLINVAR_SEQR_TO_SEARCH_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                materialized_view="seqr_variants_to_search_mv"
            ),
        ),
        migrations.RunSQL(
            CLINVAR_SEQR_TO_SEARCH_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_materialized_view(
                reference_genome="GRCh38",
                dataset_type="MITO",
                materialized_view="seqr_variants_to_search_mv"
            ),
        ),
    ]
