# Generated by Django 4.2.21 on 2025-11-19 20:29
# Modified by the seqr team.
import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager

class Migration(migrations.Migration):
    dependencies = [
        ('clickhouse_search', '0021_affected_status_orderby'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneIdDict',
            fields=[
                ('gene_id', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('seqrdb_id', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'seqrdb_gene_ids',
                'engine': clickhouse_backend.models.MergeTree(primary_key='gene_id'),
                'layout': 'HASHED()',
                'postgres_query': 'SELECT gene_id, id FROM reference_data_geneinfo',
                'postgres_db': 'reference_data',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 1;",
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 1;",
            hints={'clickhouse': True},
        ),
    ]
