# Generated by Django 4.2.21 on 2025-11-19 20:29
# Modified by the seqr team.
from django.db import migrations
import os
from string import Template

from settings import DATABASES

CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

SEQRDB_GENE_IDS_DICT = Template("""
CREATE DICTIONARY `seqrdb_gene_ids`
(
    `gene_id` String,
    `seqrdb_id` UInt32
)
PRIMARY KEY gene_id
SOURCE(POSTGRESQL(
    NAME 'seqr_postgres_named_collection'
    DATABASE $database
    QUERY 'SELECT gene_id, id FROM reference_data_geneinfo'
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(HASHED());
""").substitute(
    database=DATABASES['reference_data']['NAME'],
)

class Migration(migrations.Migration):
    dependencies = [
        ('clickhouse_search', '0021_affected_status_orderby'),
    ]

    operations = [
        migrations.RunSQL(
            SEQRDB_GENE_IDS_DICT,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 1;",
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 1;",
            hints={'clickhouse': True},
        ),
    ]
