# Generated by Django 4.2.24 on 2025-12-03 16:16

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0022_db_gene_id'),
        ('seqr', '0001_squashed_0067_remove_project_custom_reference_populations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexDict',
            fields=[
                ('family_guid', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('sampleId', clickhouse_backend.models.StringField()),
                ('sex', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'seqrdb_sex_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key=('family_guid', 'sampleId')),
                'layout': 'COMPLEX_KEY_HASHED()',
                'postgres_query': 'select f.guid as family_guid, i.individual_id as sample_id, i.sex FROM seqr_individual i INNER JOIN seqr_family f ON i.family_id = f.id',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
