# Generated by Django 4.2.24 on 2025-12-03 16:16

from django.db import migrations
from string import Template

from settings import DATABASES

SEQRDB_SEX_STATUS_DICT = Template("""
CREATE DICTIONARY `seqrdb_sex_dict`
(
    `family_guid` String,
    `sampleId` String,
    `sex` String
)
PRIMARY KEY family_guid, sampleId
SOURCE(POSTGRESQL(
    NAME 'seqr_postgres_named_collection' 
    DATABASE $database
    QUERY 'select f.guid as family_guid, i.individual_id as sample_id, i.sex FROM seqr_individual i INNER JOIN seqr_family f ON i.family_id = f.id'
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(COMPLEX_KEY_HASHED());
""").substitute(
    database=DATABASES['default']['NAME'],
)

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0022_db_gene_id'),
    ]

    operations = [
        migrations.RunSQL(
            SEQRDB_SEX_STATUS_DICT,
            hints={'clickhouse': True},
        ),
    ]
