# Generated by Django 4.2.21 on 2025-11-13 21:28

import clickhouse_backend.models
import clickhouse_search.backend.engines
from django.db import migrations, models, connections
import django.db.models.deletion
import django.db.models.manager

from string import Template


GCS_NAMED_COLLECTION = 'pipeline_data_access'
HGMD_URLS = {
    'GRCh37': 'https://storage.googleapis.com/seqr-reference-data-private/GRCh37/HGMD/HGMD_Pro_2023.1_hg19.vcf.gz',
    'GRCh38': 'https://storage.googleapis.com/seqr-reference-data-private/GRCh38/HGMD/HGMD_Pro_2023.1_hg38.vcf.gz',
}

HGMD_VIEW = Template(Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/hgmd/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/hgmd/all_variants`
EMPTY
AS SELECT
    arrayStringConcat([
        replaceOne(replaceOne(CHROM, 'chr', ''), 'MT', 'M'),
        toString(POS),
        REF,
        ALT
    ], '-') AS variantId,
    ID as accession,
    extract(INFO, 'CLASS=([^;]+)') as classification
FROM gcs(
    $gcs_named_collection,
    url='$hgmd_url',
    format='TSV',
    structure='CHROM String, POS UInt32, ID String, REF String, ALT String, QUAL String, FILTER String, INFO String'
)
WHERE ALT != '<DEL>'
SETTINGS input_format_allow_errors_ratio = 0.01, input_format_allow_errors_num = 25
""")).safe_substitute(
    gcs_named_collection=GCS_NAMED_COLLECTION,
)

HGMD_ALL_TO_SEQR_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/hgmd/all_variants_to_seqr_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/hgmd/seqr_variants`
AS 
SELECT
    DISTINCT ON (key)
    key,
    COLUMNS('.*') EXCEPT(version, variantId, key)
FROM `$reference_genome/SNV_INDEL/reference_data/hgmd/all_variants` src
INNER JOIN `$reference_genome/SNV_INDEL/key_lookup` dst
ON assumeNotNull(src.variantId) = dst.variantId
""")

HGMD_SEQR_TO_SEARCH_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/hgmd/seqr_variants_to_search_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/hgmd`
AS 
SELECT 
DISTINCT ON (key) *
FROM `$reference_genome/SNV_INDEL/reference_data/hgmd/seqr_variants`
""")

def build_hgmd_view(reference_genome: str, hgmd_url: str):
    def inner(apps, schema_editor):
        with connections['clickhouse_write'].cursor() as cursor:
            cursor.execute(
                HGMD_VIEW.substitute(
                    reference_genome=reference_genome,
                    hgmd_url=hgmd_url,
                )
            )
    return inner

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0023_gnomad_noncoding_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HgmdAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdGRCh37SnvIndel',
            fields=[
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='hgmd_join', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd',
                'abstract': False,
                'engine': clickhouse_search.backend.engines.Join('ALL', 'LEFT', 'key', flatten_nested=0, join_use_nulls=1),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSnvIndel',
            fields=[
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='hgmd_join', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('accession', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('classification', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')], null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd',
                'abstract': False,
                'engine': clickhouse_search.backend.engines.Join('ALL', 'LEFT', 'key', flatten_nested=0, join_use_nulls=1),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            HGMD_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            HGMD_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            HGMD_SEQR_TO_SEARCH_MV.substitute(
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            HGMD_SEQR_TO_SEARCH_MV.substitute(
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            build_hgmd_view(
                reference_genome="GRCh37",
                hgmd_url=HGMD_URLS["GRCh37"],
            ),
        ),
        migrations.RunPython(
            build_hgmd_view(
                reference_genome="GRCh38",
                hgmd_url=HGMD_URLS["GRCh38"],
            ),
        ),
    ]
