# Generated by Django 4.2.21 on 2025-10-22 14:07
from string import Template

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary
from settings import DATABASES

PEXT_VIEW = Template("""
$mv_header
AS SELECT
    replaceOne(splitByChar(':', assumeNotNull(locus))[1], 'chr', '') AS chrom,
    toUInt32(splitByChar(':', assumeNotNull(locus))[2]) AS pos,
    if(exp_prop_mean IN ('NaN', 'nan', ''), NULL, exp_prop_mean) AS score
FROM url('https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/pext/gnomad.pext.gtex_v10.base_level.tsv.gz')
$condition
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0023_add_sex_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='PextAllVariantsSnvIndel',
            fields=[
                ('chrom', clickhouse_search.backend.fields.Enum8Field(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 'X'), (24, 'Y'), (25, 'M')], primary_key=True, serialize=False)),
                ('pos', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by=('chrom', 'pos'), primary_key=('chrom', 'pos')),
                'unique_together': {('chrom', 'pos')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextAllVariantsMito',
            fields=[
                ('chrom', clickhouse_search.backend.fields.Enum8Field(choices=[(1, 'M')], primary_key=True, serialize=False)),
                ('pos', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by=('chrom', 'pos'), primary_key=('chrom', 'pos')),
                'unique_together': {('chrom', 'pos')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="pext",
                columns="""
                    chrom String,
                    start UInt32,
                    end UInt32,
                    score Nullable(Decimal(9, 5))
                """,
                primary_key="chrom",
                source=f"QUERY 'SELECT chrom, pos as start, pos as end, score FROM {DATABASES['clickhouse_write']['NAME']}.`GRCh38/SNV_INDEL/reference_data/pext/all_variants`'",
                layout="RANGE_HASHED()"
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="pext",
                columns="""
                    chrom String,
                    start UInt32,
                    end UInt32,
                    score Nullable(Decimal(9, 5))
                """,
                primary_key="chrom",
                source=f"QUERY 'SELECT chrom, pos as start, pos as end, score FROM {DATABASES['clickhouse_write']['NAME']}.`GRCh38/MITO/reference_data/pext/all_variants`'",
                layout="RANGE_HASHED()"
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PEXT_VIEW.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="pext"),
                dataset_type='SNV_INDEL',
                condition='',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PEXT_VIEW.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="pext"),
                dataset_type='MITO',
                condition="WHERE startsWith(locus, 'chrM')",
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="pext",
            ),
        ),
    ]
