# Generated by Django 4.2.21 on 2025-10-22 14:07
from string import Template

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary
from settings import DATABASES

PEXT_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    concat(
        replaceOne(splitByChar(':', assumeNotNull(locus))[1], 'chr', ''),
        '-',
        splitByChar(':', assumeNotNull(locus))[2],
        '-',
        JSONExtractArrayRaw(assumeNotNull(alleles))[1],
        '-',
        JSONExtractArrayRaw(assumeNotNull(alleles))[2]
    ) as variantId,
    if(exp_prop_mean IN ('NaN', 'nan', ''), NULL, exp_prop_mean) AS score
FROM url('https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/pext/gnomad.pext.gtex_v10.annotation_level.tsv.gz')
$condition
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0023_add_sex_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='PextAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextAllVariantsMito',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSeqrVariantsMito',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            PEXT_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="pext"),
                dataset_type='SNV_INDEL',
                condition='WHERE score IS NOT NULL',
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            PEXT_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="pext"),
                dataset_type='MITO',
                condition="WHERE score IS NOT NULL AND startsWith(locus, 'chrM')",
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="pext",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="pext",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="pext",
                columns="""
                    key UInt32,
                    score Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/pext/seqr_variants`",
                layout="RANGE_HASHED()"
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="pext",
                columns="""
                    key UInt32,
                    score Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/pext/seqr_variants`",
                layout="RANGE_HASHED()"
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="pext",
            ),
        ),
    ]
