# Generated by Django 4.2.21 on 2025-10-22 14:07
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0023_add_sex_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='PextAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextAllVariantsMito',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSeqrVariantsMito',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSnvIndelAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/all_variants_mv',
                'to_table': 'PextAllVariantsSnvIndel',
                'source_sql': 'WHERE score IS NOT NULL',
                'source_url': 'https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/pext/gnomad.pext.gtex_v10.annotation_level.tsv.gz',
                'column_selects': {'score': "if(exp_prop_mean IN ('NaN', 'nan', ''), NULL, exp_prop_mean)", 'variantId': "concat(replaceOne(splitByChar(':', assumeNotNull(locus))[1], 'chr', ''), '-', splitByChar(':', assumeNotNull(locus))[2], '-', JSONExtract(assumeNotNull(alleles), 'Array(String)')[1], '-', JSONExtract(assumeNotNull(alleles), 'Array(String)')[2])"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextMitoAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/all_variants_mv',
                'to_table': 'PextAllVariantsMito',
                'source_sql': "WHERE score IS NOT NULL AND startsWith(locus, 'chrM')",
                'source_url': 'https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/pext/gnomad.pext.gtex_v10.annotation_level.tsv.gz',
                'column_selects': {'score': "if(exp_prop_mean IN ('NaN', 'nan', ''), NULL, exp_prop_mean)", 'variantId': "concat(replaceOne(splitByChar(':', assumeNotNull(locus))[1], 'chr', ''), '-', splitByChar(':', assumeNotNull(locus))[2], '-', JSONExtract(assumeNotNull(alleles), 'Array(String)')[1], '-', JSONExtract(assumeNotNull(alleles), 'Array(String)')[2])"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSnvIndelMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext/all_variants_to_seqr_variants_mv',
                'to_table': 'PextSeqrVariantsSnvIndel',
                'source_table': 'PextAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextMitoMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext/all_variants_to_seqr_variants_mv',
                'to_table': 'PextSeqrVariantsMito',
                'source_table': 'PextAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextSnvIndelDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pext', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/pext',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'PextSeqrVariantsSnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PextMitoDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pext', serialize=False, to='clickhouse_search.entriesmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/pext',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'PextSeqrVariantsMito',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="pext",
            ),
        ),
    ]
