# Generated by Django 4.2.21 on 2025-10-22 14:07
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations
import django.db.models.manager

from clickhouse_search.migration_templates import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0024_pext_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenAllVariantsSnvIndel',
            fields=[
                ('chrom', clickhouse_search.backend.fields.Enum8Field(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 'X'), (24, 'Y'), (25, 'M')], primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('region_type', clickhouse_backend.models.StringField(db_column='regionType')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/screen/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by=('chrom', 'start', 'end'), primary_key=('chrom', 'start', 'end')),
                'unique_together': {('chrom', 'start', 'end')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScreenAllMv',
            fields=[
                ('chrom', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('start', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('region_type', clickhouse_backend.models.StringField(db_column='regionType')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint/all_variants_mv',
                'to_table': 'ScreenAllVariantsSnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/screen/GRCh38-cCREs.bed',
                'column_selects': {'chrom': "replaceOne(c1, 'chr', '')", 'end': 'toUInt32(assumeNotNull(c3))', 'regionType': "splitByChar(',', assumeNotNull(c6))[1]", 'start': 'toUInt32(assumeNotNull(c2))'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDict',
            fields=[
                ('chrom', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('region_type', clickhouse_backend.models.StringField(db_column='regionType')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/screen',
                'engine': clickhouse_backend.models.MergeTree(primary_key='chrom'),
                'source_table': 'ScreenAllVariantsSnvIndel',
                'layout': 'RANGE_HASHED()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="screen",
            ),
        ),
    ]
