# Generated by Django 4.2.21 on 2025-10-22 14:07
from string import Template

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary

# Original file sourced from `https://downloads.wenglab.org/V3/GRCh38-cCREs.bed`
SCREEN_VIEW = Template("""
$mv_header
AS SELECT
    replaceOne(c1, 'chr', '') as chrom,
    toUInt32(assumeNotNull(c2)) as start,
    toUInt32(assumeNotNull(c3)) as end,
    splitByChar(',', assumeNotNull(c6))[1] as regionType
FROM url('https://seqr-reference-data.broadinstitute.org/clickhouse/GRCh38/screen/GRCh38-cCREs.bed')
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0024_pext_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenAllVariantsSnvIndel',
            fields=[
                ('chrom', clickhouse_search.backend.fields.Enum8Field(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 'X'), (24, 'Y'), (25, 'M')], primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('region_type', clickhouse_backend.models.StringField(db_column='regionType')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/screen/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by=('chrom', 'start', 'end'), primary_key=('chrom', 'start', 'end')),
                'unique_together': {('chrom', 'start', 'end')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="screen",
                columns="""
                    chrom String,
                    start UInt32,
                    end UInt32,
                    regionType String
                """,
                primary_key="chrom",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/screen/all_variants`",
                layout="RANGE_HASHED()"
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            SCREEN_VIEW.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="screen")
            ),
            hints={'clickhouse': True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="screen",
            ),
        ),
    ]
