# Generated by Django 4.2.21 on 2025-10-22 14:07
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0025_screen_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadNonCodingConstraintAllVariantsSnvIndel',
            fields=[
                ('chrom', clickhouse_search.backend.fields.Enum8Field(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 'X'), (24, 'Y'), (25, 'M')], primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by=('chrom', 'start', 'end'), primary_key=('chrom', 'start', 'end')),
                'unique_together': {('chrom', 'start', 'end')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadNonCodingConstraintAllMv',
            fields=[
                ('chrom', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('start', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint/all_variants_mv',
                'to_table': 'GnomadNonCodingConstraintAllVariantsSnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/gcp-public-data--gnomad/release/3.1/secondary_analyses/genomic_constraint/constraint_z_genome_1kb.qc.download.txt.gz',
                'column_selects': {'chrom': "replaceOne(chrom, 'chr', '')", 'end': 'toUInt32(assumeNotNull(end))', 'score': 'z', 'start': 'toUInt32(assumeNotNull(start))'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadNonCodingConstraintDict',
            fields=[
                ('chrom', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint',
                'engine': clickhouse_backend.models.MergeTree(primary_key='chrom'),
                'source_table': 'GnomadNonCodingConstraintAllVariantsSnvIndel',
                'layout': 'RANGE_HASHED()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_non_coding_constraint",
            ),
        ),
    ]
