# Generated by Django 4.2.21 on 2025-12-03 00:28

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

TOPMED_SEARCH = Template("""
CREATE DICTIONARY `$reference_genome/SNV_INDEL/reference_data/topmed`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 5)
    `an` UInt32,
    `het` UInt32,
    `hom` UInt32
)
PRIMARY KEY chrom
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `$reference_genome/SNV_INDEL/reference_data/topmed/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(RANGE_HASHED())
RANGE(MIN start MAX end)
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

TOPMED_ALL_VARIANTS_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/topmed/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/topmed/all_variants`
EMPTY
AS SELECT
    arrayStringConcat([
        replaceOne(replaceOne(CHROM, 'chr', ''), 'MT', 'M'),
        toString(POS),
        REF,
        ALT
    ], '-') AS variantId,
    ID as accession,
    extract(INFO, 'CLASS=([^;]+)') as classification
FROM $table_structure
WHERE ALT != '<DEL>'
SETTINGS input_format_allow_errors_ratio = 0.01, input_format_allow_errors_num = 25
""")

TOPMED_ALL_TO_SEQR_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/topmed/all_variants_to_seqr_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/topmed/seqr_variants`
AS 
SELECT
    DISTINCT ON (key)
    key,
    COLUMNS('.*') EXCEPT(version, variantId, key)
FROM `$reference_genome/SNV_INDEL/reference_data/topmed/all_variants` src
INNER JOIN `$reference_genome/SNV_INDEL/key_lookup` dst
ON assumeNotNull(src.variantId) = dst.variantId
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0026_hgmd_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopmedAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
