# Generated by Django 4.2.21 on 2025-11-13 21:28
import os

import clickhouse_backend.models
import clickhouse_search.backend.engines
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset

HGMD_GRCH37_URL = os.environ.get('HGMD_GRCH37_URL', None)
HGMD_GRCH38_URL = os.environ.get('HGMD_GRCH38_URL', None)

HGMD_INFO_STRUCTURE = 'CHROM String, POS UInt32, ID String, REF String, ALT String, QUAL String, FILTER String, INFO String'

def _hgmd_source_url_template(url):
    if not url:
        return "null('{source_url}')"
    return f"gcs(pipeline_data_access, url='{{source_url}}', format='TSV', structure='{HGMD_INFO_STRUCTURE}')"


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0026_gnomad_noncoding_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HgmdAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSeqrVariantsSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdGRCh37SnvIndel',
            fields=[
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='hgmd_join', serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd',
                'abstract': False,
                'engine': clickhouse_search.backend.engines.Join('ALL', 'LEFT', 'key', flatten_nested=0, join_use_nulls=1),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSnvIndel',
            fields=[
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='hgmd_join', serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd',
                'abstract': False,
                'engine': clickhouse_search.backend.engines.Join('ALL', 'LEFT', 'key', flatten_nested=0, join_use_nulls=1),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/all_variants_to_seqr_variants_mv',
                'to_table': 'HgmdSeqrVariantsGRCh37SnvIndel',
                'source_table': 'HgmdAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/all_variants_to_seqr_variants_mv',
                'to_table': 'HgmdSeqrVariantsSnvIndel',
                'source_table': 'HgmdAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdGRCh37SearchMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/seqr_variants_to_search_mv',
                'to_table': 'HgmdGRCh37SnvIndel',
                'source_table': 'HgmdSeqrVariantsGRCh37SnvIndel',
                'source_sql': '',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdSearchMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.Enum8Field(choices=[(0, 'DM'), (1, 'DM?'), (2, 'DP'), (3, 'DFP'), (4, 'FP'), (5, 'R')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/seqr_variants_to_search_mv',
                'to_table': 'HgmdSnvIndel',
                'source_table': 'HgmdSeqrVariantsSnvIndel',
                'source_sql': '',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdGRCh37AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/hgmd/all_variants_mv',
                'to_table': 'HgmdAllVariantsGRCh37SnvIndel',
                'source_sql': "WHERE ALT != '<DEL>' SETTINGS input_format_allow_errors_ratio = 0.01, input_format_allow_errors_num = 25",
                'source_url': HGMD_GRCH37_URL or HGMD_INFO_STRUCTURE,
                'source_url_template': _hgmd_source_url_template(HGMD_GRCH37_URL),
                'column_selects': {'accession': 'ID', 'classification': "extract(INFO, 'CLASS=([^;]+)')", 'variantId': "arrayStringConcat([replaceOne(replaceOne(CHROM, 'chr', ''), 'MT', 'M'), toString(POS), REF, ALT], '-')"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HgmdAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('accession', clickhouse_backend.models.StringField()),
                ('classification', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/hgmd/all_variants_mv',
                'to_table': 'HgmdAllVariantsSnvIndel',
                'source_sql': "WHERE ALT != '<DEL>' SETTINGS input_format_allow_errors_ratio = 0.01, input_format_allow_errors_num = 25",
                'source_url': HGMD_GRCH38_URL or HGMD_INFO_STRUCTURE,
                'source_url_template': _hgmd_source_url_template(HGMD_GRCH38_URL),
                'column_selects': {'accession': 'ID', 'classification': "extract(INFO, 'CLASS=([^;]+)')", 'variantId': "arrayStringConcat([replaceOne(replaceOne(CHROM, 'chr', ''), 'MT', 'M'), toString(POS), REF, ALT], '-')"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="hgmd",
            ),
        ),
    ]

