# Generated by Django 4.2.21 on 2025-12-03 00:28
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0027_hgmd_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopmedAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedGRCh37AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('het', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('hom', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/all_variants_mv',
                'to_table': 'TopmedAllVariantsGRCh37SnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh37/topmed/1.1.parquet/*.parquet',
                'column_selects': {'ac': 'AC', 'af': 'AF', 'an': 'AN', 'filter_af': 'AF_POPMAX_OR_GLOBAL', 'hemi': 'Hemi', 'het': 'Het', 'hom': 'Hom', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('het', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('hom', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/all_variants_mv',
                'to_table': 'TopmedAllVariantsSnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/topmed/1.1.parquet/*.parquet',
                'column_selects': {'ac': 'AC', 'af': 'AF', 'an': 'AN', 'filter_af': 'AF_POPMAX_OR_GLOBAL', 'hemi': 'Hemi', 'het': 'Het', 'hom': 'Hom', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/all_variants_to_seqr_variants_mv',
                'to_table': 'TopmedSeqrVariantsGRCh37SnvIndel',
                'source_table': 'TopmedAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/all_variants_to_seqr_variants_mv',
                'to_table': 'TopmedSeqrVariantsSnvIndel',
                'source_table': 'TopmedAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedGRCh37Dict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topmed', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'TopmedSeqrVariantsGRCh37SnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topmed', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'TopmedSeqrVariantsSnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="topmed",
            ),
        ),
    ]
