# Generated by Django 4.2.21 on 2025-12-03 00:28
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary

TOPMED_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variant_id as variantId,
    AC as ac,
    AF as af,
    AN as an,
    Het as het,
    Hom as hom
FROM gcs('https://seqr-reference-data.broadinstitute.org/v3.1/$reference_genome/topmed/1.1.parquet/*.parquet')
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0027_hgmd_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopmedAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TopmedSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('het', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/topmed/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            TOPMED_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh37", dataset_type="SNV_INDEL", reference_dataset="topmed"),
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            TOPMED_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="topmed"),
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="topmed",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="topmed",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="topmed",
                columns="""
                    `key` UInt32,
                    `ac` UInt32,
                    `af` Decimal(9, 8),
                    `an` UInt32,
                    `het` UInt32,
                    `hom` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh37/SNV_INDEL/reference_data/topmed/seqr_variants`",
                layout="HASHED_ARRAY()",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="topmed",
                columns="""
                    `key` UInt32,
                    `ac` UInt32,
                    `af` Decimal(9, 8),
                    `an` UInt32,
                    `het` UInt32,
                    `hom` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/topmed/seqr_variants`",
                layout="HASHED_ARRAY()",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="topmed",
            ),
        ),
    ]
