# Generated by Django 4.2.21 on 2025-12-04 16:24

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

GNOMAD_EXOMES_SEARCH = Template(Template("""
CREATE DICTIONARY `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 8),
    `an` UInt32,
    `filter_af` Decimal(9, 8),
    `hemi` UInt32,
    `hom` UInt32
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(HASHED_ARRAY())
""").safe_substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
))

GNOMAD_EXOMES_ALL_VARIANTS_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/all_variants`
EMPTY
AS SELECT
    variant_id as variantId,
    AC as ac,
    AF as af,
    AN as an,
    AF_POPMAX_OR_GLOBAL as filter_af,
    Hemi as hemi,
    Hom as hom
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/$reference_genome/gnomad_exomes/1.0.parquet/*.parquet')
""")

GNOMAD_EXOMES_ALL_TO_SEQR_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/all_variants_to_seqr_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants`
AS 
SELECT
    DISTINCT ON (key)
    key,
    COLUMNS('.*') EXCEPT(version, variantId, key)
FROM `$reference_genome/SNV_INDEL/reference_data/gnomad_exomes/all_variants` src
INNER JOIN `$reference_genome/SNV_INDEL/key_lookup` dst
ON assumeNotNull(src.variantId) = dst.variantId
""")


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0027_topmed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadExomesAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_ALL_VARIANTS_MV.substitute(
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_ALL_VARIANTS_MV.substitute(
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_SEARCH.substitute(
                reference_genome="GRCh37",
                size=int(2e8),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_EXOMES_SEARCH.substitute(
                reference_genome="GRCh38",
                size=int(1e9),
            ),
            hints={"clickhouse": True},
        ),
    ]
