# Generated by Django 4.2.21 on 2025-12-04 16:24
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0028_topmed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadExomesAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesSeqrVariantsSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesGRCh37AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('filter_af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('hemi', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('hom', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/all_variants_mv',
                'to_table': 'GnomadExomesAllVariantsGRCh37SnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh37/gnomad_exomes/1.0.parquet/*.parquet',
                'column_selects': {'ac': 'AC', 'af': 'AF', 'an': 'AN', 'filter_af': 'AF_POPMAX_OR_GLOBAL', 'hemi': 'Hemi', 'hom': 'Hom', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('filter_af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('hemi', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('hom', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/all_variants_mv',
                'to_table': 'GnomadExomesAllVariantsSnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_exomes/1.0.parquet/*.parquet',
                'column_selects': {'ac': 'AC', 'af': 'AF', 'an': 'AN', 'filter_af': 'AF_POPMAX_OR_GLOBAL', 'hemi': 'Hemi', 'hom': 'Hom', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes/all_variants_to_seqr_variants_mv',
                'to_table': 'GnomadExomesSeqrVariantsGRCh37SnvIndel',
                'source_table': 'GnomadExomesAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes/all_variants_to_seqr_variants_mv',
                'to_table': 'GnomadExomesSeqrVariantsSnvIndel',
                'source_table': 'GnomadExomesAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesGRCh37Dict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnomad_exomes', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_exomes',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GnomadExomesSeqrVariantsGRCh37SnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadExomesDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnomad_exomes', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_exomes',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GnomadExomesSeqrVariantsSnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_exomes",
            ),
        ),
    ]
