# Generated by Django 4.2.21 on 2025-12-04 16:24
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary

GNOMAD_GENOMES_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variant_id as variantId,
    AC as ac,
    AF as af,
    AN as an,
    AF_POPMAX_OR_GLOBAL as filter_af,
    Hemi as hemi,
    Hom as hom
FROM gcs('https://seqr-reference-data.broadinstitute.org/v3.1/$reference_genome/gnomad_genomes/1.0.parquet/*.parquet')
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0029_gnomad_exomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadGenomesAllVariantsGRCh37SnvIndel',
            fields=[
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_genomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadGenomesAllVariantsSnvIndel',
            fields=[
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_genomes/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadGenomesSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadGenomesSeqrVariantsSnvIndel',
            fields=[
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('filter_af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('hemi', clickhouse_backend.models.UInt32Field()),
                ('hom', clickhouse_backend.models.UInt32Field()),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            GNOMAD_GENOMES_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh37", dataset_type="SNV_INDEL", reference_dataset="gnomad_genomes"),
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            GNOMAD_GENOMES_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="gnomad_genomes"),
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="gnomad_genomes",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="gnomad_genomes",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="gnomad_genomes",
                columns="""
                    `key` UInt32,
                    `ac` UInt32,
                    `af` Decimal(9, 8),
                    `an` UInt32,
                    `filter_af` Decimal(9, 8),
                    `hemi` UInt32,
                    `hom` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 200000000)"
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="gnomad_genomes",
                columns="""
                    `key` UInt32,
                    `ac` UInt32,
                    `af` Decimal(9, 8),
                    `an` UInt32,
                    `filter_af` Decimal(9, 8),
                    `hemi` UInt32,
                    `hom` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1000000000)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_genomes",
            ),
        ),
    ]
