# Generated by Django 4.2.21 on 2025-12-08 04:50
import os
from string import Template
import requests

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from settings import DATABASES, PIPELINE_RUNNER_SERVER

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, conditionally_refresh_reference_dataset

CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

SPLICE_AI_SEARCH = Template(Template("""
CREATE DICTIONARY `$reference_genome/SNV_INDEL/reference_data/splice_ai`
(
    `key` UInt32,
    `score` Decimal(9, 5),
    `consequence_id` UInt8
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    QUERY 'SELECT key, score, toUInt8(consequence) from  `$reference_genome/SNV_INDEL/reference_data/splice_ai/seqr_variants`'
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE $size))
""").safe_substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
))

SPLICE_AI_ALL_VARIANTS_MV = Template("""
CREATE MATERIALIZED VIEW `$reference_genome/SNV_INDEL/reference_data/splice_ai/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `$reference_genome/SNV_INDEL/reference_data/splice_ai/all_variants`
EMPTY
AS SELECT
    variant_id as variantId,
    delta_score as score,
    splice_consequence_id as consequence
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/$reference_genome/splice_ai/1.1.parquet/*.parquet')
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0030_gnomad_genomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceAiAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            SPLICE_AI_ALL_VARIANTS_MV.substitute(
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            SPLICE_AI_ALL_VARIANTS_MV.substitute(
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            SPLICE_AI_SEARCH.substitute(
                reference_genome="GRCh37",
                size=int(2e8),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            SPLICE_AI_SEARCH.substitute(
                reference_genome="GRCh38",
                size=int(1e9),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="splice_ai",
            ),
        ),
    ]
