# Generated by Django 4.2.21 on 2025-12-08 04:50
from string import Template
import requests

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary

SPLICE_AI_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variant_id as variantId,
    delta_score as score,
    splice_consequence_id as consequence
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/$reference_genome/splice_ai/1.1.parquet/*.parquet')
""")

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0030_gnomad_genomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceAiAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            SPLICE_AI_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh37", dataset_type="SNV_INDEL", reference_dataset="splice_ai"),
                reference_genome="GRCh37",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            SPLICE_AI_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="splice_ai"),
                reference_genome="GRCh38",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
                columns="""
                    `key` UInt32,
                    `score` Decimal(9, 5),
                    `consequence_id` UInt8
                """,
                primary_key="key",
                source="QUERY 'SELECT key, score, toUInt8(consequence) from  `$reference_genome/SNV_INDEL/reference_data/splice_ai/seqr_variants`'",
                layout="HASHED_ARRAY()"
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="splice_ai",
                columns="""
                    `key` UInt32,
                    `score` Decimal(9, 5),
                    `consequence_id` UInt8
                """,
                primary_key="key",
                source="QUERY 'SELECT key, score, toUInt8(consequence) from  `$reference_genome/SNV_INDEL/reference_data/splice_ai/seqr_variants`'",
                layout="HASHED_ARRAY()",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="splice_ai",
            ),
        ),
    ]
