# Generated by Django 4.2.21 on 2025-12-08 04:50
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0030_gnomad_genomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceAiAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiSeqrVariantsSnvIndel',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiGRCh37AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('consequence', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/all_variants_mv',
                'to_table': 'SpliceAiAllVariantsGRCh37SnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh37/splice_ai/1.1.parquet/*.parquet',
                'column_selects': {'consequence': 'splice_consequence_id', 'score': 'delta_score', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('consequence', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/all_variants_mv',
                'to_table': 'SpliceAiAllVariantsSnvIndel',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/splice_ai/1.1.parquet/*.parquet',
                'column_selects': {'consequence': 'splice_consequence_id', 'score': 'delta_score', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai/all_variants_to_seqr_variants_mv',
                'to_table': 'SpliceAiSeqrVariantsGRCh37SnvIndel',
                'source_table': 'SpliceAiAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence', clickhouse_backend.models.Enum8Field(choices=[(0, 'Acceptor gain'), (1, 'Acceptor loss'), (2, 'Donor gain'), (3, 'Donor loss'), (4, 'No consequence')])),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai/all_variants_to_seqr_variants_mv',
                'to_table': 'SpliceAiSeqrVariantsSnvIndel',
                'source_table': 'SpliceAiAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiGRCh37Dict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='splice_ai', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence_id', clickhouse_backend.models.UInt8Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/splice_ai',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'SpliceAiSeqrVariantsGRCh37SnvIndel',
                'layout': 'HASHED_ARRAY()',
                'clickhouse_query_template': 'SELECT key, score, toUInt8(consequence) from {table}',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpliceAiDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='splice_ai', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('consequence_id', clickhouse_backend.models.UInt8Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/splice_ai',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'SpliceAiSeqrVariantsSnvIndel',
                'layout': 'HASHED_ARRAY()',
                'clickhouse_query_template': 'SELECT key, score, toUInt8(consequence) from {table}',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="splice_ai",
            ),
        ),
    ]
