# Generated by Django 4.2.21 on 2025-12-09 19:25
import os
from string import Template
import requests

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from settings import DATABASES, PIPELINE_RUNNER_SERVER

CLICKHOUSE_WRITER_PASSWORD = os.environ.get('CLICKHOUSE_WRITER_PASSWORD', 'clickhouse_test')
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'clickhouse')

GNOMAD_MITO_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/gnomad_mito`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 8),
    `an` UInt32
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/gnomad_mito/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

GNOMAD_MITO_HETEROPLASMY_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 8),
    `an` UInt32,
    `max_hl` Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

HELIX_MITO_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/helix_mito`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 8),
    `an` UInt32
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/helix_mito/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

HELIX_MITO_HETEROPLASMY_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/helix_mito_heteroplasmy`
(
    `key` UInt32,
    `ac` UInt32,
    `af` Decimal(9, 8),
    `an` UInt32,
    `max_hl` Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/helix_mito_heteroplasmy/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

HMTVAR_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/hmtvar`
(
    `key` UInt32,
    `score` Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/hmtvar/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

MITIMPACT_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/mitimpact`
(
    `key` UInt32,
    `score` Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/mitimpact/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

LOCAL_CONSTRAINT_MITO_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/local_constraint_mito`
(
    `key` UInt32,
    `score` Decimal(9, 5)
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/local_constraint_mito/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

MITOMAP_SEARCH = Template("""
CREATE DICTIONARY `GRCh38/MITO/reference_data/mitomap`
(
    `key` UInt32,
    `pathogenic` Bool
)
PRIMARY KEY key
SOURCE(CLICKHOUSE(
    USER '$clickhouse_writer_user'
    PASSWORD '$clickhouse_writer_password'
    TABLE `GRCh38/MITO/reference_data/mitomap/seqr_variants`
))
LIFETIME(MIN 0 MAX 0)
LAYOUT(FLAT(MAX_ARRAY_SIZE 1e6))
""").substitute(
    # Note the nested Template-ing that allows
    # double substitution these shared values
    clickhouse_writer_user=CLICKHOUSE_WRITER_USER,
    clickhouse_writer_password=CLICKHOUSE_WRITER_PASSWORD,
)

ALL_TO_SEQR_MV = Template("""
CREATE MATERIALIZED VIEW `GRCh38/MITO/reference_data/$reference_dataset/all_variants_to_seqr_variants_mv`
REFRESH EVERY 10 YEAR
TO `GRCh38/MITO/reference_data/$reference_dataset/seqr_variants`
AS 
SELECT
    DISTINCT ON (key)
    key,
    COLUMNS('.*') EXCEPT(version, variantId, key)
FROM `GRCh38/MITO/reference_data/$reference_dataset/all_variants` src
INNER JOIN `GRCh38/MITO/key_lookup` dst
ON assumeNotNull(src.variantId) = dst.variantId
""")

GNOMAD_MITO_ALL_VARIANTS_MV = """
CREATE MATERIALIZED VIEW `GRCh38/MITO/reference_data/gnomad_mito/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `GRCh38/MITO/reference_data/gnomad_mito/all_variants`
EMPTY
AS SELECT
    variant_id AS variantId,
    AC_hom as ac,
    AF_hom as af,
    AN as an
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito/1.1.parquet/*.parquet')
"""

GNOMAD_MITO_HETEROPLASMY_ALL_VARIANTS_MV = """
CREATE MATERIALIZED VIEW `GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants`
EMPTY
AS SELECT
    variant_id as variantId,
    AC_het as ac,
    AF_hom as af,
    AN as an,
    max_hl
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito_heteroplasmy/1.1.parquet/*.parquet')
"""

HELIX_MITO_ALL_VARIANTS_MV = """
CREATE MATERIALIZED VIEW `GRCh38/MITO/reference_data/helix_mito/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `GRCh38/MITO/reference_data/helix_mito/all_variants`
EMPTY
AS SELECT
    concat(
        'M',
        '-',
        replace(locus, 'chrM:', ''), 
        '-',
        arrayStringConcat(
            arrayMap(x -> replaceAll(x, '"', ''), JSONExtractArrayRaw(assumeNotNull(alleles))), '-')
        ) AS variantId,
    counts_hom as ac,
    CAST(AF_hom AS Decimal(9, 8)) as af,
    if(
        toFloat64(AF_hom) > 0,
        CAST(counts_hom / toFloat64(AF_hom) AS Int32),
        CAST(counts_het / toFloat64(AF_het) AS Int32)
    ) as an
FROM url('https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv')
"""

HELIX_MITO_HETEROPLASMY_ALL_VARIANTS_MV = """
CREATE MATERIALIZED VIEW `GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants_mv`
REFRESH EVERY 10 YEAR
TO `GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants`
EMPTY
AS SELECT
    concat(
        'M',
        '-',
        replace(locus, 'chrM:', ''), 
        '-',
        arrayStringConcat(
            arrayMap(x -> replaceAll(x, '"', ''), JSONExtractArrayRaw(assumeNotNull(alleles))), '-')
        ) AS variantId,
    counts_het as ac,
    CAST(AF_het AS Decimal(9, 8)) as af,
    if(
        toFloat64(AF_hom) > 0,
        CAST(counts_hom / toFloat64(AF_hom) AS Int32),
        CAST(counts_het / toFloat64(AF_het) AS Int32)
    ) as an,anager
    max_ARF as max_hl
FROM url('https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv')
"""

def conditionally_refresh_view(reference_dataset: str):
    def inner(apps, schema_editor):
        if DATABASES['default']['NAME'].startswith('test_'):
            return
        requests.post(
            f"{PIPELINE_RUNNER_SERVER}/refresh_clickhouse_reference_dataset_enqueue",
            json={"reference_dataset": reference_dataset},
            timeout=60,
        )
    return inner

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0031_splice_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadMitoHeteroplasmyAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadMitoHeteroplasmySeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixMitoHeteroplasmyAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixMitoHeteroplasmySeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito_heteroplasmy/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HmtvarMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/hmtvar/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HmtvarMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/hmtvar/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalconstraintmitoMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/local_constraint_mito/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalconstraintmitoMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/local_constraint_mito/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitimpactMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitimpact/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitimpactMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitimpact/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitomapMitoAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('pathogenic', clickhouse_backend.models.BoolField()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitomap/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitomapMitoSeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('pathogenic', clickhouse_backend.models.BoolField())
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitomap/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            GNOMAD_MITO_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='gnomad_mito'),
        ),
        migrations.RunSQL(
            GNOMAD_MITO_ALL_VARIANTS_MV,
            hints={"clickhouse": True},
        )
        migrations.RunSQL(
            GNOMAD_MITO_HETEROPLASMY_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='gnomad_mito_heteroplasmy'),
        ),
        migrations.RunSQL(
            GNOMAD_MITO_HETEROPLASMY_ALL_VARIANTS_MV,
            hints={"clickhouse": True},
        )
        migrations.RunSQL(
            HELIX_MITO_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='helix_mito'),
        ),
        migrations.RunSQL(
            HELIX_MITO_ALL_VARIANTS_MV,
            hints={"clickhouse": True},
        )
        migrations.RunSQL(
            HELIX_MITO_HETEROPLASMY_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='helix_mito_heteroplasmy'),
        ),
        migrations.RunSQL(
            HELIX_MITO_HETEROPLASMY_ALL_VARIANTS_MV,
            hints={"clickhouse": True},
        )
        migrations.RunSQL(
            HMTVAR_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='hmtvar'),
        ),
        migrations.RunSQL(
            MITIMPACT_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='mitimpact'),
        ),
        migrations.RunSQL(
            LOCAL_CONSTRAINT_MITO_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='local_constraint_mito'),
        ),
        migrations.RunSQL(
            MITOMAP_SEARCH,
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(reference_dataset='mitomap'),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="gnomad_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="gnomad_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="helix_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="helix_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="hmtvar",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="mitimpact",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="local_constraint_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_view(
                reference_genome="mitomap",
            ),
        ),
    ]
