# Generated by Django 4.2.21 on 2025-12-08 04:50

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0031_splice_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbnsfpAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpAllVariantsMito',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsMito',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpGRCh37SnvIndelAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/all_variants_mv',
                'to_table': 'DbnsfpAllVariantsGRCh37SnvIndel',
                'source_sql': 'WHERE (arrayExists(x -> isNotNull(x), [cadd, fathmm, mpc, mut_pred, polyphen, primate_ai, revel, sift, vest]) OR isNotNull(mut_taster)) SETTINGS input_format_tsv_use_best_effort_in_schema_inference = 0',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh37/dbnsfp/dbNSFP5.3a_grch37.gz',
                'column_selects': {'cadd': 'CAST(`CADD_phred` as Nullable(Decimal(9, 5)))', 'fathmm': 'CAST(`fathmm-XF_coding_score` as Nullable(Decimal(9, 5)))', 'mpc': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MPC_score`))) as Nullable(Decimal(9, 5)))", 'mut_pred': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutPred2_score`))) as Nullable(Decimal(9, 5)))", 'mut_taster': "nullIf(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutationTaster_pred`))), '')", 'polyphen': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`Polyphen2_HVAR_score`))) as Nullable(Decimal(9, 5)))", 'primate_ai': 'CAST(`PrimateAI_score` as Nullable(Decimal(9, 5)))', 'revel': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`REVEL_score`))) as Nullable(Decimal(9, 5)))", 'sift': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`SIFT_score`))) as Nullable(Decimal(9, 5)))", 'variantId': "assumeNotNull(concat(`hg19_chr`, '-', `hg19_pos(1-based)`, '-', ref, '-', alt))", 'vest': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`VEST4_score`))) as Nullable(Decimal(9, 5)))"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSnvIndelAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/all_variants_mv',
                'to_table': 'DbnsfpAllVariantsSnvIndel',
                'source_sql': "WHERE (`#chr` != 'M') AND (arrayExists(x -> (x IS NOT NULL), [cadd, fathmm, mpc, mut_pred, polyphen, primate_ai, revel, sift, vest]) OR (mut_taster IS NOT NULL)) SETTINGS input_format_tsv_use_best_effort_in_schema_inference = 0",
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/dbnsfp/dbNSFP5.3a_grch38.gz',
                'column_selects': {'cadd': 'CAST(`CADD_phred` as Nullable(Decimal(9, 5)))', 'fathmm': 'CAST(`fathmm-XF_coding_score` as Nullable(Decimal(9, 5)))', 'mpc': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MPC_score`))) as Nullable(Decimal(9, 5)))", 'mut_pred': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutPred2_score`))) as Nullable(Decimal(9, 5)))", 'mut_taster': "nullIf(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutationTaster_pred`))), '')", 'polyphen': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`Polyphen2_HVAR_score`))) as Nullable(Decimal(9, 5)))", 'primate_ai': 'CAST(`PrimateAI_score` as Nullable(Decimal(9, 5)))', 'revel': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`REVEL_score`))) as Nullable(Decimal(9, 5)))", 'sift': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`SIFT_score`))) as Nullable(Decimal(9, 5)))", 'variantId': "assumeNotNull(concat(`#chr`, '-', `pos(1-based)`, '-', ref, '-', alt))", 'vest': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`VEST4_score`))) as Nullable(Decimal(9, 5)))"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpMitoAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/all_variants_mv',
                'to_table': 'DbnsfpAllVariantsMito',
                'source_sql': "WHERE `#chr` = 'M' AND isNotNull(sift) OR isNotNull(mut_taster) SETTINGS input_format_tsv_use_best_effort_in_schema_inference = 0",
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/dbnsfp/dbNSFP5.3a_grch38.gz',
                'column_selects': {'cadd': 'CAST(`CADD_phred` as Nullable(Decimal(9, 5)))', 'fathmm': 'CAST(`fathmm-XF_coding_score` as Nullable(Decimal(9, 5)))', 'mpc': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MPC_score`))) as Nullable(Decimal(9, 5)))", 'mut_pred': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutPred2_score`))) as Nullable(Decimal(9, 5)))", 'mut_taster': "nullIf(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`MutationTaster_pred`))), '')", 'polyphen': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`Polyphen2_HVAR_score`))) as Nullable(Decimal(9, 5)))", 'primate_ai': 'CAST(`PrimateAI_score` as Nullable(Decimal(9, 5)))', 'revel': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`REVEL_score`))) as Nullable(Decimal(9, 5)))", 'sift': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`SIFT_score`))) as Nullable(Decimal(9, 5)))", 'variantId': "assumeNotNull(concat(`#chr`, '-', `pos(1-based)`, '-', ref, '-', alt))", 'vest': "CAST(arrayFirst(x -> (x != '.'), splitByChar(';', assumeNotNull(`VEST4_score`))) as Nullable(Decimal(9, 5)))"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpGRCh37SnvIndelMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/all_variants_to_seqr_variants_mv',
                'to_table': 'DbnsfpSeqrVariantsGRCh37SnvIndel',
                'source_table': 'DbnsfpAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSnvIndelMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/all_variants_to_seqr_variants_mv',
                'to_table': 'DbnsfpSeqrVariantsSnvIndel',
                'source_table': 'DbnsfpAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpMitoMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/all_variants_to_seqr_variants_mv',
                'to_table': 'DbnsfpSeqrVariantsMito',
                'source_table': 'DbnsfpAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpGRCh37SnvIndelDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dbnsfp', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'DbnsfpSeqrVariantsGRCh37SnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSnvIndelDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dbnsfp', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'DbnsfpSeqrVariantsSnvIndel',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpMitoDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dbnsfp', serialize=False, to='clickhouse_search.entriesmito')),
                ('mut_taster', clickhouse_backend.models.StringField(blank=True, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'DbnsfpSeqrVariantsMito',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="dbnsfp",
            ),
        ),
    ]
