# Generated by Django 4.2.21 on 2025-12-09 19:25
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import (
    ALL_TO_SEQR_MV,
    ALL_VARIANTS_MV_HEADER,
    conditionally_refresh_reference_dataset,
    render_search_dictionary,
)

GNOMAD_MITO_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variant_id AS variantId,
    AC_hom as ac,
    AF_hom as af,
    AN as an
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito/1.1.parquet/*.parquet')
""")

GNOMAD_MITO_HETEROPLASMY_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variant_id as variantId,
    AC_het as ac,
    AF_hom as af,
    AN as an,
    max_hl
FROM gcs('https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito/1.1.parquet/*.parquet')
""")

HELIX_MITO_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    concat(
        'M',
        '-',
        replace(locus, 'chrM:', ''), 
        '-',
        arrayStringConcat(
            arrayMap(x -> replaceAll(x, '"', ''), JSONExtractArrayRaw(assumeNotNull(alleles))), '-')
        ) AS variantId,
    counts_hom as ac,
    CAST(AF_hom AS Decimal(9, 8)) as af,
    if(
        toFloat64(AF_hom) > 0,
        CAST(counts_hom / toFloat64(AF_hom) AS Int32),
        CAST(counts_het / toFloat64(AF_het) AS Int32)
    ) as an
FROM url('https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv')
""")

HELIX_MITO_HETEROPLASMY_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    concat(
        'M',
        '-',
        replace(locus, 'chrM:', ''), 
        '-',
        arrayStringConcat(
            arrayMap(x -> replaceAll(x, '"', ''), JSONExtractArrayRaw(assumeNotNull(alleles))), '-')
        ) AS variantId,
    counts_het as ac,
    CAST(AF_het AS Decimal(9, 8)) as af,
    if(
        toFloat64(AF_hom) > 0,
        CAST(counts_hom / toFloat64(AF_hom) AS Int32),
        CAST(counts_het / toFloat64(AF_het) AS Int32)
    ) as an,
    max_ARF as max_hl
FROM url('https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv')
""")

HMTVAR_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    variantId,
    max(score) AS score
FROM
(
    SELECT
        concat('M', '-', nt_start, '-', ref_rCRS, '-', alt) AS variantId,
        CAST(disease_score AS Decimal(9, 5)) AS score
    FROM url('https://storage.googleapis.com/seqr-reference-data/GRCh38/mitochondrial/HmtVar/HmtVar%20Jan.%2010%202022.json')
    WHERE match(alt, '^[ACTG]+$$') AND (disease_score IS NOT NULL)
)
GROUP BY variantId
""")

MITIMPACT_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT 
    variantId,
    max(score) as score
FROM (
    SELECT
        concat('M', '-', Start, '-', Ref, '-', Alt) as variantId,
        CAST(APOGEE2_score AS Decimal(9, 5)) AS score
    FROM url('https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/mitimpact/MitImpact_db_3.1.3.txt', 'TSV')
)
GROUP BY variantId
SETTINGS input_format_tsv_crlf_end_of_line = 1
""")

LOCAL_CONSTRAINT_MITO_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT 
    concat('M', '-', Position, '-', Reference, '-', Alternate) as variantId,
    CAST(MLC_score AS Decimal(9, 5)) AS score
FROM url('https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/local_constraint_mito/supplementary_dataset_7.tsv')
""")

MITOMAP_ALL_VARIANTS_MV = Template("""
$mv_header
AS SELECT
    concat(
        'M',
        '-',
        Position,
        '-',
        extract(assumeNotNull(Allele), 'm\\.[0-9]+([ATGC]+)>[ATGC]+'),
        '-',
        extract(assumeNotNull(Allele), 'm\\.[0-9]+[ATGC]+>([ATGC]+)')
    ) as variantId,
    true as pathogenic
FROM url('https://storage.googleapis.com/seqr-reference-data/GRCh38/mitochondrial/MITOMAP/mitomap_confirmed_mutations_nov_2024.csv', 'CsvWithNames')
WHERE variantId NOT LIKE '%--'
""")


class Migration(migrations.Migration):
    dependencies = [
        ("clickhouse_search", "0032_dbnsfp"),
    ]

    operations = [
        migrations.CreateModel(
            name="GnomadmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoheteroplasmyAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoheteroplasmySeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoheteroplasmyAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoheteroplasmySeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito_heteroplasmy/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HmtvarAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/hmtvar/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HmtvarSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/hmtvar/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LocalconstraintmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/local_constraint_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LocalconstraintmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/local_constraint_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitimpactAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitimpact/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitimpactSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitimpact/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitomapAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("pathogenic", clickhouse_backend.models.BoolField()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitomap/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitomapSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("pathogenic", clickhouse_backend.models.BoolField()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitomap/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="gnomad_mito",
            ),
        ),
        migrations.RunSQL(
            GNOMAD_MITO_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="gnomad_mito"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="gnomad_mito_heteroplasmy",
            ),
        ),
        migrations.RunSQL(
            GNOMAD_MITO_HETEROPLASMY_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="gnomad_mito_heteroplasmy"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="helix_mito",
            ),
        ),
        migrations.RunSQL(
            HELIX_MITO_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="helix_mito"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="helix_mito_heteroplasmy",
            ),
        ),
        migrations.RunSQL(
            HELIX_MITO_HETEROPLASMY_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="helix_mito_heteroplasmy"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="hmtvar",
            ),
        ),
        migrations.RunSQL(
            HMTVAR_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="hmtvar"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="mitimpact",
            ),
        ),
        migrations.RunSQL(
            MITIMPACT_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="mitimpact"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="local_constraint_mito",
            ),
        ),
        migrations.RunSQL(
            LOCAL_CONSTRAINT_MITO_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="local_constraint_mito"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="mitomap",
            ),
        ),
        migrations.RunSQL(
            MITOMAP_ALL_VARIANTS_MV.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="MITO", reference_dataset="mitomap"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="gnomad_mito",
                columns="""
                   `key` UInt32,
                   `ac` UInt32,
                   `af` Decimal(9, 8),
                   `an` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/gnomad_mito/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="gnomad_mito_heteroplasmy",
                columns="""
                   `key` UInt32,
                   `ac` UInt32,
                   `af` Decimal(9, 8),
                   `an` UInt32,
                   `max_hl` Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="helix_mito",
                columns="""
                   `key` UInt32,
                   `ac` UInt32,
                   `af` Decimal(9, 8),
                   `an` UInt32
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/helix_mito/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="helix_mito_heteroplasmy",
                columns="""
                   `key` UInt32,
                   `ac` UInt32,
                   `af` Decimal(9, 8),
                   `an` UInt32,
                   `max_hl` Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/helix_mito_heteroplasmy/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="hmtvar",
                columns="""
                   `key` UInt32,
                   `score` Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/hmtvar/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="mitimpact",
                columns="""
                   `key` UInt32,
                   `score` Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/mitimpact/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="local_constraint_mito",
                columns="""
                   `key` UInt32,
                   `score` Decimal(9, 5)
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/local_constraint_mito/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="MITO",
                reference_dataset="mitomap",
                columns="""
                   `key` UInt32,
                   `pathogenic` Bool
                """,
                primary_key="key",
                source="TABLE `GRCh38/MITO/reference_data/mitomap/seqr_variants`",
                layout="FLAT(MAX_ARRAY_SIZE 1e6)",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="helix_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="helix_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="hmtvar",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="mitimpact",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="local_constraint_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="mitomap",
            ),
        ),
    ]
