# Generated by Django 4.2.21 on 2025-12-09 19:25
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.models.reference_data_models import conditionally_refresh_reference_dataset

class Migration(migrations.Migration):
    dependencies = [
        ("clickhouse_search", "0032_dbnsfp"),
    ]

    operations = [
        migrations.CreateModel(
            name="GnomadmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoheteroplasmyAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="GnomadmitoheteroplasmySeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoheteroplasmyAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HelixmitoheteroplasmySeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("ac", clickhouse_backend.models.UInt32Field()),
                (
                    "af",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=8, max_digits=9
                    ),
                ),
                ("an", clickhouse_backend.models.UInt32Field()),
                (
                    "max_hl",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/helix_mito_heteroplasmy/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HmtvarAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/hmtvar/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HmtvarSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/hmtvar/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LocalconstraintmitoAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/local_constraint_mito/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LocalconstraintmitoSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/local_constraint_mito/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitimpactAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitimpact/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitimpactSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                (
                    "score",
                    clickhouse_backend.models.DecimalField(
                        decimal_places=5, max_digits=9
                    ),
                ),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitimpact/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitomapAllVariantsMito",
            fields=[
                (
                    "variant_id",
                    clickhouse_backend.models.StringField(
                        db_column="variantId", primary_key=True, serialize=False
                    ),
                ),
                ("pathogenic", clickhouse_backend.models.BoolField()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitomap/all_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="variant_id", primary_key="variant_id"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MitomapSeqrVariantsMito",
            fields=[
                (
                    "key",
                    models.OneToOneField(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clickhouse_search.annotationsmito",
                    ),
                ),
                ("pathogenic", clickhouse_backend.models.BoolField()),
            ],
            options={
                "db_table": "GRCh38/MITO/reference_data/mitomap/seqr_variants",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by="key", primary_key="key"
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito/all_variants_to_seqr_variants_mv',
                'to_table': 'GnomadmitoSeqrVariantsMito',
                'source_table': 'GnomadmitoAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito/all_variants_mv',
                'to_table': 'GnomadmitoAllVariantsMito',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito/1.1.parquet/*.parquet',
                'column_selects': {'ac': 'AC_hom', 'af': 'AF_hom', 'an': 'AN', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoheteroplasmyMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants_to_seqr_variants_mv',
                'to_table': 'GnomadmitoheteroplasmySeqrVariantsMito',
                'source_table': 'GnomadmitoheteroplasmyAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoheteroplasmyAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.Float32Field(blank=True, null=True)),
                ('an', clickhouse_backend.models.Int32Field(blank=True, null=True)),
                ('max_hl', clickhouse_backend.models.Float32Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy/all_variants_mv',
                'to_table': 'GnomadmitoheteroplasmyAllVariantsMito',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/gnomad_mito/1.1.parquet/*.parquet',
                'column_selects': {'ac': 'AC_het', 'af': 'AF_hom', 'an': 'AN', 'variantId': 'assumeNotNull(variant_id)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito/all_variants_to_seqr_variants_mv',
                'to_table': 'HelixmitoSeqrVariantsMito',
                'source_table': 'HelixmitoAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int64Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.Int32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito/all_variants_mv',
                'to_table': 'HelixmitoAllVariantsMito',
                'source_sql': '',
                'source_url': 'https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv',
                'column_selects': {'ac': 'counts_hom', 'af': 'CAST(AF_hom AS Decimal(9, 8))', 'an': 'if(toFloat64(AF_hom) > 0, CAST(counts_hom / toFloat64(AF_hom) AS Int32), CAST(counts_het / toFloat64(AF_het) AS Int32))', 'variantId': 'assumeNotNull(concat(\'M\', \'-\', replace(locus, \'chrM:\', \'\'), \'-\', arrayStringConcat(arrayMap(x -> replaceAll(x, \'"\', \'\'), JSONExtractArrayRaw(assumeNotNull(alleles))), \'-\')))'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoheteroplasmyMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants_to_seqr_variants_mv',
                'to_table': 'HelixmitoheteroplasmySeqrVariantsMito',
                'source_table': 'HelixmitoheteroplasmyAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoheteroplasmyAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('ac', clickhouse_backend.models.Int64Field(blank=True, null=True)),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.Int32Field()),
                ('max_hl', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito_heteroplasmy/all_variants_mv',
                'to_table': 'HelixmitoheteroplasmyAllVariantsMito',
                'source_sql': '',
                'source_url': 'https://helix-research-public.s3.amazonaws.com/mito/HelixMTdb_20200327.tsv',
                'column_selects': {'ac': 'counts_het', 'af': 'CAST(AF_het AS Decimal(9, 8))', 'an': 'if(toFloat64(AF_hom) > 0, CAST(counts_hom / toFloat64(AF_hom) AS Int32), CAST(counts_het / toFloat64(AF_het) AS Int32))', 'max_hl': 'max_ARF', 'variantId': 'assumeNotNull(concat(\'M\', \'-\', replace(locus, \'chrM:\', \'\'), \'-\', arrayStringConcat(arrayMap(x -> replaceAll(x, \'"\', \'\'), JSONExtractArrayRaw(assumeNotNull(alleles))), \'-\')))'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HmtvarMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/hmtvar/all_variants_to_seqr_variants_mv',
                'to_table': 'HmtvarSeqrVariantsMito',
                'source_table': 'HmtvarAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HmtvarAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/hmtvar/all_variants_mv',
                'to_table': 'HmtvarAllVariantsMito',
                'source_sql': 'GROUP BY variantId',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/GRCh38/mitochondrial/HmtVar/HmtVar%20Jan.%2010%202022.json',
                'source_url_template': "(SELECT concat('M', '-', nt_start, '-', ref_rCRS, '-', alt) as variantId, CAST(disease_score AS Decimal(9, 5)) AS score FROM url('{source_url}') WHERE match(alt, '^[ACTG]+$$') AND (disease_score IS NOT NULL))",
                'column_selects': {'score': 'max(score)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitimpactMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitimpact/all_variants_to_seqr_variants_mv',
                'to_table': 'MitimpactSeqrVariantsMito',
                'source_table': 'MitimpactAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitimpactAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitimpact/all_variants_mv',
                'to_table': 'MitimpactAllVariantsMito',
                'source_sql': 'GROUP BY variantId SETTINGS input_format_tsv_crlf_end_of_line = 1',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/mitimpact/MitImpact_db_3.1.3.txt',
                'source_url_template': "(SELECT concat('M', '-', Start, '-', Ref, '-', Alt) as variantId, CAST(APOGEE2_score AS Decimal(9, 5)) AS score FROM url('{source_url}', 'TSV'))",
                'column_selects': {'score': 'max(score)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalconstraintmitoMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/local_constraint_mito/all_variants_to_seqr_variants_mv',
                'to_table': 'LocalconstraintmitoSeqrVariantsMito',
                'source_table': 'LocalconstraintmitoAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalconstraintmitoAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/local_constraint_mito/all_variants_mv',
                'to_table': 'LocalconstraintmitoAllVariantsMito',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/local_constraint_mito/supplementary_dataset_7.tsv',
                'column_selects': {'score': 'CAST(MLC_score AS Decimal(9, 5))', 'variantId': "concat('M', '-', Position, '-', Reference, '-', Alternate)"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitomapMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('pathogenic', clickhouse_backend.models.BoolField()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitomap/all_variants_to_seqr_variants_mv',
                'to_table': 'MitomapSeqrVariantsMito',
                'source_table': 'MitomapAllVariantsMito',
                'source_sql': 'src INNER JOIN `GRCh38/MITO/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitomapAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('pathogenic', clickhouse_backend.models.BoolField()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitomap/all_variants_mv',
                'to_table': 'MitomapAllVariantsMito',
                'source_sql': "WHERE variantId NOT LIKE '%--'",
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/GRCh38/mitochondrial/MITOMAP/mitomap_confirmed_mutations_nov_2024.csv',
                'source_url_template': "url('{source_url}', 'CsvWithNames')",
                'column_selects': {'pathogenic': 'true', 'variantId': "concat('M', '-', Position, '-', extract(assumeNotNull(Allele), 'm\\.[0-9]+([ATGC]+)>[ATGC]+'), '-', extract(assumeNotNull(Allele), 'm\\.[0-9]+[ATGC]+>([ATGC]+)'))"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnomad_mito', serialize=False, to='clickhouse_search.entriesmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GnomadmitoSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GnomadmitoheteroplasmyDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnomad_mito_heteroplasmy', serialize=False, to='clickhouse_search.entriesmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/gnomad_mito_heteroplasmy',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'GnomadmitoheteroplasmySeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='helix', serialize=False, to='clickhouse_search.entriesmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'HelixmitoSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelixmitoheteroplasmyDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='helix_heteroplasmy', serialize=False, to='clickhouse_search.entriesmito')),
                ('ac', clickhouse_backend.models.UInt32Field()),
                ('af', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
                ('an', clickhouse_backend.models.UInt32Field()),
                ('max_hl', clickhouse_backend.models.DecimalField(decimal_places=8, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/helix_mito_heteroplasmy',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'HelixmitoheteroplasmySeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HmtvarDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hmtvar', serialize=False, to='clickhouse_search.entriesmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/hmtvar',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'HmtvarSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitimpactDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apogee', serialize=False, to='clickhouse_search.entriesmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitimpact',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'MitimpactSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalconstraintmitoDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mlc', serialize=False, to='clickhouse_search.entriesmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/local_constraint_mito',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'LocalconstraintmitoSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MitomapDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mitomap', serialize=False, to='clickhouse_search.entriesmito')),
                ('pathogenic', clickhouse_backend.models.BoolField()),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/mitomap',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'MitomapSeqrVariantsMito',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1e6)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="gnomad_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="helix_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="helix_mito_heteroplasmy",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="hmtvar",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="mitimpact",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="local_constraint_mito",
            ),
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="mitomap",
            ),
        ),
    ]
