# Generated by Django 4.2.21 on 2025-12-08 04:50
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary

DBNSFP_ALL_VARIANTS_MV_GRCh37 = Template("""
$mv_header
AS SELECT
    concat(
        `hg19_chr`,
        '-',
        `hg19_pos(1-based)`,
        '-',
        ref,
        '-',
        alt
    ) as variantId,
    CAST(`CADD_phred` as Decimal(9, 5)) as cadd,
    CAST(`fathmm-XF_coding_score` as Decimal(9, 5)) as fathmm,
    CAST(`MPC_score` as Decimal(9, 5)) as mpc,
    CAST(`MutPred2_score` as Decimal(9, 5)) as mut_pred,
    arrayFirst(x -> x != '.', splitByChar(';', assumeNotNull(MutationTaster_pred))) as mut_tester,
    CAST(`Polyphen2_HVAR_score` as Decimal(9, 5)) as polyphen,
    CAST(`PrimateAI_score` as Decimal(9, 5)) as primate_ai,
    CAST(`REVEL_score` as Decimal(9, 5)) as revel,
    CAST(`SIFT_score` as Decimal(9, 5)) as sift,
    CAST(`VEST4_score` as Decimal(9, 5)) as vest
FROM gcs('https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh37/dbnsfp/dbNSFP5.3a_grch37.gz', 'TSV')
""")

DBNSFP_ALL_VARIANTS_MV_GRCh38 = Template("""
$mv_header
AS SELECT
    concat(
        `#chr`,
        '-',
        `pos(1-based)`,
        '-',
        ref,
        '-',
        alt
    ) as variantId,
    CAST(`CADD_phred` as Decimal(9, 5)) as cadd,
    CAST(`fathmm-XF_coding_score` as Decimal(9, 5)) as fathmm,
    CAST(`MPC_score` as Decimal(9, 5)) as mpc,
    CAST(`MutPred2_score` as Decimal(9, 5)) as mut_pred,
    arrayFirst(x -> x != '.', splitByChar(';', assumeNotNull(MutationTaster_pred))) as mut_tester,
    CAST(`Polyphen2_HVAR_score` as Decimal(9, 5)) as polyphen,
    CAST(`PrimateAI_score` as Decimal(9, 5)) as primate_ai,
    CAST(`REVEL_score` as Decimal(9, 5)) as revel,
    CAST(`SIFT_score` as Decimal(9, 5)) as sift,
    CAST(`VEST4_score` as Decimal(9, 5)) as vest
FROM gcs('https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/dbnsfp/dbNSFP5.3a_grch38.gz', 'TSV')
""")


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0032_eigen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbnsfpAllVariantsGRCh37SnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpAllVariantsSnvIndel',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsSnvIndel',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
                ('cadd', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('fathmm', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mpc', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_pred', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('polyphen', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('primate_ai', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('revel', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('vest', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            DBNSFP_ALL_VARIANTS_MV_GRCh37.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh37", dataset_type="SNV_INDEL", reference_dataset="dbnsfp"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            DBNSFP_ALL_VARIANTS_MV_GRCh38.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="dbnsfp"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="dbnsfp",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="dbnsfp",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
                reference_dataset="dbnsfp",
                columns="""
                    `key` UInt32,
                    `cadd` Nullable(Decimal(9, 5)),
                    `fathmm` Nullable(Decimal(9, 5)),
                    `mpc` Nullable(Decimal(9, 5)),
                    `mut_pred` Nullable(Decimal(9, 5)),
                    `mut_taster` Nullable(String),
                    `polyphen` Nullable(Decimal(9, 5)),
                    `primate_ai` Nullable(Decimal(9, 5)),
                    `revel` Nullable(Decimal(9, 5)),
                    `sift` Nullable(Decimal(9, 5)),
                    `vest` Nullable(Decimal(9, 5))
                """,
                primary_key="key",
                source="TABLE `GRCh37/SNV_INDEL/reference_data/dbnsfp/seqr_variants`",
                layout="HASHED_ARRAY()"
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="dbnsfp",
                columns="""
                    `key` UInt32,
                    `cadd` Nullable(Decimal(9, 5)),
                    `fathmm` Nullable(Decimal(9, 5)),
                    `mpc` Nullable(Decimal(9, 5)),
                    `mut_pred` Nullable(Decimal(9, 5)),
                    `mut_taster` Nullable(String),
                    `polyphen` Nullable(Decimal(9, 5)),
                    `primate_ai` Nullable(Decimal(9, 5)),
                    `revel` Nullable(Decimal(9, 5)),
                    `sift` Nullable(Decimal(9, 5)),
                    `vest` Nullable(Decimal(9, 5))
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/dbnsfp/seqr_variants`",
                layout="HASHED_ARRAY()",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="dbnsfp",
            ),
        ),
    ]
