# Generated by Django 4.2.21 on 2025-12-14 16:20
import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0033_mito_all_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absplice2AllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absplice2SeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absplice2AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/all_variants_mv',
                'to_table': 'Absplice2AllVariants',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/absplice2/absplice2.tsv.gz',
                'column_selects': {'score': 'AbSplice_DNA_max', 'variantId': "assumeNotNull(concat(replaceOne(replaceOne(chrom, 'chr', ''), 'MT', 'M'), '-', pos, '-', ref, '-', alt))"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absplice2Dict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='absplice', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'Absplice2SeqrVariants',
                'layout': 'HASHED_ARRAY()',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absplice2Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/all_variants_to_seqr_variants_mv',
                'to_table': 'Absplice2SeqrVariants',
                'source_table': 'Absplice2AllVariants',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="absplice2",
            ),
        ),
    ]
