# Generated by Django 4.2.21 on 2025-12-14 16:20

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.manager

import clickhouse_search.backend.fields
from clickhouse_search.migration_templates import conditionally_refresh_reference_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0034_absplice2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterAIAllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('gene_id', clickhouse_backend.models.StringField(db_column='geneId')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/promoterAI/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PromoterAISeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('gene_id', clickhouse_backend.models.StringField(db_column='geneId')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/promoterAI/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PromoterAIAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('gene_id', clickhouse_backend.models.StringField(db_column='geneId')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/promoterAI/all_variants_mv',
                'to_table': 'PromoterAIAllVariants',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/promoterAI/promoterAI.tsv.gz',
                'column_selects': {'geneId': 'gene_id', 'score': 'promoterAI,', 'variantId': "concat(replaceOne(replaceOne(chrom, 'chr', ''), 'MT', 'M'), '-', pos, '-', ref, '-', alt)"},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PromoterAIMv',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('gene_id', clickhouse_backend.models.StringField(db_column='geneId')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/promoterAI/all_variants_to_seqr_variants_mv',
                'to_table': 'PromoterAISeqrVariants',
                'source_table': 'PromoterAIAllVariants',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PromoterAIDict',
            fields=[
                ('key', clickhouse_search.backend.fields.UInt32FieldDeltaCodecField(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/promoterAI',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'PromoterAISeqrVariants',
                'layout': 'HASHED_ARRAY()',
                'clickhouse_query_template': 'SELECT key, max(score) from {table} GROUP BY key',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="promoterAI",
            ),
        ),
    ]
