# Generated by Django 4.2.21 on 2025-12-14 16:20
from string import Template

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from clickhouse_search.migration_templates import ALL_TO_SEQR_MV, ALL_VARIANTS_MV_HEADER, conditionally_refresh_reference_dataset, render_search_dictionary


ABSPLICE2_ALL_VARIANTS_MV_GRCh38 = Template("""
$mv_header
AS SELECT
    concat(
        replaceOne(replaceOne(chrom, 'chr', ''), 'MT', 'M'),
        '-',
        pos,
        '-',
        ref,
        '-',
        alt
    ) as variantId,
    AbSplice_DNA_max as score
FROM url('https://storage.googleapis.com/seqr-reference-data/clickhouse/GRCh38/absplice2/absplice2.tsv.gz')
""")


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0034_mito_all_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absplice2AllVariants',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absplice2SeqrVariants',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/absplice2/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            ABSPLICE2_ALL_VARIANTS_MV_GRCh38.substitute(
                mv_header=ALL_VARIANTS_MV_HEADER.substitute(reference_genome="GRCh38", dataset_type="SNV_INDEL", reference_dataset="absplice2"),
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            ALL_TO_SEQR_MV.substitute(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="absplice2",
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunSQL(
            render_search_dictionary(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
                reference_dataset="absplice2",
                columns="""
                    `key` UInt32,
                    `score` Decimal(9, 5),
                """,
                primary_key="key",
                source="TABLE `GRCh38/SNV_INDEL/reference_data/absplice2/seqr_variants`",
                layout="HASHED_ARRAY()"
            ),
            hints={"clickhouse": True},
        ),
        migrations.RunPython(
            conditionally_refresh_reference_dataset(
                reference_dataset="absplice2",
            ),
        ),
    ]
