# Generated by Django 4.2.21 on 2025-12-14 16:20
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0035_promoterai'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/reference_data/gnomad_genomes/all_variants` MODIFY COLUMN variantId String FIRST;"
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/reference_data/gnomad_genomes/all_variants` MODIFY COLUMN variantId String FIRST;"
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants` MODIFY COLUMN key UInt32 FIRST;"
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/reference_data/gnomad_genomes/seqr_variants` MODIFY COLUMN key UInt32 FIRST;"
            hints={'clickhouse': True},
        ),
    ]
