# Generated by Django 4.2.21 on 2026-01-05 21:07

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0036_promoterai'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbnsfpAllVariantsMito',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DbnsfpSeqrVariantsMito',
            fields=[
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsmito')),
                ('mut_taster', clickhouse_backend.models.Enum8Field(blank=True, choices=[(0, 'D'), (1, 'A'), (2, 'N'), (3, 'P')], null=True)),
                ('sift', clickhouse_backend.models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'GRCh38/MITO/reference_data/dbnsfp/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
