# Generated by Django 4.2.21 on 2025-11-19 20:29
# Modified by the seqr team.
from django.db import migrations, connections

def optimize_partitions(apps, schema_editor):
    with connections['clickhouse_write'].cursor() as cursor:
        # GRCh37
        cursor.execute(
            '''
            SELECT DISTINCT project_guid 
            FROM 'GRCh37/SNV_INDEL/entries'
            WHERE sign = -1
            '''
        )
        project_guids = [row[0] for row in cursor.fetchall()]
        for project_guid in project_guids:
            cursor.execute(f"OPTIMIZE TABLE `GRCh37/SNV_INDEL/entries` PARTITION '{project_guid}' FINAL ASYNC")

        # Check if GRCh38 is repartitioned
        cursor.execute(
            '''
            SELECT DISTINCT project_guid 
            FROM 'GRCh38/SNV_INDEL/entries'
            WHERE sign = -1
            '''
        )
        project_guids = [row[0] for row in cursor.fetchall()]
        cursor.execute(
            '''
            SELECT create_table_query
            FROM system.tables
            WHERE database = currentDatabase() AND name = %(table_name)s;
            ''',
            {'table_name': 'GRCh38/SNV_INDEL/entries'},
        )
        row = cursor.fetchone()
        if not row:
            return
        if 'farmHash64(family_guid)' not in row[0]:
            for project_guid in project_guids:
                cursor.execute(f"OPTIMIZE TABLE `GRCh38/SNV_INDEL/entries` PARTITION '{project_guid}' FINAL ASYNC")
        else:
            for project_guid in project_guids:
                cursor.execute(
                    '''
                    SELECT n_partitions
                    FROM `GRCh38/SNV_INDEL/project_partitions`
                    WHERE project_guid = %(project_guid)s
                    ''',
                    {'project_guid': project_guid},
                )
                row = cursor.fetchone()
                if row is None:
                    n_partitions = 1
                else:
                    n_partitions = row[0]
                for n in range(0, n_partitions):
                    cursor.execute(f"OPTIMIZE TABLE `GRCh38/SNV_INDEL/entries` PARTITION ('{project_guid}', {n}) FINAL ASYNC")

class Migration(migrations.Migration):
    dependencies = [
        ('clickhouse_search', '0036_gnomad_genomes_columnbugfix'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `GRCh37/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 0;",
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            "ALTER TABLE `GRCh38/SNV_INDEL/entries` MODIFY COLUMN `is_annotated_in_any_gene` Bool DEFAULT length(geneId_ids) > 0;",
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            """
            INSERT INTO `GRCh37/SNV_INDEL/entries`
            SELECT COLUMNS('.*') EXCEPT(sign, n_partitions, partition_id), -1 as sign
            FROM `GRCh37/SNV_INDEL/entries`
            WHERE length(geneId_ids) = 1 AND is_annotated_in_any_gene = false
            """,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            """
            INSERT INTO `GRCh38/SNV_INDEL/entries`
            SELECT COLUMNS('.*') EXCEPT(sign, n_partitions, partition_id), -1 as sign
            FROM `GRCh38/SNV_INDEL/entries`
            WHERE length(geneId_ids) = 1 AND is_annotated_in_any_gene = false
            """,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            """
            INSERT INTO `GRCh37/SNV_INDEL/entries`
            SELECT 
            key, project_guid, family_guid, sample_type, 
            xpos, is_gnomad_gt_5_percent, length(geneId_ids) > 0 as is_annotated_in_any_gene,
            geneId_ids, filters, calls, 1 as sign
            FROM `GRCh37/SNV_INDEL/entries`
            WHERE sign=-1
            """,
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            """
            INSERT INTO `GRCh38/SNV_INDEL/entries`
            SELECT 
            key, project_guid, family_guid, sample_type, 
            xpos, is_gnomad_gt_5_percent, length(geneId_ids) > 0 as is_annotated_in_any_gene,
            geneId_ids, filters, calls, 1 as sign
            FROM `GRCh38/SNV_INDEL/entries`
            WHERE sign=-1
            """,
            hints={'clickhouse': True},
        ),
        migrations.RunPython(
            optimize_partitions,
            reverse_code=migrations.RunPython.noop
        ),
    ]
