# Generated by Django 4.2.21 on 2026-01-20 18:18

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0037_geneIds_bugfix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EigenAllVariantsGRCh37SnvIndel',
            fields=[
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenAllVariantsSnvIndel',
            fields=[
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/eigen/all_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='variant_id', primary_key='variant_id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenSeqrVariantsGRCh37SnvIndel',
            fields=[
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationsgrch37snvindel')),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenSeqrVariantsSnvIndel',
            fields=[
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
                ('key', models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.annotationssnvindel')),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/eigen/seqr_variants',
                'engine': clickhouse_backend.models.MergeTree(order_by='key', primary_key='key'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenGRCh37AllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen/all_variants_mv',
                'to_table': 'EigenAllVariants',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh37/eigen/1.1.parquet/*.parquet',
                'column_selects': {'score': 'Eigen_phred', 'variantId': 'variant_id'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenAllMv',
            fields=[
                ('variant_id', clickhouse_backend.models.StringField(db_column='variantId', primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.StringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/eigen/all_variants_mv',
                'to_table': 'EigenAllVariants',
                'source_sql': '',
                'source_url': 'https://storage.googleapis.com/seqr-reference-data/v3.1/GRCh38/eigen/1.1.parquet/*.parquet',
                'column_selects': {'score': 'Eigen_phred', 'variantId': 'variant_id'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv',
                'to_table': 'EigenSeqrVariantsGRCh37SnvIndel',
                'source_table': 'EigenAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenMv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv',
                'to_table': 'EigenSeqrVariantsSnvIndel',
                'source_table': 'EigenAllVariantsSnvIndel',
                'source_sql': 'src INNER JOIN `GRCh38/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenDict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eigen', serialize=False, to='clickhouse_search.entriessnvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/eigen',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'EigenSeqrVariantsSnvIndel',
                'layout': 'FLAT(MAX_ARRAY_SIZE 1000000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EigenGRCh37Dict',
            fields=[
                ('key', clickhouse_search.backend.fields.DictKeyForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eigen', serialize=False, to='clickhouse_search.entriesgrch37snvindel')),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen',
                'engine': clickhouse_backend.models.MergeTree(primary_key='key'),
                'source_table': 'EigenSeqrVariantsGRCh37SnvIndel',
                'layout': 'FLAT(MAX_ARRAY_SIZE 200000000)',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
