# Generated by Django 4.2.24 on 2026-01-22 20:33

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0038_eigen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GnomadNonCodingConstraintDict',
        ),
        migrations.CreateModel(
            name='GnomadNonCodingConstraintDict',
            fields=[
                ('chrom_id', clickhouse_backend.models.Int8Field(primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint',
                'engine': clickhouse_backend.models.MergeTree(primary_key='chrom_id'),
                'source_table': 'GnomadNonCodingConstraintAllVariantsSnvIndel',
                'layout': 'RANGE_HASHED()',
                'clickhouse_query_template': "SELECT indexOf([\\'1\\', \\'2\\', \\'3\\', \\'4\\', \\'5\\', \\'6\\', \\'7\\', \\'8\\', \\'9\\', \\'10\\', \\'11\\', \\'12\\', \\'13\\', \\'14\\', \\'15\\', \\'16\\', \\'17\\', \\'18\\', \\'19\\', \\'20\\', \\'21\\', \\'22\\', \\'X\\', \\'Y\\', \\'M\\'], chrom) as chrom_id, start, end, score from {table}",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            'SYSTEM RELOAD DICTIONARY "GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint"',
            hints={'clickhouse': True},
        ),
    ]
