# Generated by Django 4.2.24 on 2026-01-22 20:33

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0039_variantsdiskgcnv_variantsdiskgrch37snvindel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GnomadNonCodingConstraintDict',
        ),
        migrations.CreateModel(
            name='GnomadNonCodingConstraintDict',
            fields=[
                ('chrom_id', clickhouse_backend.models.Int8Field(primary_key=True, serialize=False)),
                ('start', clickhouse_backend.models.UInt32Field()),
                ('end', clickhouse_backend.models.UInt32Field()),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint',
                'engine': clickhouse_backend.models.MergeTree(primary_key='chrom_id'),
                'source_table': 'GnomadNonCodingConstraintAllVariantsSnvIndel',
                'layout': 'RANGE_HASHED()',
                'clickhouse_query_template': "SELECT indexOf([\\'1\\', \\'2\\', \\'3\\', \\'4\\', \\'5\\', \\'6\\', \\'7\\', \\'8\\', \\'9\\', \\'10\\', \\'11\\', \\'12\\', \\'13\\', \\'14\\', \\'15\\', \\'16\\', \\'17\\', \\'18\\', \\'19\\', \\'20\\', \\'21\\', \\'22\\', \\'X\\', \\'Y\\', \\'M\\'], chrom) as chrom_id, start, end, score from {table}",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='EigenGRCh37Mv',
        ),
        migrations.CreateModel(
            name='EigenGRCh37Mv',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('score', clickhouse_backend.models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'GRCh37/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv',
                'to_table': 'EigenSeqrVariantsGRCh37SnvIndel',
                'source_table': 'EigenAllVariantsGRCh37SnvIndel',
                'source_sql': 'src INNER JOIN `GRCh37/SNV_INDEL/key_lookup` dst on assumeNotNull(src.variantId) = dst.variantId',
                'column_selects': {'key': 'DISTINCT ON (key)'},
                'refreshable': True,
                'create_empty': True,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            'SYSTEM RELOAD DICTIONARY "GRCh38/SNV_INDEL/reference_data/gnomad_non_coding_constraint"',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'SYSTEM START VIEW "GRCh37/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv"',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'SYSTEM REFRESH VIEW "GRCh37/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv"',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'SYSTEM WAIT VIEW "GRCh37/SNV_INDEL/reference_data/eigen/all_variants_to_seqr_variants_mv"',
            hints={'clickhouse': True},
        ),
        migrations.RunSQL(
            'SYSTEM RELOAD DICTIONARY "GRCh37/SNV_INDEL/reference_data/eigen"',
            hints={'clickhouse': True},
        ),
    ]
