# Generated by Django 4.2.24 on 2026-02-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0040_gnomadnoncodingconstraintdict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranscriptsGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='TranscriptsSnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskGcnv',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskMito',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskSnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskSv',
        ),
        migrations.DeleteModel(
            name='AnnotationsGcnv',
        ),
        migrations.DeleteModel(
            name='AnnotationsMito',
        ),
        migrations.DeleteModel(
            name='AnnotationsSv',
        ),
        migrations.DeleteModel(
            name='AnnotationsGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsSnvIndel',
        ),
    ]
