# Generated by Django 4.2.24 on 2026-01-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0040_gnomadnoncodingconstraintdict'),
    ]

    operations = [
        migrations.RunSQL(
            'SELECT 1',
            hints={'clickhouse': True},
            state_operations = [
                migrations.AlterField(
                    model_name='entriesgcnv',
                    name='key',
                    field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantsgcnv'),
                ),
                migrations.AlterField(
                    model_name='entriesgrch37snvindel',
                    name='key',
                    field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantsgrch37snvindel'),
                ),
                migrations.AlterField(
                    model_name='entriesmito',
                    name='key',
                    field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantsmito'),
                ),
                migrations.AlterField(
                    model_name='entriessnvindel',
                    name='key',
                    field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantssnvindel'),
                ),
                migrations.AlterField(
                    model_name='entriessv',
                    name='key',
                    field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantssv'),
                ),
                migrations.AlterField(
                    model_name='hgmdseqrvariantsgrch37snvindel',
                    name='key',
                    field=models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantsgrch37snvindel'),
                ),
                migrations.AlterField(
                    model_name='hgmdseqrvariantssnvindel',
                    name='key',
                    field=models.OneToOneField(db_column='key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clickhouse_search.variantssnvindel'),
                ),
            ]
        ),
    ]
