# Generated by Django 4.2.24 on 2026-02-06 17:31

from django.db import migrations


def validate_data_migrated(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # If the data migration has been run, then variants should be present in any variant table that had corresponding annotations
    for table_type in ['SnvIndel', 'GRCh37SnvIndel', 'Mito', 'Sv', 'Gcnv']:
        variants = apps.get_model('clickhouse_search', f'Variants{table_type}')
        annotations = apps.get_model('clickhouse_search', f'Annotations{table_type}')
        if variants.objects.using(db_alias).exists() != annotations.objects.using(db_alias).exists():
            raise Exception('Data migration has not been run')


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0041_variant_details_path'),
    ]

    operations = [
        migrations.RunPython(validate_data_migrated, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='TranscriptsGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='TranscriptsSnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskGcnv',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskMito',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskSnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsDiskSv',
        ),
        migrations.DeleteModel(
            name='AnnotationsGcnv',
        ),
        migrations.DeleteModel(
            name='AnnotationsMito',
        ),
        migrations.DeleteModel(
            name='AnnotationsSv',
        ),
        migrations.DeleteModel(
            name='AnnotationsGRCh37SnvIndel',
        ),
        migrations.DeleteModel(
            name='AnnotationsSnvIndel',
        ),
    ]
