# Generated by Django 4.2.27 on 2026-05-14 21:48

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0042_delete_annotationsdiskgcnv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryVariantDict',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('dataset_type', clickhouse_backend.models.StringField()),
                ('family_guids',
                 clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
            ],
            options={
                'db_table': 'seqrdb_discovery_variant_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key=('key', 'dataset_type')),
                'layout': 'COMPLEX_KEY_HASHED()',
                'postgres_query': "SELECT sv.key as key, sv.dataset_type as dataset_type, array_agg(distinct f.guid) as family_guids FROM seqr_savedvariant sv INNER JOIN seqr_family f ON sv.family_id = f.id WHERE sv.id IN (SELECT savedvariant_id FROM seqr_varianttag_saved_variants vts LEFT JOIN seqr_varianttag vt ON vts.varianttag_id = vt.id LEFT JOIN seqr_varianttagtype vtt ON vt.variant_tag_type_id = vtt.id WHERE vtt.category = ''CMG Discovery Tags'') GROUP BY sv.key, sv.dataset_type",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedVariantDict',
            fields=[
                ('key', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('dataset_type', clickhouse_backend.models.StringField()),
                ('family_guids',
                 clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
            ],
            options={
                'db_table': 'seqrdb_excluded_variant_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key=('key', 'dataset_type')),
                'layout': 'COMPLEX_KEY_HASHED()',
                'postgres_query': "SELECT sv.key as key, sv.dataset_type as dataset_type, array_agg(distinct f.guid) as family_guids FROM seqr_savedvariant sv INNER JOIN seqr_family f ON sv.family_id = f.id WHERE sv.id IN (SELECT savedvariant_id FROM seqr_varianttag_saved_variants vts LEFT JOIN seqr_varianttag vt ON vts.varianttag_id = vt.id LEFT JOIN seqr_varianttagtype vtt ON vt.variant_tag_type_id = vtt.id WHERE vtt.name = ''Excluded'') GROUP BY sv.key, sv.dataset_type",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualMetadataDict',
            fields=[
                ('family_guid', clickhouse_backend.models.StringField(primary_key=True, serialize=False)),
                ('sampleId', clickhouse_backend.models.StringField()),
                ('restrict_sharing', clickhouse_backend.models.BoolField()),
                ('features', clickhouse_backend.models.StringField()),
                ('omim_id', clickhouse_backend.models.UInt32Field()),
                ('mondo_id', clickhouse_backend.models.StringField()),
                ('is_solved', clickhouse_backend.models.BoolField()),
                ('vlm_contact_email', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'seqrdb_individual_metadata_dict',
                'engine': clickhouse_backend.models.MergeTree(primary_key=('family_guid', 'sampleId')),
                'layout': 'COMPLEX_KEY_HASHED()',
                'postgres_query': "select f.guid as family_guid, i.individual_id as sampleId, p.restrict_sharing as restrict_sharing, i.features as features, f.post_discovery_omim_numbers[1] as omim_id, f.post_discovery_mondo_id as mondo_id, f.analysis_status in (''S'', ''S_kgfp'', ''S_kgdp'', ''S_ng'', ''ES'') as is_solved, p.vlm_contact_email as vlm_contact_email FROM seqr_individual i INNER JOIN seqr_family f ON i.family_id = f.id INNER JOIN seqr_project p ON f.project_id = p.id",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL('SYSTEM RELOAD DICTIONARY "seqrdb_discovery_variant_dict"'),
        migrations.RunSQL('SYSTEM RELOAD DICTIONARY "seqrdb_excluded_variant_dict"'),
        migrations.RunSQL('SYSTEM RELOAD DICTIONARY "seqrdb_individual_metadata_dict"'),
    ]
