# Generated by Django 4.2.27 on 2026-06-09 18:19

import clickhouse_backend.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clickhouse_search', '0043_discoveryvariantdict_excludedvariantdict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmimDict',
            fields=[
                ('mim_number', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('phenotype_description', clickhouse_backend.models.StringField()),
            ],
            options={
                'db_table': 'seqrdb_omim',
                'engine': clickhouse_backend.models.MergeTree(primary_key='mim_number'),
                'layout': 'HASHED()',
                'postgres_query': 'SELECT phenotype_mim_number, phenotype_description FROM reference_data_omim where phenotype_mim_number is not null',
                'postgres_db': 'reference_data',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL('SYSTEM RELOAD DICTIONARY "seqrdb_omim"'),
    ]
