command = 'gunicorn'
bind = '0.0.0.0:8000'
workers = 1
loglevel = 'info'
timeout = 3600   # seconds (default is 30)
accesslog = '-'
errorlog = '-'  # logs to stderr
worker_class = 'aiohttp.GunicornWebWorker'
access_log_format = '%{From}i "%r" %s %Tfs'
