export PS1="\h:\w]$ "

export SHELL=/bin/bash

export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ll="ls -al"
alias less='less -m -g -i--underline-special --SILENT'
alias more='less'

export TERM=xterm
resize

echo
echo This shell is in the PIPELINE-RUNNER container.
echo

alias gs='gsutil'

export PATH=/usr/local/spark-2.0.2-bin-hadoop2.7/bin:$PATH

export HAIL_HOME=/hail
export SPARK_HOME=/usr/local/spark-2.0.2-bin-hadoop2.7
export PYTHONPATH="$PYTHONPATH:$HAIL_HOME/python:$SPARK_HOME/python:$(echo $SPARK_HOME/python/lib/py4j*-src.zip)"
export PYTHONPATH="$PYTHONPATH:/hail/build/distributions/hail-python.zip"
export SPARK_CLASSPATH=$HAIL_HOME/build/libs/hail-all-spark.jar


echo SHELL: $SHELL
echo PATH: $PATH
echo PYTHONPATH: $PYTHONPATH
echo
echo SPARK_HOME: $SPARK_HOME
echo SPARK_CLASSPATH: $SPARK_CLASSPATH
echo HAIL_HOME: HAIL_HOME

