# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gencodegene',
            name='gene_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gencodetranscript',
            name='transcript_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
