# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_auto_20170319_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('genome_build_id', models.CharField(choices=[(b'b37', b'b37'), (b'b38', b'b38')], max_length=3)),
                ('chrom', models.CharField(max_length=1)),
                ('pos', models.IntegerField()),
                ('ref', models.TextField(blank=True, null=True)),
                ('alt', models.TextField(blank=True, null=True)),
                ('measureset_type', models.TextField(blank=True, null=True)),
                ('measureset_id', models.TextField(blank=True, null=True)),
                ('rcv', models.TextField(blank=True, null=True)),
                ('allele_id', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('hgvs_c', models.TextField(blank=True, null=True)),
                ('hgvs_p', models.TextField(blank=True, null=True)),
                ('molecular_consequence', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('pathogenic', models.BooleanField()),
                ('benign', models.BooleanField()),
                ('conflicted', models.BooleanField()),
                ('review_status', models.TextField(blank=True, null=True)),
                ('gold_stars', models.IntegerField()),
                ('all_submitters', models.TextField(blank=True, null=True)),
                ('all_traits', models.TextField(blank=True, null=True)),
                ('all_pmids', models.TextField(blank=True, null=True)),
                ('inheritance_modes', models.TextField(blank=True, null=True)),
                ('age_of_onset', models.TextField(blank=True, null=True)),
                ('prevalence', models.TextField(blank=True, null=True)),
                ('disease_mechanism', models.TextField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
