# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0004_auto_20170626_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gencoderelease',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gencoderelease',
            name='release_number',
            field=models.IntegerField(),
        ),
    ]
