# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0006_auto_20170630_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencodegene',
            name='genome_version',
            field=models.CharField(choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], default='37', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gencodetranscript',
            name='genome_version',
            field=models.CharField(choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], default='37', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gencodegene',
            name='gene_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gencodegene',
            name='gene_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gencodetranscript',
            name='transcript_support_level',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gencodegene',
            unique_together=set([('genome_version', 'gene_id', 'chrom', 'start', 'end')]),
        ),
        migrations.RemoveField(
            model_name='gencodetranscript',
            name='transcript_status',
        ),
        migrations.AlterUniqueTogether(
            name='gencodetranscript',
            unique_together=set([('genome_version', 'transcript_id', 'chrom', 'start', 'end')]),
        ),
        migrations.RemoveField(
            model_name='gencodegene',
            name='gene_status',
        ),
        migrations.RemoveField(
            model_name='gencodegene',
            name='gencode_release',
        ),
        migrations.RemoveField(
            model_name='gencodetranscript',
            name='gencode_release',
        ),
        migrations.DeleteModel(
            name='GencodeRelease',
        ),
    ]
