# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0007_auto_20180809_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_values', models.TextField(blank=True, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.GeneInfo')),
            ],
        ),
    ]
