# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 20:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0008_geneexpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='expression_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='geneexpression',
            name='gene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reference_data.GeneInfo'),
        ),
    ]
