# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0014_auto_20190510_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneconstraint',
            name='louef',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geneconstraint',
            name='louef_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
