# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0015_auto_20190625_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[(b'heart', b'heart'), (b'nerve', b'nerve'), (b'brain', b'brain'), (b'colon', b'colon'), (b'skin', b'skin'), (b'esophagus', b'esophagus'), (b'kidney', b'kidney'), (b'thyroid', b'thyroid'), (b'testis', b'testis'), (b'adipose_tissue', b'adipose_tissue'), (b'blood_vessel', b'blood_vessel'), (b'vagina', b'vagina'), (b'cells_-_ebv-transformed_lymphocytes', b'cells_-_ebv-transformed_lymphocytes'), (b'stomach', b'stomach'), (b'breast', b'breast'), (b'whole_blood', b'whole_blood'), (b'prostate', b'prostate'), (b'ovary', b'ovary'), (b'pancreas', b'pancreas'), (b'cells_-_transformed_fibroblasts', b'cells_-_transformed_fibroblasts'), (b'adrenal_gland', b'adrenal_gland'), (b'salivary_gland', b'salivary_gland'), (b'spleen', b'spleen'), (b'small_intestine', b'small_intestine'), (b'uterus', b'uterus'), (b'lung', b'lung'), (b'pituitary', b'pituitary'), (b'muscle', b'muscle'), (b'liver', b'liver')], max_length=40),
        ),
    ]
