# Generated by Django 3.1.3 on 2021-03-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0017_auto_20190909_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneCopyNumberSensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pHI', models.FloatField()),
                ('pTS', models.FloatField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.geneinfo')),
            ],
        ),
    ]
