# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0017_auto_20190909_2102'),
        ('reference_data', '0017_auto_20190827_1711'),
    ]

    operations = [
    ]
