# Generated by Django 3.2.13 on 2022-04-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_gencc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haploinsufficiency', models.TextField()),
                ('triplosensitivity', models.TextField()),
                ('href', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.geneinfo')),
            ],
        ),
    ]
