# Generated by Django 3.2.23 on 2023-12-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0022_geneshet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omim',
            name='phenotypic_series_number',
        ),
    ]
