# Generated by Django 3.2.23 on 2023-12-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0022_geneshet'),
    ]

    operations = [
        migrations.AddField(
            model_name='omim',
            name='chrom',
            field=models.CharField(default='30', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='omim',
            name='end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='omim',
            name='start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='omim',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_data.geneinfo'),
        ),
    ]
