# Generated by Django 4.2.18 on 2025-03-19 20:54

from django.db import migrations, models

from reference_data.models import HumanPhenotypeOntology, GeneInfo, GeneConstraint, \
    GeneCopyNumberSensitivity, GeneShet, Omim, dbNSFPGene, PrimateAI, MGI, GenCC, ClinGen

def get_current_versions(apps, schema_editor):
    DataVersions = apps.get_model('reference_data', 'DataVersions')
    db_alias = schema_editor.connection.alias
    versions = [DataVersions(data_model_name=model.__name__, version=model.CURRENT_VERSION or '') for model in [
        HumanPhenotypeOntology, GeneInfo, GeneConstraint, GeneCopyNumberSensitivity, GeneShet, Omim,
        dbNSFPGene, PrimateAI, MGI, GenCC, ClinGen,
    ] if model.objects.exists()]
    DataVersions.objects.using(db_alias).bulk_create(versions)


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0024_auto_20231218_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersions',
            fields=[
                ('data_model_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
            ],
        ),
        migrations.RunPython(get_current_versions, reverse_code=migrations.RunPython.noop),
    ]
