FROM python:3.7-slim-bullseye as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        libc6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# init new venv
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

WORKDIR /seqr
COPY requirements.txt .
RUN pip install --no-cache-dir wheel && pip install --no-cache-dir -r requirements.txt

FROM python:3.7-slim-bullseye as runtime

COPY --from=build /venv /venv

# install base OS dependencies
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg2 \
        curl \
        procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install google cloud SDK
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-bullseye main" > /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && apt-get update && apt-get install -y --no-install-recommends \
        google-cloud-sdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# copy in current seqr checkout
WORKDIR /seqr
COPY . .

EXPOSE 8000

COPY deploy/docker/seqr/readiness_probe /
COPY deploy/docker/seqr/bin/*.sh /usr/local/bin/
COPY deploy/docker/seqr/config/*.py ./
COPY deploy/docker/seqr/bashrc /root/.bashrc
COPY deploy/docker/seqr/entrypoint.sh /

ENV PATH="/venv/bin:$PATH"
CMD [ "/entrypoint.sh" ]
