#!/bin/bash

###
# Usage: ./wait_for_routes https://www.google.com/ https://www.broadinstitute.org https://www.broadins.org
###

RETRY_COUNT=10

for route in "$@"
do
    retries=0
    until [ "$retries" -ge 10 ]
    do
        curl -s $route -o /dev/null && echo "Successful ping of $route" && break
        retries=$((retries+1))
        if [ "$retries" -eq 10 ]; then
            echo "Route ${route} wasn't available after ${RETRY_COUNT} connection attempts"
            exit 1
        else
            echo "Unable to connect to ${route}, retrying. Attempt ${retries}/${RETRY_COUNT}"
            sleep 1
        fi
    done
done