# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='analysis_status_date_saved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='analysis_status_saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
