# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160526_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantnote',
            name='search_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='search_url',
            field=models.TextField(null=True),
        ),
    ]
