# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160612_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='coverage_status',
            field=models.CharField(choices=[(b'S', b'In Sequencing'), (b'I', b'Interim'), (b'C', b'Complete'), (b'A', b'Abandoned')], default=b'S', max_length=1),
        ),
        migrations.AddField(
            model_name='individual',
            name='mean_target_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
