# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161013_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='internal_case_review_notes',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='internal_case_review_short_summary',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='analysis_status',
            field=models.CharField(choices=[(b'S', b'Solved'), (b'S_kgfp', b'Solved - known gene for phenotype'), (b'S_kgdp', b'Solved - gene linked to different phenotype'), (b'S_ng', b'Solved - novel gene'), (b'Sc_kgfp', b'Strong candidate - known gene for phenotype'), (b'Sc_kgdp', b'Strong candidate - gene linked to different phenotype'), (b'Sc_ng', b'Strong candidate - novel gene'), (b'Rcpc', b'Reviewed, currently pursuing candidates'), (b'Rncc', b'Reviewed, no clear candidate'), (b'I', b'Analysis in Progress'), (b'Q', b'Waiting for data')], default=b'Q', max_length=10),
        ),
    ]
