# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20161110_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='after_load_qc_json',
        ),
        migrations.RemoveField(
            model_name='family',
            name='before_load_qc_json',
        ),
        migrations.RemoveField(
            model_name='family',
            name='has_after_load_qc_error',
        ),
        migrations.RemoveField(
            model_name='family',
            name='has_before_load_qc_error',
        ),
        migrations.RemoveField(
            model_name='family',
            name='relatedness_matrix_json',
        ),
        migrations.RemoveField(
            model_name='family',
            name='variant_stats_json',
        ),
    ]
