# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20161112_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
