# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20161113_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='phenotips_features',
            new_name='phenotips_data',
        ),
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(blank=True, choices=[(b'U', b'Uncertain'), (b'A', b'Accepted'), (b'E', b'Accepted - Exome'), (b'G', b'Accepted - Genome'), (b'R', b'Not Accepted'), (b'N', b'See Notes'), (b'H', b'Hold')], default=b'', max_length=1, null=True),
        ),
    ]
