# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20161125_1810'),
        ('base', '0013_breakpoint_breakpointfile_breakpointgene_breakpointmetadata'),
    ]

    operations = [
    ]
