# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20161202_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
