# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_individual_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='pedigree_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'pedigree_images'),
        ),
    ]
