# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170207_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='guid',
            field=models.SlugField(max_length=165, unique=True),
        ),
    ]
