# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20170509_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='combined_families_info',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='project',
            name='combined_projects_info',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
