# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20170514_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='category',
            field=models.TextField(default=b''),
        ),
    ]
