# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_projecttag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
