# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_projecttag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='order',
            field=models.FloatField(null=True),
        ),
    ]
