# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20170518_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='combined_individuals_info',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
