# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20170606_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='tag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='title',
            field=models.TextField(default=b''),
        ),
    ]
