# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_variantnote_submit_to_clinvar'),
        ('base', '0031_auto_20170713_0732'),
    ]

    operations = [
    ]
