# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20170812_1543'),
        ('base', '0031_variantnote_submit_to_clinvar'),
    ]

    operations = [
    ]
