# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_merge_20170913_1920'),
        ('base', '0035_auto_20171106_0815'),
    ]

    operations = [
    ]
