# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20170812_1543'),
        ('base', '0037_auto_20171112_1649'),
    ]

    operations = [
    ]
