# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0028_auto_20171123_0200'),
        ('base', '0037_auto_20171112_1649'),
    ]

    operations = [

    ]
