# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20171130_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(blank=True, choices=[(b'N', b'Not In Review'), (b'I', b'In Review'), (b'U', b'Uncertain'), (b'A', b'Accepted'), (b'R', b'Not Accepted'), (b'Q', b'More Info Needed'), (b'P', b'Pending Results and Records'), (b'W', b'Waitlist'), (b'WD', b'Withdrew'), (b'IE', b'Ineligible'), (b'DP', b'Declined to Participate')], default=b'', max_length=2, null=True),
        ),
    ]
