# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_merge_20171128_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(blank=True, choices=[(b'N', b'Not In Review'), (b'I', b'In Review'), (b'U', b'Uncertain'), (b'A', b'Accepted'), (b'R', b'Not Accepted'), (b'Q', b'More Info Needed'), (b'P', b'Pending Results and Records'), (b'W', b'Waitlist')], default=b'', max_length=1, null=True),
        ),
    ]
