# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20171112_1649'),
    ]

    operations = [

    ]
