# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20171130_0154'),
        ('base', '0039_auto_20171214_1104'),
    ]

    operations = [
    ]
