# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20171128_0204'),
        ('base', '0034_auto_20171102_0000'),
    ]

    operations = [
    ]
