# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0040_merge_20180119_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='vcffile',
            name='needs_reannotate',
        ),
        migrations.AddField(
            model_name='family',
            name='internal_analysis_status',
            field=models.CharField(blank=True, choices=[(b'S', b'Solved'), (b'S_kgfp', b'Solved - known gene for phenotype'), (b'S_kgdp', b'Solved - gene linked to different phenotype'), (b'S_ng', b'Solved - novel gene'), (b'Sc_kgfp', b'Strong candidate - known gene for phenotype'), (b'Sc_kgdp', b'Strong candidate - gene linked to different phenotype'), (b'Sc_ng', b'Strong candidate - novel gene'), (b'Rcpc', b'Reviewed, currently pursuing candidates'), (b'Rncc', b'Reviewed, no clear candidate'), (b'I', b'Analysis in Progress'), (b'Q', b'Waiting for data')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='case_review_discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='case_review_status_last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='case_review_status_last_modified_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='phenotips_patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='genome_version',
            field=models.CharField(default=b'37', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='is_mme_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_phenotips_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='mme_contact_institution',
            field=models.TextField(blank=True, default=b'Broad Center for Mendelian Genomics', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mme_contact_url',
            field=models.TextField(blank=True, default=b'mailto:matchmaker@broadinstitute.org', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mme_primary_data_owner',
            field=models.TextField(blank=True, default=b'Samantha Baxter', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phenotips_user_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vcffile',
            name='dataset_type',
            field=models.CharField(choices=[(b'VARIANTS', b'Variant Calls'), (b'SV', b'SV Calls')], default=b'VARIANTS', max_length=10),
        ),
        migrations.AddField(
            model_name='vcffile',
            name='elasticsearch_index',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vcffile',
            name='loaded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcffile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.SlugField(blank=True, default=b'', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='vcffile',
            name='file_path',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
