# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20180214_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcffile',
            name='sample_type',
            field=models.CharField(blank=True, choices=[(b'WES', b'Exome'), (b'WGS', b'Whole Genome'), (b'RNA', b'RNA'), (b'ARRAY', b'ARRAY')], max_length=3, null=True),
        ),
    ]
