# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_genenote'),
        ('base', '0044_analysedby'),
    ]

    operations = [
    ]
