# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_merge_20180308_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disease_area',
            field=models.CharField(blank=True, choices=[(b'blood', b'Blood'), (b'cardio', b'Cardio'), (b'kidney', b'Kidney'), (b'muscle', b'Muscle'), (b'neurodev', b'Neurodev'), (b'orphan_disease', b'Orphan Disease'), (b'retinal', b'Retinal')], max_length=20, null=True),
        ),
    ]
