# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_merge_20180308_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disease_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
