# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0046_project_disease_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantFunctionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_data_tag', models.TextField()),
                ('metadata', models.TextField(null=True)),
                ('date_saved', models.DateTimeField(null=True)),
                ('xpos', models.BigIntegerField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('search_url', models.TextField(null=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='is_functional_data_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
