# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20180322_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disable_staff_access',
            field=models.BooleanField(default=False),
        ),
    ]
