# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0037_auto_20180515_1440'),
        ('base', '0047_auto_20180322_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantfunctionaldata',
            name='seqr_variant_functional_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.VariantFunctionalData'),
        ),
    ]
