# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_remove_individual_case_review_status_accepted_for'),
        ('base', '0048_variantfunctionaldata_seqr_variant_functional_data'),
    ]

    operations = [
    ]
