# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_merge_20180531_1604'),
        ('base', '0050_merge_20180603_1309'),
    ]

    operations = [
    ]
