# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0044_familyanalysedby'),
        ('base', '0052_auto_20180719_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedby',
            name='seqr_family_analysed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.FamilyAnalysedBy'),
        ),
    ]
