command = 'gunicorn'
bind = '127.0.0.1:8000'
workers = 1
pythonpath='/seqr,/seqr_settings'
timeout = 3600   # seconds (default is 30)
errorlog = '-'  # '${INSTALL_DIR}/logs/gunicorn-error.log'
accesslog = '-' # '${INSTALL_DIR}/logs/gunicorn-access.log'
loglevel = 'info'
#worker_tmp_dir = '/tmp'