# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0001_squashed_0067_remove_project_custom_reference_populations'),
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakercontactnotes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='matchmakerresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='matchmakerresult',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='matchmakerresult',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_deleted_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_deleted_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_submitted_data',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_submitted_date',
        ),
        migrations.DeleteModel(
            name='MatchmakerContactNotes',
        ),
        migrations.DeleteModel(
            name='MatchmakerResult',
        ),
    ]
