# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('genome_build_id', models.CharField(choices=[(b'b37', b'b37'), (b'b38', b'b38')], default=b'b37', max_length=5)),
                ('xpos_start', models.BigIntegerField()),
                ('xpos_end', models.BigIntegerField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('gene_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transcript_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('molecular_consequence', models.CharField(blank=True, max_length=35, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='molecular_consequence',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='transcript_id',
        ),
        migrations.AddField(
            model_name='varianttag',
            name='variant_annotation',
            field=models.ManyToManyField(to='seqr.VariantAnnotation'),
        ),
        migrations.AlterIndexTogether(
            name='varianttag',
            index_together=set([('xpos_start', 'ref', 'alt', 'genome_build_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='variantannotation',
            unique_together=set([('genome_build_id', 'xpos_start', 'xpos_end', 'ref', 'alt')]),
        ),
        migrations.AlterIndexTogether(
            name='variantannotation',
            index_together=set([('xpos_start', 'ref', 'alt', 'genome_build_id')]),
        ),
    ]
