# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0002_auto_20170309_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='phenotips_patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
