# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0003_auto_20170313_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(blank=True, choices=[(b'I', b'In Review'), (b'U', b'Uncertain'), (b'A', b'Accepted: Platform Uncertain'), (b'E', b'Accepted: Exome'), (b'G', b'Accepted: Genome'), (b'3', b'Accepted: RNA-seq'), (b'R', b'Not Accepted'), (b'H', b'Hold'), (b'Q', b'More Info Needed')], max_length=1, null=True),
        ),
    ]
