# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 19:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0003_auto_20191203_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlastaccesseddate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlastaccesseddate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedfileforfamily',
            name='family',
        ),
        migrations.RemoveField(
            model_name='uploadedfileforfamily',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='uploadedfileforindividual',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='uploadedfileforindividual',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='family',
            name='causal_inheritance_mode',
        ),
        migrations.RemoveField(
            model_name='locuslistgene',
            name='description',
        ),
        migrations.RemoveField(
            model_name='locuslistinterval',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deprecated_project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='disease_area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_new_search',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_functional_data_enabled',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_phenotips_enabled',
        ),
        migrations.RemoveField(
            model_name='variantfunctionaldata',
            name='search_parameters',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='search_parameters',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='search_parameters',
        ),
        migrations.RemoveField(
            model_name='varianttagtype',
            name='is_built_in',
        ),
        migrations.AlterField(
            model_name='variantnote',
            name='note',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ProjectLastAccessedDate',
        ),
        migrations.DeleteModel(
            name='UploadedFileForFamily',
        ),
        migrations.DeleteModel(
            name='UploadedFileForIndividual',
        ),
    ]
