# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0005_auto_20170319_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sample_id', models.TextField()),
                ('individual_id', models.TextField(blank=True, null=True)),
                ('sample_status', models.CharField(choices=[(b'S', b'In Sequencing'), (b'I', b'Interim'), (b'C', b'Complete'), (b'A', b'Abandoned')], default=b'S', max_length=1)),
                ('source_file_path', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sequencingsample',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sequencingsample',
            name='sample_batch',
        ),
        migrations.RenameField(
            model_name='samplebatch',
            old_name='sequencing_type',
            new_name='sample_type',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='sequencing_samples',
        ),
        migrations.DeleteModel(
            name='SequencingSample',
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seqr.SampleBatch'),
        ),
        migrations.AddField(
            model_name='individual',
            name='samples',
            field=models.ManyToManyField(to='seqr.Sample'),
        ),
    ]
