# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 18:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0006_family_mme_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(choices=[(b'I', b'In Review'), (b'U', b'Uncertain'), (b'A', b'Accepted'), (b'R', b'Not Accepted'), (b'Q', b'More Info Needed'), (b'P', b'Pending Results and Records'), (b'N', b'NMI Review'), (b'W', b'Waitlist'), (b'L', b'Lost To Follow-Up'), (b'V', b'Inactive')], default=b'I', max_length=2),
        ),
    ]
