# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0006_auto_20170430_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='internal_case_review_brief_summary',
            new_name='internal_case_review_summary',
        ),
        migrations.RemoveField(
            model_name='samplebatch',
            name='variant_callset_is_loaded',
        ),
        migrations.RemoveField(
            model_name='samplebatch',
            name='variant_callset_loaded_date',
        ),
        migrations.RemoveField(
            model_name='samplebatch',
            name='variant_callset_path',
        ),
        migrations.AddField(
            model_name='sample',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='loaded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
