# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 18:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0006_family_mme_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='case_review_status',
            field=models.CharField(choices=[('I', 'In Review'), ('U', 'Uncertain'), ('A', 'Accepted'), ('R', 'Not Accepted'), ('Q', 'More Info Needed'), ('P', 'Pending Results and Records'), ('N', 'NMI Review'), ('W', 'Waitlist'), ('L', 'Lost To Follow-Up'), ('V', 'Inactive')], default='I', max_length=2),
        ),
    ]
