# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20170509_0046'),
        ('seqr', '0007_auto_20170509_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='deprecated_base_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
    ]
