# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0010_auto_20200413_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='proband_relationship',
            field=models.CharField(choices=[(b'S', b'Self'), (b'M', b'Mother'), (b'F', b'Father'), (b'B', b'Sibling'), (b'C', b'Child'), (b'H', b'Maternal Half Sibling'), (b'J', b'Paternal Half Sibling'), (b'G', b'Maternal Grandmother'), (b'W', b'Maternal Grandfather'), (b'X', b'Paternal Grandmother'), (b'Y', b'Paternal Grandfather'), (b'A', b'Maternal Aunt'), (b'L', b'Maternal Uncle'), (b'E', b'Paternal Aunt'), (b'D', b'Paternal Uncle'), (b'N', b'Niece'), (b'P', b'Nephew'), (b'Z', b'Maternal 1st Cousin'), (b'K', b'Paternal 1st Cousin'), (b'O', b'Other'), (b'U', b'Unknown')], max_length=1, null=True),
        ),
    ]
