# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0011_auto_20170517_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
