# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0011_individual_proband_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='phenotips_data',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='phenotips_eid',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='phenotips_patient_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phenotips_user_id',
        ),
    ]
