# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 19:41
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0012_auto_20200603_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='sv_flags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
