# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0013_individual_sv_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnvilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anvil_username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_namespace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
