# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-17 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0013_individual_sv_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_namespace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
