# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('seqr', '0013_individual_sv_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('privacy_version', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('tos_version', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
