# Generated by Django 3.1.3 on 2020-11-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0015_auto_20201112_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyanalysedby',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seqr.family'),
        ),
    ]
