# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0015_auto_20170606_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='individual_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='maternal_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='paternal_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deprecated_last_accessed_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deprecated_project_id',
            field=models.TextField(blank=True, db_index=True, default=b''),
        ),
        migrations.AlterField(
            model_name='project',
            name='mme_primary_data_owner',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='phenotips_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
