# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0015_anviluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anviluser',
            old_name='anvil_user_name',
            new_name='anvil_username',
        ),
    ]
