# Generated by Django 3.1.3 on 2020-11-24 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0016_auto_20201120_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='pubmed_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='family',
            name='success_story_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('N', 'Novel Discovery'), ('A', 'Altered Clinical Outcome'), ('C', 'Collaboration'), ('T', 'Technical Win'), ('D', 'Data Sharing'), ('O', 'Other')], max_length=1, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='individual',
            name='absent_features',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='absent_nonstandard_features',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='affected_relatives',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_donoregg',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_donorsperm',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_fertility_meds',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_icsi',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_iui',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_ivf',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ar_surrogacy',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='candidate_genes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='consanguinity',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='features',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='filter_flags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='nonstandard_features',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='pop_platform_filters',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='rejected_genes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sv_flags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedvariant',
            name='saved_variant_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='variantsearch',
            name='search',
            field=models.JSONField(),
        ),
    ]
