# Generated by Django 3.1.3 on 2020-12-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0017_auto_20201124_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='internal_case_review_notes',
            new_name='case_review_notes',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='internal_case_review_summary',
            new_name='case_review_summary',
        ),
        migrations.RemoveField(
            model_name='family',
            name='internal_analysis_status',
        ),
        migrations.AddField(
            model_name='project',
            name='has_case_review',
            field=models.BooleanField(default=False),
        ),
    ]
