# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0018_auto_20170626_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locuslistentry',
            old_name='genome_build_id',
            new_name='genome_version',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='genome_build_id',
            new_name='genome_version',
        ),
        migrations.RenameField(
            model_name='variantnote',
            old_name='genome_build_id',
            new_name='genome_version',
        ),
        migrations.RenameField(
            model_name='varianttag',
            old_name='genome_build_id',
            new_name='genome_version',
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_file_path',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='locuslistentry',
            unique_together=set([('parent', 'genome_version', 'feature_id', 'chrom', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='varianttag',
            unique_together=set([('variant_tag_type', 'genome_version', 'xpos_start', 'xpos_end', 'ref', 'alt', 'family')]),
        ),
        migrations.AlterIndexTogether(
            name='varianttag',
            index_together=set([('xpos_start', 'ref', 'alt', 'genome_version')]),
        ),
    ]
