# Generated by Django 3.1.3 on 2021-01-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0020_remove_project_disable_staff_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='igvsample',
            name='sample_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='igvsample',
            name='sample_type',
            field=models.CharField(choices=[('alignment', 'Bam/Cram'), ('wig', 'RNAseq Coverage'), ('spliceJunctions', 'RNAseq Junction'), ('gcnv', 'gCNV')], default='alignment', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='igvsample',
            unique_together={('individual', 'sample_type')},
        ),
    ]
