# Generated by Django 3.1.3 on 2021-02-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0021_auto_20210125_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedvariant',
            old_name='xpos_start',
            new_name='xpos',
        ),
        migrations.AlterUniqueTogether(
            name='savedvariant',
            unique_together={('xpos', 'xpos_end', 'variant_id', 'family')},
        ),
    ]
