# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0022_auto_20170704_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_external_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='causal_inheritance_mode',
            field=models.CharField(choices=[(b'r', b'recessive'), (b'u', b'unknown'), (b'd', b'dominant'), (b'x', b'x-linked recessive'), (b'n', b'de novo')], default=b'u', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[(b'WES', b'Exome'), (b'WGS', b'Whole Genome'), (b'RNA', b'RNA'), (b'ARRAY', b'ARRAY')], max_length=3),
        ),
    ]
