# Generated by Django 3.1.3 on 2021-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0022_auto_20210201_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='privacy_version',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='tos_version',
            field=models.FloatField(null=True),
        ),
    ]
