# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0023_auto_20170909_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mme_contact_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mme_primary_data_owner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
