# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0025_auto_20171106_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantsDataset',
            fields=[
            ],
            options={
                'db_table': 'dataset',
                'proxy': True,
                'indexes': [],
            },
            bases=('seqr.dataset',),
        ),
        migrations.RemoveField(
            model_name='project',
            name='genome_version',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_location',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='genome_version',
            field=models.CharField(choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], default=b'37', max_length=5),
        ),
        migrations.AddField(
            model_name='variantnote',
            name='lifted_over_genome_version',
            field=models.CharField(blank=True, choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='variantnote',
            name='lifted_over_xpos_start',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='lifted_over_genome_version',
            field=models.CharField(blank=True, choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='lifted_over_xpos_start',
            field=models.BigIntegerField(null=True),
        ),
    ]
