# Generated by Django 3.1.6 on 2021-05-21 18:36

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0025_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianttagtype',
            name='metadata_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='varianttagtype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.project'),
        ),
    ]
