# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0026_auto_20171112_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantsDataset',
        ),
        migrations.CreateModel(
            name='ElasticsearchDataset',
            fields=[
            ],
            options={
                'db_table': 'dataset',
                'proxy': True,
                'indexes': [],
            },
            bases=('seqr.dataset',),
        ),
        migrations.AlterField(
            model_name='variantnote',
            name='xpos_end',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varianttag',
            name='xpos_end',
            field=models.BigIntegerField(null=True),
        ),
    ]
