# Generated by Django 3.1.13 on 2021-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0026_auto_20210521_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='classification',
            field=models.JSONField(null=True),
        ),
    ]
