# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0028_auto_20171123_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_file_path',
            field=models.TextField(db_index=True),
        ),
    ]
