# Generated by Django 3.1.13 on 2021-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0028_auto_20210826_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='classification',
            field=models.JSONField(null=True),
        ),
    ]
