# Generated by Django 3.1.13 on 2021-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0029_auto_20210826_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='acmg_classification',
            field=models.JSONField(null=True),
        ),
    ]
