# Generated by Django 3.1.13 on 2021-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0029_auto_20210826_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_hgmd',
            field=models.BooleanField(default=False),
        ),
    ]
