# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0029_auto_20171130_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mme_contact_institution',
            field=models.TextField(blank=True, default=b'Broad Center for Mendelian Genomics', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_mme_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mme_contact_url',
            field=models.TextField(blank=True, default=b'mailto:matchmaker@broadinstitute.org', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mme_primary_data_owner',
            field=models.TextField(blank=True, default=b'Samantha Baxter', null=True),
        ),
    ]
