# Generated by Django 3.1.13 on 2021-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0030_project_enable_hgmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='all_user_demo',
            field=models.BooleanField(default=False),
        ),
    ]
