# Generated by Django 3.1.13 on 2021-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0031_project_all_user_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('header', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
