# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0032_auto_20171218_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='deprecated_base_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Project'),
        ),
        migrations.AlterField(
            model_name='uploadedfileforfamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seqr.Family'),
        ),
        migrations.AlterField(
            model_name='uploadedfileforfamily',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfileforindividual',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seqr.Individual'),
        ),
        migrations.AlterField(
            model_name='uploadedfileforindividual',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
