# Generated by Django 3.1.13 on 2021-10-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0032_warningmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='acmg_classification',
            field=models.JSONField(null=True),
        ),
    ]
