# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0033_auto_20180111_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantnote',
            name='variant_annotation',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='variant_annotation',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='variant_genotypes',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='variant_genotypes',
        ),
        migrations.AddField(
            model_name='variantnote',
            name='saved_variant_json',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='saved_variant_json',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='disease_area',
            field=models.CharField(blank=True, choices=[(b'blood', b'Blood'), (b'cardio', b'Cardio'), (b'kidney', b'Kidney'), (b'muscle', b'Muscle'), (b'neurodev', b'Neurodev'), (b'orphan_disease', b'Orphan Disease'), (b'retinal', b'Retinal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_functional_data_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
