# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0034_auto_20180411_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('genome_version', models.CharField(choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], default=b'37', max_length=5)),
                ('xpos_start', models.BigIntegerField()),
                ('xpos_end', models.BigIntegerField(null=True)),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('lifted_over_genome_version', models.CharField(blank=True, choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], max_length=5, null=True)),
                ('lifted_over_xpos_start', models.BigIntegerField(null=True)),
                ('saved_variant_json', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.Family')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VariantFunctionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('functional_data_tag', models.TextField()),
                ('metadata', models.TextField(null=True)),
                ('search_url', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('saved_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.SavedVariant')),
            ],
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='family',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='genome_version',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='lifted_over_genome_version',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='lifted_over_xpos_start',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='project',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='saved_variant_json',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='xpos_end',
        ),
        migrations.RemoveField(
            model_name='variantnote',
            name='xpos_start',
        ),
        migrations.AlterIndexTogether(
            name='varianttag',
            index_together=set([]),
        ),
        migrations.AddField(
            model_name='variantnote',
            name='saved_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.SavedVariant'),
        ),
        migrations.AddField(
            model_name='varianttag',
            name='saved_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.SavedVariant'),
        ),
        migrations.AlterUniqueTogether(
            name='varianttag',
            unique_together=set([('variant_tag_type', 'saved_variant')]),
        ),
        migrations.AlterUniqueTogether(
            name='variantfunctionaldata',
            unique_together=set([('functional_data_tag', 'saved_variant')]),
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='family',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='genome_version',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='lifted_over_genome_version',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='lifted_over_xpos_start',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='saved_variant_json',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='xpos_end',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='xpos_start',
        ),
        migrations.AlterUniqueTogether(
            name='savedvariant',
            unique_together=set([('genome_version', 'xpos_start', 'xpos_end', 'ref', 'alt', 'project', 'family')]),
        ),
        migrations.AlterIndexTogether(
            name='savedvariant',
            index_together=set([('xpos_start', 'ref', 'alt', 'genome_version', 'project')]),
        ),
    ]
