# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0034_auto_20180411_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantnote',
            name='submit_to_clinvar',
            field=models.BooleanField(default=False),
        ),
    ]
