# Generated by Django 3.2.11 on 2022-01-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0034_auto_20211208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsearch',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
