# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0035_variantnote_submit_to_clinvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocusListGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('gene_id', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocusListInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('genome_version', models.CharField(choices=[(b'37', b'GRCh37'), (b'38', b'GRCh38')], default=b'37', max_length=5)),
                ('chrom', models.CharField(max_length=2)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locuslistentry',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='locuslistentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='locuslistentry',
            name='parent',
        ),
        migrations.AlterField(
            model_name='locuslist',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.DeleteModel(
            name='LocusListEntry',
        ),
        migrations.AddField(
            model_name='locuslistinterval',
            name='locus_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.LocusList'),
        ),
        migrations.AddField(
            model_name='locuslistgene',
            name='locus_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.LocusList'),
        ),
        migrations.AlterUniqueTogether(
            name='locuslistinterval',
            unique_together=set([('locus_list', 'genome_version', 'chrom', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='locuslistgene',
            unique_together=set([('locus_list', 'gene_id')]),
        ),
    ]
