# Generated by Django 3.2.11 on 2022-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0035_variantsearch_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='tissue_type',
            field=models.CharField(blank=True, choices=[('WB', 'Whole Blood'), ('F', 'Fibroblast'), ('M', 'Muscle'), ('L', 'Lymphocyte')], max_length=2, null=True),
        ),
    ]
