# Generated by Django 3.2.11 on 2022-02-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0036_auto_20220201_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyanalysedby',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.family'),
        ),
    ]
