# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0036_auto_20180415_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='case_review_status_accepted_for',
        ),
    ]
