# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0037_project_disable_staff_access'),
        ('seqr', '0037_remove_individual_case_review_status_accepted_for'),
    ]

    operations = [
    ]
