# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0038_merge_20180530_2034'),
        ('seqr', '0038_merge_20180525_1800'),
    ]

    operations = [
    ]
