# Generated by Django 3.2.13 on 2022-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0039_project_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyanalysedby',
            name='data_type',
            field=models.CharField(choices=[('SNP', 'WES/WGS'), ('SV', 'gCNV/SV'), ('RNA', 'RNAseq'), ('MT', 'Mitochondrial'), ('STR', 'STR')], default='SNP', max_length=3),
            preserve_default=False,
        ),
    ]
