# Generated by Django 3.2.13 on 2022-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0040_familyanalysedby_data_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rnaseqoutlier',
            index=models.Index(fields=['gene_id'], name='seqr_rnaseq_gene_id_a6ad2f_idx'),
        ),
        migrations.AddIndex(
            model_name='rnaseqoutlier',
            index=models.Index(fields=['p_adjust'], name='seqr_rnaseq_p_adjus_59a417_idx'),
        ),
    ]
