# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0040_auto_20180603_1309'),
        ('seqr', '0040_auto_20180612_1513'),
    ]

    operations = [
    ]
