# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0041_genenote'),
        ('seqr', '0041_merge_20180621_1247'),
    ]

    operations = [
    ]
