# Generated by Django 3.2.13 on 2022-06-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0042_alter_sample_dataset_type'),
        ('seqr', '0042_auto_20220621_1852'),
    ]

    operations = [
    ]
