# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0044_familyanalysedby'),
        ('seqr', '0044_auto_20180723_1808'),
    ]

    operations = [
    ]
