# Generated by Django 3.2.14 on 2022-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0044_alter_variantfunctionaldata_functional_data_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consent_code',
            field=models.CharField(blank=True, choices=[('HMB', 'HMB'), ('GRU', 'GRU'), ('Other', 'Other')], max_length=5, null=True),
        ),
    ]
