# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0045_auto_20180801_1933'),
        ('seqr', '0045_merge_20180726_1246'),
    ]

    operations = [
    ]
