# Generated by Django 3.2.14 on 2022-08-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seqr', '0045_project_consent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='can_edit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='can_view_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group'),
        ),
    ]
