# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0046_merge_20180803_1534'),
        ('seqr', '0046_auto_20180803_1708'),
    ]

    operations = [
    ]
