# Generated by Django 3.2.15 on 2022-10-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0046_auto_20220831_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_mme_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
