# Generated by Django 3.2.14 on 2022-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0046_auto_20220831_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='analyte_type',
            field=models.CharField(blank=True, choices=[
                ('D', 'DNA'), ('R', 'RNA'), ('B', 'blood plasma'), ('F', 'frozen whole blood'),
                ('H', 'high molecular weight DNA'), ('U', 'urine')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='primary_biosample',
            field=models.CharField(blank=True, choices=[
                ('T', 'UBERON:0000479'), ('NT', 'UBERON:0003714'), ('S', 'UBERON:0001836'), ('SE', 'UBERON:0001003'),
                ('MT', 'UBERON:0002385'), ('WB', 'UBERON:0000178'), ('BM', 'UBERON:0002371'), ('CC', 'UBERON:0006956'),
                ('CF', 'UBERON:0001359'), ('U', 'UBERON:0001088'), ('NE', 'UBERON:0019306')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='tissue_affected_status',
            field=models.BooleanField(null=True),
        ),
    ]
