# Generated by Django 3.2.15 on 2022-09-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0047_auto_20220908_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypePrioritization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20)),
                ('tool', models.CharField(choices=[('E', 'exomiser'), ('L', 'lirical')], max_length=1)),
                ('rank', models.IntegerField()),
                ('disease_id', models.CharField(max_length=32)),
                ('scores', models.JSONField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.sample')),
            ],
            options={
                'unique_together': {('sample', 'gene_id', 'disease_id')},
            },
        ),
    ]
