# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0047_merge_20180809_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_hash', models.CharField(db_index=True, max_length=50, unique=True)),
                ('search', models.TextField()),
                ('es_index', models.TextField(null=True)),
                ('results', models.TextField(null=True)),
                ('total_results', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='varianttag',
            name='variant_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.VariantSearch'),
        ),
    ]
