# Generated by Django 3.2.15 on 2022-10-14 20:38

from django.db import migrations, models
import django.db.models.deletion
import seqr.models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0047_auto_20220908_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypePrioritization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20)),
                ('tool', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('disease_id', models.CharField(max_length=32)),
                ('disease_name', models.TextField()),
                ('scores', models.JSONField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.individual')),
            ],
            bases=(models.Model, seqr.models.BulkOperationBase),
        ),
    ]
