# Generated by Django 3.2.15 on 2023-01-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0047_alter_project_is_mme_enabled'),
        ('seqr', '0048_phenotypeprioritization'),
    ]

    operations = [
    ]
