# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0048_auto_20180918_2030'),
        ('seqr', '0048_auto_20181106_1639'),
    ]

    operations = [
    ]
