# Generated by Django 3.2.15 on 2023-02-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0049_family_mondo_id'),
        ('seqr', '0049_merge_20230108_2118'),
    ]

    operations = [
    ]
