# Generated by Django 3.2.18 on 2023-04-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0049_family_mondo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnaSeqSpliceOutlier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20)),
                ('p_value', models.FloatField()),
                ('z_score', models.FloatField()),
                ('chrom', models.CharField(max_length=2)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(choices=[('+', '5′ to 3′ direction'), ('-', '3′ to 5′ direction'), ('*', 'Any direction')], max_length=1)),
                ('type', models.CharField(max_length=12)),
                ('delta_psi', models.FloatField()),
                ('read_count', models.IntegerField()),
                ('rare_disease_samples_with_junction', models.IntegerField()),
                ('rare_disease_samples_total', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seqr.sample')),
            ],
            options={
                'unique_together': {('sample', 'gene_id', 'chrom', 'start', 'end', 'strand', 'type')},
            },
        ),
    ]
