# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 19:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0049_auto_20190114_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='pubmed_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
