# Generated by Django 3.2.18 on 2023-04-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0050_rnaseqspliceoutlier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnaseqoutlier',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rnaseqspliceoutlier',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rnaseqtpm',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
