# Generated by Django 3.2.18 on 2023-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0051_auto_20230426_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
