# Generated by Django 3.2.15 on 2023-05-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0050_merge_0049_family_mondo_id_0049_merge_20230108_2118'),
        ('seqr', '0051_auto_20230426_1615'),
    ]

    operations = [
    ]
