# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0051_auto_20190320_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantsearchresults',
            name='es_index',
        ),
    ]
