# Generated by Django 3.2.19 on 2023-06-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0051_auto_20230426_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
