# Generated by Django 3.2.18 on 2023-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0052_rnaseqspliceoutlier_rank'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rnaseqoutlier',
            name='seqr_rnaseq_gene_id_a6ad2f_idx',
        ),
        migrations.AlterField(
            model_name='rnaseqoutlier',
            name='gene_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rnaseqspliceoutlier',
            name='gene_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rnaseqtpm',
            name='gene_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='rnaseqoutlier',
            index=models.Index(fields=['sample_id', 'gene_id'], name='seqr_rnaseq_sample__bdd363_idx'),
        ),
        migrations.AddIndex(
            model_name='rnaseqtpm',
            index=models.Index(fields=['sample_id', 'gene_id'], name='seqr_rnaseq_sample__e7153a_idx'),
        ),
    ]
