# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0052_remove_variantsearchresults_es_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deprecated_last_accessed_date',
            new_name='last_accessed_date',
        ),
    ]
