# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0053_auto_20190405_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_new_search',
            field=models.BooleanField(default=False),
        ),
    ]
