# Generated by Django 3.2.18 on 2023-09-28 16:05

from django.db import migrations, models
from django.contrib.postgres.aggregates import ArrayAgg

SAMPLE_TISSUE_MAP = {sample_id: 'A' for sample_id in {
    'MCH-103_1_NE1', 'MCH-75_1_NE1', 'MCH-44_1_NE1', 'MCH-80_1_NE1', 'MCH-199_1_NE1', 'MCH-68_1_NE1', 'MCH-55_1_NE1',
    'MCH-69_1_NE1', 'MCH-198_1_NE1',
}}


def update_tissue_type(apps, schema_editor):
    Sample = apps.get_model('seqr', 'Sample')
    db_alias = schema_editor.connection.alias

    samples = Sample.objects.using(db_alias).filter(tissue_type__isnull=True)
    if not samples:
        return

    rna_samples = samples.filter(sample_type='RNA', is_active=True)
    individual_tissue_map = {}
    for agg in Sample.objects.using(db_alias).filter(
        tissue_type__isnull=False, individual_id__in=rna_samples.values_list('individual_id', flat=True),
    ).values('individual_id').annotate(tissue_types=ArrayAgg('tissue_type', distinct=True)):
        if len(agg['tissue_types']) == 1:
            individual_tissue_map[agg['individual_id']] = agg['tissue_types'][0]

    for s in rna_samples:
        if s.individual_id in individual_tissue_map:
            s.tissue_type = individual_tissue_map[s.individual_id]
        elif s.data_source.startswith('fibroblasts__'):
            s.tissue_type = 'F'
        elif s.data_source.startswith('muscle__'):
            s.tissue_type = 'M'
        else:
            s.tissue_type = SAMPLE_TISSUE_MAP[s.sample_id]

    print(f'Updating {len(rna_samples)} RNA samples')
    Sample.objects.using(db_alias).bulk_update(rna_samples, ['tissue_type'])

    non_rna_samples = samples.exclude(id__in=[s.id for s in rna_samples])
    print(f'Updating {len(non_rna_samples)} non-RNA samples to default tissue type')
    non_rna_samples.update(tissue_type='X')


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0054_alter_sample_dataset_type'),
    ]

    operations = [
        migrations.RunPython(update_tissue_type, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sample',
            name='tissue_type',
            field=models.CharField(choices=[('WB', 'whole_blood'), ('F', 'fibroblasts'), ('M', 'muscle'), ('L', 'lymphocytes'), ('A', 'airway_cultured_epithelium'), ('X', 'None')], max_length=2),
        ),
    ]
