# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 20:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0055_remove_sample_dataset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('we_contacted', models.BooleanField(default=False)),
                ('host_contacted', models.BooleanField(default=False)),
                ('deemed_irrelevant', models.BooleanField(default=False)),
                ('flag_for_analysis', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='mme_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='mme_deleted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='mme_submitted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mme_submitted_data',
        ),
        migrations.AddField(
            model_name='individual',
            name='mme_submitted_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seqr.Individual'),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
