# Generated by Django 3.2.18 on 2023-10-26 14:42

from django.db import migrations, models


def clear_splice_outlier_data(apps, schema_editor):
    RnaSeqSpliceOutlier = apps.get_model('seqr', 'RnaSeqSpliceOutlier')
    db_alias = schema_editor.connection.alias
    RnaSeqSpliceOutlier.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0056_alter_family_post_discovery_omim_number'),
    ]

    operations = [
        migrations.RunPython(clear_splice_outlier_data, reverse_code=migrations.RunPython.noop),
        migrations.RenameField(
            model_name='rnaseqspliceoutlier',
            old_name='read_count',
            new_name='counts',
        ),
        migrations.RenameField(
            model_name='rnaseqspliceoutlier',
            old_name='p_value',
            new_name='p_adjust',
        ),
        migrations.RenameField(
            model_name='rnaseqspliceoutlier',
            old_name='rare_disease_samples_with_junction',
            new_name='rare_disease_samples_with_this_junction',
        ),
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='delta_intron_jaccard_index',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='mean_counts',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='total_counts',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='rnaseqspliceoutlier',
            name='mean_total_counts',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='rnaseqspliceoutlier',
            unique_together={('sample', 'gene_id', 'chrom', 'start', 'end', 'type')},
        ),
        migrations.RemoveField(
            model_name='rnaseqspliceoutlier',
            name='delta_psi',
        ),
        migrations.RemoveField(
            model_name='rnaseqspliceoutlier',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='rnaseqspliceoutlier',
            name='z_score',
        ),
    ]
