# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0056_auto_20190513_1621'),
        ('seqr', '0056_auto_20190424_2059'),
    ]

    operations = [
    ]
