# Generated by Django 3.2.19 on 2024-01-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0052_merge_20230516_0343'),
        ('seqr', '0058_alter_sample_dataset_type'),
    ]

    operations = [
    ]
