# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0059_auto_20190705_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakerresult',
            name='match_removed',
            field=models.BooleanField(default=False),
        ),
    ]
