# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0060_matchmakerresult_match_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='filter_flags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='pop_platform_filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='population',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
