# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0062_merge_20190723_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='success_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='success_story_type',
            field=models.CharField(blank=True, choices=[(b'ND', b'N'), (b'ACO', b'A'), (b'C', b'C'), (b'TW', b'T'), (b'DS', b'D'), (b'O', b'O')], max_length=10, null=True),
        ),
    ]
