# Generated by Django 3.2.25 on 2024-04-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0059_merge_20240116_2354'),
        ('seqr', '0062_individual_solve_status'),
    ]

    operations = [
    ]
