# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 18:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0062_merge_20190723_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='success_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='success_story_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'N', b'Novel Discovery'), (b'A', b'Altered Clinical Outcome'), (b'C', b'Collaboration'), (b'T', b'Technical Win'), (b'D', b'Data Sharing'), (b'O', b'Other')], max_length=1, null=True), default=[], size=None),
        ),
    ]
