# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0063_auto_20190729_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default=b'#1f78b4', max_length=20)),
                ('order', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='success_story_type',
        ),
        migrations.AddField(
            model_name='successstorytype',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seqr.Family'),
        ),
        migrations.AlterUniqueTogether(
            name='successstorytype',
            unique_together=set([('family', 'name', 'color')]),
        ),
    ]
