# Generated by Django 3.2.23 on 2024-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0063_dynamicanalysisgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='igvsample',
            name='index_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
