# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0063_auto_20190806_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paternal_children', to='seqr.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternal_children', to='seqr.Individual'),
        ),
    ]
