# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0063_auto_20190723_1825'),
        ('seqr', '0064_auto_20190823_2112'),
    ]

    operations = [
    ]
