# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0064_auto_20190823_2112'),
        ('seqr', '0064_auto_20190826_1748'),
    ]

    operations = [
    ]
