# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0065_merge_20190827_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantnote',
            old_name='saved_variant',
            new_name='saved_variants',
        ),
    ]
