# Generated by Django 3.2.23 on 2024-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0065_family_external_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='post_discovery_mondo_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
