# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0066_auto_20191007_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='custom_reference_populations',
        ),
    ]
