# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0066_auto_20190924_1422'),
        ('seqr', '0066_auto_20191007_1946'),
    ]

    operations = [
    ]
