# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-30 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0065_merge_20190827_2031'),
        ('seqr', '0067_auto_20190827_1957'),
    ]

    operations = [
    ]
