# Generated by Django 3.2.23 on 2024-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0067_alter_variantfunctionaldata_functional_data_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='igvsample',
            name='index_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
