# Generated by Django 3.2.23 on 2024-06-28 15:44

from django.db import migrations, models


def update_vlm_contact_email(apps, schema_editor):
    Project = apps.get_model('seqr', 'Project')
    db_alias = schema_editor.connection.alias

    projects = Project.objects.using(db_alias).all()
    for project in projects:
        project.vlm_contact_email = project.mme_contact_url.replace('mailto:', '').replace('matchmaker', 'vlm')
    Project.objects.using(db_alias).bulk_update(projects, ['vlm_contact_email'])


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0067_alter_variantfunctionaldata_functional_data_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vlm_contact_email',
            field=models.TextField(blank=True, default='vlm@broadinstitute.org', null=True),
        ),
        migrations.RunPython(update_vlm_contact_email, reverse_code=migrations.RunPython.noop),
    ]
