# Generated by Django 4.2.13 on 2024-07-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0070_remove_rnasample_dataset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igvsample',
            name='index_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
