# Generated by Django 4.2.15 on 2024-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0073_alter_variantfunctionaldata_functional_data_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='primary_biosample',
            field=models.CharField(blank=True, choices=[
                ('IP', 'CL:0000034'), ('MO', 'CL:0000576'), ('LY', 'CL:0000542'), ('FI', 'CL:0000057'),
                ('EM', 'UBERON:0005291'), ('NP', 'CL:0011020'), ('CE', 'UBERON:0002037'), ('CA', 'UBERON:0001133')
            ], max_length=2, null=True),
        ),
    ]

