# Generated by Django 4.2.15 on 2024-08-26 15:27
from tqdm import tqdm

from django.db import migrations

def update_genotype_for_individual_to_array(apps, schema_editor):
    SavedVariant = apps.get_model("seqr", "SavedVariant")
    db_alias = schema_editor.connection.alias
    variants = SavedVariant.objects.using(db_alias).all()
    if variants:
        print('Updating  {} variants'.format(len(variants)))
        for variant in tqdm(variants, unit=' variants'):
            genotypes = variant.saved_variant_json.get('genotypes', {})
            for individual, genotype in genotypes.items():
                genotypes[individual] = [genotype]
            variant.genotypes = genotypes
            variant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0073_alter_variantfunctionaldata_functional_data_tag'),
    ]

    operations = [
        migrations.RunPython(update_genotype_for_individual_to_array, reverse_code=migrations.RunPython.noop),
    ]
