# Generated by Django 4.2.13 on 2024-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0074_alter_individual_add_primary_biosample_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='primary_biosample',
            field=models.CharField(blank=True, choices=[('T', 'UBERON:0000479'), ('NT', 'UBERON:0003714'), ('S', 'UBERON:0001836'), ('SE', 'UBERON:0001003'), ('MT', 'UBERON:0002385'), ('WB', 'UBERON:0000178'), ('BM', 'UBERON:0002371'), ('CC', 'UBERON:0006956'), ('CF', 'UBERON:0001359'), ('U', 'UBERON:0001088'), ('NE', 'UBERON:0019306'), ('IP', 'CL:0000034'), ('MO', 'CL:0000576'), ('LY', 'CL:0000542'), ('FI', 'CL:0000057'), ('EM', 'UBERON:0005291'), ('NP', 'CL:0011020'), ('CE', 'UBERON:0002037'), ('CA', 'UBERON:0001133')], max_length=2, null=True),
        ),
    ]
