# Generated by Django 4.2.13 on 2024-10-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0075_alter_individual_primary_biosample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('XXY', 'XXY'), ('XYY', 'XYY'), ('XXX', 'XXX'), ('X0', 'X0')], default='U', max_length=3),
        ),
    ]
