# Generated by Django 4.2.16 on 2025-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0078_rename_submit_to_clinvar_variantnote_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='analysis_status',
            field=models.CharField(choices=[('S', 'S'), ('S_kgfp', 'S'), ('S_kgdp', 'S'), ('S_ng', 'S'), ('ES', 'E'), ('Sc_kgfp', 'S'), ('Sc_kgdp', 'S'), ('Sc_ng', 'S'), ('Rcpc', 'R'), ('Rncc', 'R'), ('C', 'C'), ('PB', 'P'), ('P', 'P'), ('I', 'A'), ('Q', 'W'), ('F', 'L'), ('N', 'N')], default='Q', max_length=10),
        ),
    ]
