# Generated by Django 4.2.22 on 2025-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0079_alter_family_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='genotypes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='savedvariant',
            name='key',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
