# Generated by Django 4.2.24 on 2026-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0081_savedvariant_gene_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recovery_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='restrict_hpo_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
