# Generated by Django 4.2.24 on 2026-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0082_project_recovery_email_project_restrict_hpo_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnaseqspliceoutlier',
            name='rare_disease_samples_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rnaseqspliceoutlier',
            name='rare_disease_samples_with_this_junction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
