# Generated by Django 4.2.24 on 2026-02-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0083_alter_rnaseqspliceoutlier_rare_disease_samples_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='restrict_hpo_sharing',
            new_name='restrict_sharing',
        ),
    ]
