# Generated by Django 4.2.24 on 2026-03-19 15:57

from collections import defaultdict
from django.db import migrations, models

from clickhouse_search.backend.fields import NamedTupleField
from clickhouse_search.backend.functions import ArrayIndex, ArrayObjectSort
from clickhouse_search.models.search_models import VARIANT_DETAILS_CLASS_MAP
from clickhouse_search.search import get_variant_details_queryset
import seqr.views.utils.json_utils

BATCH_SIZE = 10000


def populate_saved_variant_fields(apps, schema_editor):
    SavedVariant = apps.get_model('seqr', 'SavedVariant')
    db_alias = schema_editor.connection.alias
    no_key_variants = SavedVariant.objects.using(db_alias).filter(key__isnull=True)
    no_key_variants.filter(saved_variant_json__genotypes__isnull=False).update(
        genotypes=models.F('saved_variant_json__genotypes'),
    )
    no_key_variants.filter(saved_variant_json__svType__isnull=False).update(
        sv_type=models.F('saved_variant_json__svType'),
        dataset_type='SV',
    )
    no_key_variants.filter(sv_type__isnull=True).update(dataset_type='SNV_INDEL')

    to_update = []
    transcript_variants = no_key_variants.filter(sv_type__isnull=True, saved_variant_json__transcripts__isnull=False).exclude(saved_variant_json__transcripts={})
    for variant in transcript_variants:
        main_transcript_id = variant.selected_main_transcript_id or variant.saved_variant_json.get('mainTranscriptId')
        if main_transcript_id:
            variant.main_transcript = next(
                t for ts in variant.saved_variant_json['transcripts'].values() for t in ts
                if t['transcriptId'] == main_transcript_id
            )
            to_update.append(variant)
    SavedVariant.objects.using(db_alias).bulk_update(to_update, ['main_transcript'])


def populate_clickhouse_main_transcript(apps, schema_editor):
    SavedVariant = apps.get_model('seqr', 'SavedVariant')
    db_alias = schema_editor.connection.alias

    _update_field_from_clickhouse(
        SavedVariant, db_alias, 'main_transcript', 'MITO',
        expression=models.F('sorted_transcript_consequences__0'),
    )

    for genome_version in ['38', '37']:
        output_field = VARIANT_DETAILS_CLASS_MAP[genome_version].transcripts.field.clone()
        _update_field_from_clickhouse(
            SavedVariant, db_alias, 'main_transcript', 'SNV_INDEL', genome_version=genome_version,
            family__project__genome_version=genome_version,
            expression=ArrayIndex(0, ArrayObjectSort('transcripts', sort_field='transcriptRank'), base_field=NamedTupleField(output_field.base_fields)),
        )

        output_field.group_by_key = 'transcriptId'
        output_field.flatten_groups = True
        _update_field_from_clickhouse(
            SavedVariant, db_alias, 'main_transcript', 'SNV_INDEL', genome_version=genome_version,
            family__project__genome_version=genome_version, selected_main_transcript_id__isnull=False,
            expression=ArrayObjectSort('transcripts', sort_field='transcriptId', output_field=output_field),
            process_value=lambda transcripts, variant: transcripts.get(variant.selected_main_transcript_id, variant.main_transcript),
        )


def populate_clickhouse_sv_type(apps, schema_editor):
    SavedVariant = apps.get_model('seqr', 'SavedVariant')
    db_alias = schema_editor.connection.alias

    for dataset_type in ['SV_WGS', 'SV_WES']:
        _update_field_from_clickhouse(SavedVariant, db_alias, 'sv_type', dataset_type)


def _update_field_from_clickhouse(SavedVariant, db_alias, field, dataset_type, genome_version='38', expression=None, process_value=None, **filters):
    variants = SavedVariant.objects.using(db_alias).filter(key__isnull=False, dataset_type=dataset_type, **filters)
    if not variants.exists():
        return
    variants_by_key = defaultdict(list)
    for v in variants:
        variants_by_key[v.key].append(v)
    all_keys = sorted(variants_by_key.keys())
    print(f'Populating {field} for {len(all_keys)} {dataset_type} ({genome_version}) clickhouse variants')
    for i in range(0, len(all_keys), BATCH_SIZE):
        batch_keys = all_keys[i:i + BATCH_SIZE]
        clickhouse_qs = get_variant_details_queryset(genome_version, dataset_type, batch_keys)
        to_update = []
        if expression:
            clickhouse_qs = clickhouse_qs.annotate(**{field: expression})
        for key, value in clickhouse_qs.using('clickhouse').values_list('key', field):
            for variant in variants_by_key[key]:
                if process_value:
                    value = process_value(value, variant)
                setattr(variant, field, value)
                to_update.append(variant)
        num_updated = SavedVariant.objects.using(db_alias).bulk_update(to_update, [field])
        print(f'Updated {num_updated} variants')


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0084_rename_restrict_hpo_sharing_project_restrict_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvariant',
            name='main_transcript',
            field=models.JSONField(default=dict, encoder=seqr.views.utils.json_utils.DjangoJSONEncoderWithSets),
        ),
        migrations.AddField(
            model_name='savedvariant',
            name='sv_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.RunPython(populate_saved_variant_fields, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_clickhouse_main_transcript, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_clickhouse_sv_type, reverse_code=migrations.RunPython.noop),
    ]
