# Generated by Django 4.2.24 on 2026-03-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0085_savedvariant_main_transcript_savedvariant_sv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnasample',
            name='tissue_type',
            field=models.CharField(choices=[('WB', 'whole_blood'), ('F', 'fibroblasts'), ('M', 'muscle'), ('L', 'lymphocytes'), ('A', 'airway_cultured_epithelium'), ('B', 'brain'), ('LV', 'liver'), ('S', 'skin')], max_length=2),
        ),
    ]
