# Generated by Django 4.2.24 on 2026-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0087_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnasample',
            name='sequencing_type',
            field=models.CharField(choices=[('K', 'Kinnex'), ('T', 'Tru-Seq'), ('W', 'Watchmaker')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
