# Generated by Django 4.2.24 on 2026-05-04 18:13

from django.db import migrations
from pyliftover.liftover import LiftOver

from seqr.utils.xpos_utils import get_xpos, get_chrom_pos


def populate_saved_variant_json_fields(apps, schema_editor):
    SavedVariant = apps.get_model('seqr', 'SavedVariant')
    db_alias = schema_editor.connection.alias

    saved_variants_q = SavedVariant.objects.using(db_alias)
    update_variants = saved_variants_q.filter(key__isnull=True, sv_type__isnull=True)

    # Some edge cases were missed in the initial migration to set the main transcript
    to_update = []
    transcript_variants = update_variants.filter(
        gene_ids__len__gt=0, main_transcript={}, saved_variant_json__mainTranscriptId__isnull=False,
    )
    for variant in transcript_variants:
        main_transcript_id = variant.selected_main_transcript_id or variant.saved_variant_json.get('mainTranscriptId')
        if main_transcript_id:
            variant.main_transcript = next(
                t for ts in variant.saved_variant_json['transcripts'].values() for t in ts
                if t['transcriptId'] == main_transcript_id
            )
            to_update.append(variant)
    if to_update:
        updated = saved_variants_q.bulk_update(to_update, ['main_transcript'])
        print(f'Updated main transcript for {updated} variants')

    # Some variants failed to lift to 38 when project build was updated, run liftover on these
    to_update = []
    lifover_variants = update_variants.filter(saved_variant_json__genomeVersion='37', family__project__genome_version='38')
    if lifover_variants.exists():
        VariantNote = apps.get_model('seqr', 'VariantNote')
        note_q = VariantNote.objects.using(db_alias)
        _liftover_variants(lifover_variants, saved_variants_q, note_q)

    # Some variants are inexplicably saved on 38 despite being in 37 projects,
    # use existing liftover to map to the correct project genome version
    to_update = []
    liftunder_variants = update_variants.filter(saved_variant_json__genomeVersion='38', family__project__genome_version='37')
    for variant in liftunder_variants:
        chrom = variant.saved_variant_json['liftedOverChrom']
        pos = variant.saved_variant_json['liftedOverPos']
        variant.xpos = get_xpos(chrom, pos)
        variant.variant_id = f'{chrom}-{pos}-{variant.ref}-{variant.alt}'
        to_update.append(variant)
    if to_update:
        updated = saved_variants_q.bulk_update(to_update, ['xpos', 'variant_id'])
        print(f'Lifted under {updated} variants')


def _liftover_variants(lifover_variants, saved_variants_q, note_q):
    to_update = []
    skipped = 0
    liftover = LiftOver('hg19', 'hg38')
    for variant in lifover_variants:
        chrom, pos = get_chrom_pos(variant.xpos)
        lifted_coord = liftover.convert_coordinate(f'chr{chrom}', pos)

        if not lifted_coord:
            note = note_q.create(note='Variant tagged on build GRCh37', guid=variant.guid.replace('SV', 'VN'))
            note.saved_variants.add(variant)
            skipped += 1
            continue

        lifted_pos = lifted_coord[0][1]
        variant.xpos = get_xpos(chrom, lifted_pos)
        variant.variant_id = f'{chrom}-{lifted_pos}-{variant.ref}-{variant.alt}'
        to_update.append(variant)

    updated = saved_variants_q.bulk_update(to_update, ['xpos', 'variant_id'])
    print(f'Lifted over {updated} variants')
    if skipped:
        print(f'Skipped liftover for {skipped} variants, added notes to affected variants')


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0088_rnasample_sequencing_type'),
    ]

    operations = [
        migrations.RunPython(populate_saved_variant_json_fields, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='savedvariant',
            name='saved_variant_json',
        ),
    ]
