# Generated by Django 4.2.27 on 2026-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqr', '0089_remove_savedvariant_saved_variant_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='workspace_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisgroup',
            name='workspace_namespace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
