name: hail search persistent volume snapshot release
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - prod
      reference_genome:
         type: choice
         description: Reference Genome
         options:
         - GRCh37
         - GRCh38
         required: true
      dataset_type:
        type: choice
        description: Dataset Type
        options:
        - SNV_INDEL
        - MITO
        - GCNV
        - SV
        required: true
      version:
        required: false
      volume_handle:
        required: true

env:
  CHART_NAME: "${{ inputs.environment == 'dev' && 'dev-' || '' }}broad-seqr"

jobs:
  helm_update:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve tgg-helm repo for broad seqr chart
        uses: actions/checkout@v3
        with:
          repository: broadinstitute/tgg-helm
          token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: update dataset version in the broad-seqr chart
        if: "${{ inputs.version != '' }}"
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.global.hail_search.datasetVersions.${{ inputs.reference_genome }}/${{ inputs.dataset_type }} = "${{ inputs.version }}"' charts/${{ env.CHART_NAME }}/values.yaml

      - name: update volume handle in the broad-seqr chart
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.hail-search.persistentVolume.volumeHandle = "${{ inputs.volume_handle }}"' charts/${{ env.CHART_NAME }}/values.yaml

      - name: Commit and Push changes
        uses: Andro999b/push@v1.3
        with:
          repository: broadinstitute/tgg-helm
          branch: main
          github_token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          author_name: tgg-automation
          message: "Updating ${{ inputs.environment }} ${{ inputs.reference_genome }}/${{ inputs.dataset_type }} ${{ inputs.version != '' && format('{0} {1} {2}', 'dataset version to', inputs.version, 'and') || ''}} volume handle to ${{ inputs.volume_handle }} "
