name: VLM Unit Tests
permissions:
  contents: read

# Run the test suite on pushes (incl. merges) to master and dev
# Run the test suite when a PR is opened, pushed to, or reopened
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'vlm/**'
      - '.github/workflows/*vlm*.yaml'
      - 'clickhouse_search/fixtures/clickhouse_search.json'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'vlm/**'
      - '.github/workflows/*vlm*.yaml'
      - 'clickhouse_search/fixtures/clickhouse_search.json'

jobs:
  vlm_clickhouse:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: bitnamilegacy/clickhouse:latest
        ports:
          - 8123:8123   # HTTP interface
          - 9000:9000   # Native client interface
        volumes:
          - /var/tmp:/var/seqr/clickhouse-data
          - /tmp:/in-memory-dir
        options: >-
          --health-cmd "clickhouse-client --query 'SELECT 1'"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
          --name clickhouse
        env:
          CLICKHOUSE_USER: clickhouse_test_user
          CLICKHOUSE_PASSWORD: clickhouse_test_password
          ALLOW_EMPTY_PASSWORD: no
      postgres:
        image: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: pgtest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          pip install -r vlm/requirements.txt
          pip install -r vlm/requirements-test.txt
      - name: Set up Clickhouse Settings
        run: |
          cat <<EOF > test_config.xml
          <clickhouse>
            <users>
              <clickhouse_test>
                <named_collection_control>1</named_collection_control>
              </clickhouse_test>
            </users>
          </clickhouse>
          EOF
          docker cp ${{ github.workspace }}/test_config.xml clickhouse:/etc/clickhouse-server/users.d/users.xml
          docker exec clickhouse clickhouse-client --query "CREATE NAMED COLLECTION seqr_postgres_named_collection AS user='postgres', password='pgtest', host='postgres', port='5432'"
      - name: Set up Clickhouse Test Database
        run: | 
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r vlm/requirements.txt
          pip install -r vlm/requirements-test.txt
          pip install pytest-django
          pip install -r requirements.txt 
          pip install -r requirements-dev.txt 
          export CLICKHOUSE_WRITER_USER=clickhouse_test_user
          export CLICKHOUSE_WRITER_PASSWORD=clickhouse_test_password
          export CLICKHOUSE_SERVICE_HOSTNAME=localhost
          export POSTGRES_SERVICE_HOSTNAME=localhost
          python3 -m pytest --setup-only --create-db --reuse-db --ds=settings -vv
          python3 -u manage.py loaddata clickhouse_search --database=clickhouse_write
      - name: Set up Clickhouse User
        run: |
          docker exec clickhouse clickhouse-client --query "CREATE USER vlm_test_user IDENTIFIED WITH plaintext_password BY 'vlm_test_password'"
          docker exec clickhouse clickhouse-client --query "SYSTEM RELOAD USERS"
          docker exec clickhouse clickhouse-client --query "GRANT SELECT ON test_seqr.`GRCh37/SNV_INDEL/key_lookup` TO vlm_test_user"
          docker exec clickhouse clickhouse-client --query "GRANT SELECT ON test_seqr.`GRCh38/SNV_INDEL/key_lookup` TO vlm_test_user"
          docker exec clickhouse clickhouse-client --query "GRANT dictGet ON test_seqr.`GRCh37/SNV_INDEL/gt_stats_dict` TO vlm_test_user"
          docker exec clickhouse clickhouse-client --query "GRANT dictGet ON test_seqr.`GRCh38/SNV_INDEL/gt_stats_dict` TO vlm_test_user"
          docker exec clickhouse clickhouse-client --query "SYSTEM RELOAD USERS"
      - name: Run coverage tests
        run: |
          export SEQR_BASE_URL=https://test-seqr.org/
          export NODE_ID=TestVLM
          export CLICKHOUSE_SERVICE_HOSTNAME=localhost
          export CLICKHOUSE_SERVICE_PORT=8123
          export CLICKHOUSE_VLM_USERNAME=vlm_test_user
          export CLICKHOUSE_VLM_PASSWORD=vlm_test_password
          export CLICKHOUSE_DATABASE=test_seqr
          coverage run --source="./vlm" --omit="./vlm/__main__.py" -m pytest vlm/ --reuse-db
          coverage report -m --fail-under=95

