apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: {{ NAMESPACE }}
  config:
    xpack.security.sameSiteCookies: None
    xpack.security.secureCookies: true
    server.customResponseHeaders: {"x-frame-options":"sameorigin"}
  podTemplate:
    metadata:
      annotations:
            linkerd.io/inject: enabled
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
    spec:
      automountServiceAccountToken: true
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
  http:
    tls:
      selfSignedCertificate:
        disabled: true
